### ISSUE TITLE
1-click buttons dash and underscore substitution

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#100]
I need to label (no attributes, only simple bbox label) a bbox with a text containing dashes.
If I enter the label `7_segments-2` manually in the textbox the label is stored correctly.
If I use the 1-click button with caption `7_segments-2` the dash is converted to underscore, resulting in `7_segments_2`.

**Comment by ryouchinsa** [comment]
Basically RectLabel uses '-' as a separator among the object and attributes.
Even if you are not using attributes, we are using this rule.
If we change this rule suddenly, the data loading module of our users would be affected.
Do you have a good idea?

**Comment by mentezar** [comment]
ok. I understand the reason. It's good.
Basically I wanted to directly use a label with embedded object attribute on my own like `my_label-myattr1`.

Often is useful to rely on standard RectLabel object-attribute workflow but sometimes is useful to be on a "whitelist" and be able to control all aspects of the raw label, for annotation speed improvement based on some specific workflows.

I suggest you to add a checkbox in `settings-label fast` (always on for default RectLabel workflow) but if user removes the check, full control on raw label will be enabled.

**Comment by ryouchinsa** [comment]
Thanks for your feedback.
In the next update, if any objects are not using attributes, '-' character in the label name is not replaced with '_' character.
When the new update is released, we will let you know.

**Comment by mentezar** [comment]
Thanks! 👍🏻

**Comment by ryouchinsa** [comment]
Improved so that if any objects are not using attributes, '-' character in the label name is not replaced with '_' character.

The new update version 2.77 was released.
To show the new update on Mac App Store, press command + R to reload.
