### ISSUE TITLE
Smart Zoom support with Magic Mouse

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#102]
Please support the Magic Mouse as an alternative to use the smart zoom feature.

Double tap with one finger to smart zoom (like already done with double tap with two fingers on trackpad)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
Added smart zoom for double-tap with a finger on Magic Mouse.
System Preferences > Mouse > Point & Click tab > Smart zoom.
https://rectlabel.com/help#magic_mouse

The new update version 2.76 was released.
To show the new update on Mac App Store, press command + R to reload.
