### ISSUE TITLE
Measurement tool

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#105]
It's useful to have a simple measurement tool.

1. Click and hold clicked on point 1, drag and release when on point 2.
2. When dragging, a double arrow line will be drawn.

If you click again a new measurement will be done, restarting from step 1.
If you press ESC, single click (without holding), or click on any other part of the app, the measurement mode/tool will be deactivated.

When dragging, an overlay on top-left part of the image will be written with below information:
`(x1, y1)-(x2, y2) : (W x H) : Npx, D degrees`

- `x1` and `y1` are the starting point of the line
- `x2` and `y2` are the end point of the line (when dragging these updates in realtime)
- `W` and `H` are the width and height of the imaginary rectangle if you consider the measurement line a the diagonal of an imaginary rectangle.
- `N` is the length of the line/measurement with subpixel accuracy
- `D` are degree of line/measurement

Add also an option in settings for specifying the degree range (`0 to 360` or `0 to 180` and `0 to -180`). Always consider degrees increment *clockwise*.

Examples:

- If you draw an horizontal line where `x1 ,y1` are a left point and `x2, y2` are a righter point, this will be 0 degrees.
- If you draw an horizontal line where `x1 ,y1` are a right point and `x2, y2` are a lefter point, this will be 180 degrees. If from this position, you will go up by 1 degree, the resulting degree will be 181 (settings 0-360) or -179 (setting 0,180,-180)

Hope it helps.

**Comment by ryouchinsa** [comment]
For the line length and degrees, is it relevant to training neural network?
If so, how does it influence the output xml format?

**Comment by mentezar** [comment]
above tools/infos in real-time are not relevant for training neural networks, but as of RectLabel is very fast, it should be used to get some basic infos in real-time instead of opening slower and overkill tools like Gimp.
They should be only visual tools, changing nothing in xml files.

**Comment by ryouchinsa** [comment]
We do not think these features are necessary for RectLabel.
As you might know, we are working on iPad version, too.
We want to focus on features which could be used on iPad, too.
Hope you could understand.
