### ISSUE TITLE
Customizable object hotkeys

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#106]
In settings-object, hotkeys are automatically generated. They start from 0 to 9 and then from a to z.

This default behavior is good but it would be perfect if user could edit the key. In this scenario, key conflicts from autogenerated and manual edited should be considered by code/program.

Thanks.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We understand that the hotkeys are important feature of RectLabel.

You can drag & drop to change the order on the objects table.
Is it not enough to customize the 0-9 and a-z hotkey for your use-case?

![objects](https://user-images.githubusercontent.com/1954306/59032220-b1c2f680-88a0-11e9-9a99-8d3e34664bfa.jpg)

**Comment by mentezar** [comment]
Suppose you have only 1 object called "roi" and 1 object called "background_tile".
Actually label keys are automatically assigned: `0` key for `roi` and `1` key for "background_tile".

Suppose I preferred to use `r` key for `roi` and `b` key for `background_tile`. Actually it's not possible. Should fake objects should be created only to reach `b` and `r` keys?

Above example is too simple, but there are many annotation workflows that need (if possibile) more precise customization of hot keys.

Hope I explained well.

**Comment by ryouchinsa** [comment]
> Suppose you have only 1 object called roi and 1 object called background_tile.

In this case, 0 and 1 hotkeys are enough.

We understand the hotkey feature is very important for RectLabel.
Let us have some time to consider this feature would be necessary for our users or not.

**Comment by mentezar** [comment]
Yes, above case is very basic and affordable with 0 and 1.
It's not a necessary feature but it will add more flexibility to RectLabel, imho.
Thanks.

**Comment by ryouchinsa** [comment]
The new update version 2.82 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved so that you can customize objects hotkeys using 0-9 and A-Z keys.

![objects](https://user-images.githubusercontent.com/1954306/60402338-2e5ba300-9bc9-11e9-9363-dea5446c65b4.jpg)
