### ISSUE TITLE
generating camvid like dataset

### ISSUE THREAD

**Issue by roryw10** [ryouchinsa/Rectlabel-support#108]
First off, i would like to say i really like rectlabel. It's a great tool. Im finding the codumentation slightly confusing - it would be great if there where some more demos / guides on youtube as some general feedback. 

For my specific use case i am trying to generate binary masks for imgage segmentation. I have JPG files, which i am using the polygon tool to draw an outline before exporting with masks to PNG. Ideally i need a text file with the "categories" in corresponding to the color of the mask that i have used to segment the object from the background (although i suppose i could technically make this by hand?). 

I have seen a lot of people online struggling with similar issues for image segmentation - mask-RCNN and U-net are popular technologies but there seems to be a lack of tools for developers working with custom datasets. Any help would be greatly appreciated!

Edit: for camvid dataset style see http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamVid/

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

For our document, which part is confusing?
We would improve it.

For Mask-RCNN, check on "Export an image per object" on the settings dialog.
https://rectlabel.com/help#export_mask

Then follow these instructions on our document.
Other users could start training Mask-RCNN with this document.
https://rectlabel.com/help#tf_record

For camvid like dataset, check on "Export an image includes all objects" on the settings dialog.
https://rectlabel.com/help#export_mask

For an index color mask image, all objects and their overlaps are calculated based on the layer order in the label table.
Pixel values are set based on the "id" in the label map. For the background, 0 is set.
The index color table is created from object colors on the settings dialog.
https://rectlabel.com/help#mask_image

The label map file corresponds to the text file with the "categories".
https://rectlabel.com/help#label_map
id 1: car
id 2: plate
id 3: person

In the index color image, there is a color table.
0 => background rgb
1 => car rgb
2 => plate rgb
3 => person rgb
After that, each pixel values are described using 0-3 values.

![mask](https://user-images.githubusercontent.com/1954306/59008276-00529f80-8865-11e9-99db-a31542034335.jpg)

**Comment by roryw10** [comment]
ok so i think i can follow this. So here i exported the settings file and for a binary segmentation class the data i have is:


  |  
-- | --
projects |  
0 |  
oncology |  
objects |  
0 |  
color |  
red | 0
green | 1
blue | 1
aspect_ratio | ""
name | "a label"
attributes | []
hidden | false
attributes | []
primary | true

So in this case, i can generate the categories text by using "a label" and for camvid would that be 0 255 255 or are the values actually 0 1 1? The colour i used is turqouise which leads me to believe that corresponds to 0 255 255. Export all objects gives me back my images with turqouise segmentations so i believe this is correct. 

My Labelmap states 

item {
  id: 1
  name: 'a label'
}

So this looks like it correlates? I think if possible it would be incredible if the documentation could be improved by actually showing how this works in practice by making some simple video examples of the process rather than just writing it out. Rect is very useful if i can get it to do what i want it to and i dont think i am alone here however my background is more statistics and less programming and i believe there are many others like me. 

Happy to DM you with more feedback or skype if it helps?

**Comment by ryouchinsa** [comment]
We would support one by one to export camvid like dataset.

We assume that you are labeling a image.
Could you export a index-color mask image for the image?

![スクリーンショット 2019-06-07 22 58 37](https://user-images.githubusercontent.com/1954306/59109384-e81f7500-8977-11e9-9edc-138db01128a2.png)

**Comment by roryw10** [comment]
![image](https://user-images.githubusercontent.com/5229850/59110491-28aace80-8937-11e9-8dbf-b14d51676944.png)

**Comment by roryw10** [comment]
looks like the data is the same without the other boxes checked?

**Comment by ryouchinsa** [comment]
Your labelmap file is below.

```
item {
id: 1
name: 'a label'
}
```

In the index-color image, there is a color table.
0 => background rgb (0, 0, 0)
1 => "a label" rgb (0, 255, 255)
After that, each pixel values are described using 0 or 1 values.

If you want to change the object color (0, 255, 255) to another color, you can change on the settings dialog.
![objects](https://user-images.githubusercontent.com/1954306/59112163-6cc0c200-897d-11e9-8c44-a9511f886ae0.jpg)

**Comment by roryw10** [comment]
ok thats helpful, i was mainly trying to understand how to find / export the color table rather than change it - i'm guessing thats done from the settings - i.e export current settings?

**Comment by ryouchinsa** [comment]
"Export settings file" from App menu, you can export the objects colors in the settings file.
Each color is described as a float value [0.0, 1.0].
1.0 means 255.

But from the index-color image, you can extract the color table from your python code.
This is an example.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/checkIndexColorPalette.py
```
import PIL.Image
import numpy as np

if __name__ == '__main__':
    image_path = '/Users/ryo/Desktop/test_annotations/mask/tuce-311434-unsplash_all_objects.png';
    try:
        image = PIL.Image.open(image_path, 'r')
        print(image.mode)
        palette = image.getpalette()
        palette = np.array(palette).reshape(-1, 3)
        print(palette)
    except IOError:
        print("IOError", image_path)
```

![tuce-311434-unsplash_all_objects](https://user-images.githubusercontent.com/1954306/59114333-ec509000-8981-11e9-99e0-4f2ec731f5c0.png)

```
item {
  id: 1
  name: 'car'
}

item {
  id: 2
  name: 'plate'
}

item {
  id: 3
  name: 'person'
}
```

```
Output from the code.
[[  0   0   0]
 [  0 255 255]
 [247 109   8]
 [243  44 210]
...
]

```

**Comment by roryw10** [comment]
ok so this runs, what i'm now struggling to comprehend is why the output isnt binary even though i have just used one single color to mask? Or rather im getting a mix of RGB channels however i would of expected the outputs would have been a mix of 0 0 0 and 0 255 255 as expected behaviour?

**Comment by ryouchinsa** [comment]
Basically, palette is a list of 3 * 256 values in form 256 red values, 256 green values and 256 blue values.
https://stackoverflow.com/questions/51702670/tensorflow-deeplab-image-colormap-removal-confusion

You have your own label map so that you can know how many colors are used in the table.
color_num = object_num + 1(background).

What information is missing for your purpose now?

**Comment by roryw10** [comment]
ok i think i have everything here and will try the process hopefully today and report back to you. I would like to say again thank you for the support and the tool. I feel like it would definitely be useful if there where some youtube videos to illustrate the process and i will try to create one to show people the process.

**Comment by ryouchinsa** [comment]
Thanks for your feedback.
If you could show us the video on youtube, it would be very helpful to improve our document.

**Comment by roryw10** [comment]
Hi @ryouchinsa 

Apologies for the delay in communication. I have made progress and wanted to report somethings back to you. 

In terms of the "camvid" style dataset, my problem was that i do not need the labels outputted in the 3 * 255, 255, 255 values. Rather i need masks corresponding to labels (e.g. 1, 2, 3, 5) which are linked to the classes of object i would like to segment in the image (object a, object b, object c....etc). 

From what i can tell, rect label does not support labelling and mask creation in this format. In order to overcome this problem i first created masks using rectlabel, then i imported images into imageJ to convert the PNGs into mask files (i.e. masks labelled in terms of 1, 2, 3 etc....) in TIFF format (so not data was lost during saving which is an issue with image J and PNG). After this i then had to run the image through a custom script which generates masks containing the values from 0 to N, where N is the number of classes -1 in PNG format. 

I hope this workflow makes sense and you can see the issue i had. It would be great to understand if rect can generate images in this format, if not i can put up a youtube video showing the workflow for others?

**Comment by ryouchinsa** [comment]
Hi,

> Rather i need masks corresponding to labels (e.g. 1, 2, 3, 5) which are linked to the classes of object i would like to segment in the image (object a, object b, object c....etc).

When you check on "Export an image includes all objects", you obtain the index-color image.
It has a color table and after that each pixel is described with object index.
0: background
1; object 1
2: object 2
...

When you check on "Export an image per object", you obtain the 0 or 255 gray scale per object mask image.

What information is missing for your use-case?

**Comment by roryw10** [comment]
ok so ive tried checking "Export an image includes all objects" but i still get 0 through to 255 as the values. I understand that corresponds to the object index but what i was hoping for is that each pixel would be described as 0, 1, 2, as in background, object 1, object 2 (if this makes sense).

**Comment by ryouchinsa** [comment]
We do not think so.

Did you search how to read an indexed color image in python by yourself?
It is a very common image data format.
https://stackoverflow.com/questions/33022983/read-in-an-indexed-color-image-in-python

```
from PIL import Image
import numpy as np
im = Image.open("image.png") # Replace with your image name here
indexed = np.array(im) # Convert to NumPy array to easier access

```

**Comment by roryw10** [comment]
Yes, so that is the custom script i have wrote which i mentioned here:

"In order to overcome this problem i first created masks using rectlabel, then i imported images into imageJ to convert the PNGs into mask files (i.e. masks labelled in terms of 1, 2, 3 etc....) in TIFF format (so not data was lost during saving which is an issue with image J and PNG). After this i then had to run the image through a custom script which generates masks containing the values from 0 to N, where N is the number of classes -1 in PNG format."

I was hoping i could skip this step using rect

**Comment by ryouchinsa** [comment]
> what i was hoping for is that each pixel would be described as 0, 1, 2, as in background, object 1, object 2 (if this makes sense).

Again, this is being realized by this very simple script.
Please print(indexed) to understand.

```
from PIL import Image
import numpy as np
im = Image.open("image.png") # Replace with your image name here
indexed = np.array(im) # Convert to NumPy array to easier access
```
