### ISSUE TITLE
Support for the new CreateML app?

### ISSUE THREAD

**Issue by Peewee1963** [ryouchinsa/Rectlabel-support#109]
Apple presented the new CreateML app on WWDC 2019. Will you support labeling images for it?

**Comment by ryouchinsa** [comment]
We are supporting to export your annotations data in the CSV format for Turi Create object detection system.
https://rectlabel.com/help#xml_to_csv_turicreate

Did they add or change some new training data format?
https://developer.apple.com/videos/play/wwdc2019/424/

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
