### ISSUE TITLE
Image glitch

### ISSUE THREAD

**Issue by kro817** [ryouchinsa/Rectlabel-support#110]
I just updated to the newest version of Rectlabel and now the images are difficult to zoom and then move around within the app for Mac. It's not a smooth zoom/grab like it was before this update. Takes much longer to navigate my images and get close up now because of this.

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.
1. The version is 2.78, correct?
2. How large is the image size?
3. Could you show us the video what is going on in your environment?
https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
