### ISSUE TITLE
minor-aesthetic: double arrow mouse point orientation on edit-points

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#112]
All edit points show the horizontal double arrow.
Corner points should display appropriate diagonal double arrow mouse pointer.
Mid points should display appropriate horizontal or vertical double arrow mouse pointer.

It's only an aesthetic "bug".

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Looking at Adobe Illustrator, as you said, they consider the editing direction to show the edit icon.
At this moment, editable or not is important for us.
When we could understand the feature is necessary for RectLabel, we would implement.
