### ISSUE TITLE
Option to change color of vertical and horizontal guide lines along pointer

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#113]
Vertical and horizontal guide lines along mouse pointer are very useful but sometimes, with some image background, these lines are not very visibile/contraster.

Please add an option in settings (draw tab) to be able to choose a color.

Thanks!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
For the grid color, the default color is being used.
To change the default color, deselect all boxes and change the color from main window.
There is a color panel at the top-right corner of the image.
