### ISSUE TITLE
Export to CSV - Annotations column more than one cell

### ISSUE THREAD

**Issue by haroutisonfire** [ryouchinsa/Rectlabel-support#116]
The exported CSV file is incorrect. The annotations column is supposed to have only one column of data. Within this column, the format of the text must be valid JSON style. Right now it is export this for an example: 

[{"label":"item1"type:"rectangle"coordinates:{"x":444y:451width:254height:258}}]
--

This is supposed to export as follows:

[{"label":"item1", "type":"rectangle", "coordinates":{"x":444, "y":451, "width":254, "height": 258}}]
--

You are missing quotations as well as commas between the objects.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We cannot reproduce the problem.
This is a CSV file exported in our environment.

```
path,annotations
/Users/ryo/Desktop/test_annotations/test_data_csv/2.jpg,[{"label":"bare feet","type":"rectangle","coordinates":{"x":64,"y":875,"width":129,"height":170}}]
```
Could you tell us the version of both RectLabel and macOS?

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
