### ISSUE TITLE
labeling pixels with existing boxes

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#118]
I've annotated with bbox some images.
Now I want to also label pixels. I click `Edit`, `Label pixels` and the brush popup appears.
The problem is that the pointer remains the classic arrow and does not turn in the circle of brush tool. There is not way to draw.

The workaround is to quit RectLabel and start it again. Now the program starts with the "focus" on my annotated "object" (right panel) and the brush tool works.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In our environment, it works.
Edit => Label pixels => Label dialog appears => press OK => Pixels dialog appears and mouse cursor becomes the circle.

Could you show us how to reproduce the problem?

**Comment by mentezar** [comment]
Did you start to label pixels to a new image with no kind of labels?

My case is when, in an *already annotated image with bboxes*, I want to add some pixel annotations.

Let me know.

**Comment by ryouchinsa** [comment]
In our environment, for both unlabeled image and some boxes labeled image, when the pixels dialog appears, the mouse cursor changes.

> The problem is that the pointer remains the classic arrow and does not turn in the circle of brush tool. 

1. What happens when you drag on the image?
2. What happens when you click the Superpixel tab?

Could you show us the video what happens in your environment?
https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac

**Comment by ryouchinsa** [comment]
> My case is when, in an already annotated image with bboxes, I want to add some pixel annotations.

Could you show us the screenshot just after you "Label pixels"?
We want to know which label is selected on the label table and crosshairs for creating boxes are being shown or not.

**Comment by mentezar** [comment]
Sorry for the delay. I'll try to send you a video next week

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
