### ISSUE TITLE
Performance Issues When Zooming Large Images

### ISSUE THREAD

**Issue by dilpreetsingh** [ryouchinsa/Rectlabel-support#123]
Hey,

I'm running into performance issues when labelling really large images. I'm dealing with images in the ~ 6500 by 4200 range. I know this is a very outlier use case, most people deal with images significantly smaller than this. But when i trigger the zoom gesture with my trackpad, the app will beachball for a second (sometimes 3-4 seconds) before zooming in. Dragging the image around is also a bit sluggish at times. Any possibility to improve the performance in this regard would be much appreciated!

Couple of notes:
- I have a fairly high end 2018 MacBook Pro, so it's not really a slow computer issue
- These large images aren't used directly for training, but we have a unique case where we need to preserve resolution as the details on the objects are important. And instead of resizing images when training, we actually create multiple crops from a single image - so it's much more efficient to label on a full resolution image instead of 8 cropped ones.

Thanks!

_edit: actually counted number of seconds it beachballs for and updated the number :)_

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Zooming with trackpad requests 5 - 10 zoom actions to RectLabel to make it smooth.
For large images, it does cost for computers.

It might be able to batch those 5 - 10 zoom actions into 1 action to reduce the calculation.

Does the beachball happen when you change to "Zoom in" mode and make a click on the image?

**Comment by dilpreetsingh** [comment]
It's a bit more consistent experience if use the "Zoom in"/"Zoom out" modes but they do beachball at some points. The weird thing is that the beachball isn't random - it seems to occur only at certain zoom levels. I've attached a video showing this off: https://www.dropbox.com/s/m2b4uxu6b8gvhbx/zooming-rectlabel.mov?dl=0
The QuickTime screen recording doesn't show the beachball for some reason, but it occurs at at these timestamps (basically whenever you see prolonged periods of nothing happening after the click):
0:08 to 0:15 seconds
0:33 to 0:43 seconds
0:55 to 1:04 seconds
1:11 to 1:22 seconds

Some things i've noticed:
- Zooming is so much faster when the zoom levels are extreme, so either very zoomed in and very zoomed out.
- It's the most sluggish around the 100 to 150% levels I feel.

**Comment by ryouchinsa** [comment]
Thanks for the video.
We have some 4000px x 6000px images but they do not show the beachball when zoom.
Could you give us an image which shows the beachball in your environment?
We want to reproduce the problem.

**Comment by dilpreetsingh** [comment]
Here is the image: https://www.dropbox.com/s/v4cvxposzbvdqv9/im.jpg?dl=0

Few experiments I performed to narrow things down potentially:
- Connecting my MacBook Pro to power doesn't change anything
- Turning off "Automatic graphics switching" so mac always uses the dedicated GPU doesn't make a difference 
- Slow doesn't happen when i'm using an external monitor, seems much more performant, not exactly sure why (monitor is 34" with a resolution of 3440x1440)
- Changing macbook's resolution doesn't seem to make a difference (I use the "More Space" scaling option)

**Comment by ryouchinsa** [comment]
Thanks for the image and the details.

We are comparing with Photoshop's zooming.
They are smooth.

Let us have some time.
We would need some essential improvements.

**Comment by ryouchinsa** [comment]
Added "Use fast zoom for large images" on the Label fast tab on the settings dialog.
https://rectlabel.com/help#label_fast

You can use our new image view to make zooming fast for large images.
If this new image view would be useful for every use-case, we would make it as default.

The new update version 2.85 was released.
To show the new update on Mac App Store, press command + R to reload.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by dilpreetsingh** [comment]
Works beautifully! Thanks!
