### ISSUE TITLE
Support Create ML

### ISSUE THREAD

**Issue by Peewee1963** [ryouchinsa/Rectlabel-support#124]
With Create ML, XCode developer beta 3, it seems that annotations are only supported as JSON files - trying to import a CSV brings an error. Please enhance your application.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We would support the JSON format for Create ML.

When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
Hi,

The new update version 2.84 was released.
To show the new update on Mac App Store, press command + R to reload.

- Added "Export XML files to JSON file for Create ML" in Export menu.
https://rectlabel.com/help#xml_to_json

Please give us your feedback.

Best regards,
Ryo
