### ISSUE TITLE
Annotion boxes are too big

### ISSUE THREAD

**Issue by Peewee1963** [ryouchinsa/Rectlabel-support#128]
Images annotated with earlier versions now seem to have bigger boxes with the actual version.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you show us the screenshot, image, and xml file?
We have to know the details.

**Comment by Peewee1963** [comment]
Heloo,
I had to send the image/xml as ZIP, because the Email was too big. In both cases, the rectangles had a tight fit to the coins and now have a larger rectangle, mostly to the right.

Kind regards, Peter

**Comment by ryouchinsa** [comment]
If you could not send to support@rectlabel.com, could you provide an access to the file on dropbox?
Some users are providing their data through dropbox.

> now have a larger rectangle, mostly to the right.

Could you make sure that the actual image size and the image size in the xml file are the same?

**Comment by Peewee1963** [comment]
I have sent this as zip files, now you should have got them. The issue seems to regard only some of the images - I will try to find one where all the rectangles are magnified.

**Comment by ryouchinsa** [comment]
Thank you for sending. 
But we have not received the e-mail yet.

**Comment by Peewee1963** [comment]
Hello,I have written the annotations over some weeks -now ~2400. It seems to me, that only one version of RectLabel had this problem, I suspect when enlarging the image. Later annotaions seem to be correct.
Kind regards,Peter


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Di, 16. Jul. 2019 7:02
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)

Thank you for sending.
But we have not received the e-mail yet.—

**Comment by Peewee1963** [comment]
Did you get the files?

It seems that about a half of my data is affected.

**Comment by ryouchinsa** [comment]
No, not yet.

Could you send the zip file to support@rectlabel.com again?
Or could you send a test mail to support@rectlabel.com?

**Comment by ryouchinsa** [comment]
> I suspect when enlarging the image

Did you resize the image after you labeled on RectLabel?
We need to know the details to reproduce the problem.

**Comment by Peewee1963** [comment]
I resized only the view in RectLabel using two fingers on my MacBookPro, saved the annotation and went further. 


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Mi, 17. Jul. 2019 10:49
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)


I suspect when enlarging the image
Did you resize the image after you labeled on RectLabel?
We need to know the details to reproduce the problem.—

**Comment by ryouchinsa** [comment]
Thanks for the data.
We could receive the data.

We checked those 3 images and annotations.
As you said, for some coins, boxes are not fitted.

For comparison, we opened each image with Photoshop and checked each box coordinate in the xml file is the same as the coordinate shown on Photoshop.

Currently RectLabel is showing boxes correctly compared with those positions shown on Photoshop.

Do you remember the previous version you labeled those coins?

**Comment by Peewee1963** [comment]
No, but look into the EXIF data - I have updated the version always when it was offered in the App Store.


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Mi, 17. Jul. 2019 12:57
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)

Thanks for the data.
We could receive the data.We checked those 3 images and annotations.
As you said, for some coins, boxes are not fitted.For comparison, we opened each image with Photoshop and checked each box coordinate in the xml file is the same as the coordinate shown on Photoshop.Currently RectLabel is showing boxes correctly compared with those positions shown on Photoshop.Do you remember the previous version you labeled those coins?—

**Comment by ryouchinsa** [comment]
> but look into the EXIF data
> It seems that about a half of my data is affected.

Could you check from which date to which date this problem was happening for all xml files in your environment?

**Comment by Peewee1963** [comment]
I will try...


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Mi, 17. Jul. 2019 16:40
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)


but look into the EXIF data
It seems that about a half of my data is affected.
Could you check from which date to which date this problem was happening for all xml files in your environment?—

**Comment by Peewee1963** [comment]
Hello,the dates of the images I have ssent to you are from mid of June - I don't think that there are to much newer versions of RectLabel. Did you try to label one with the mid June version and to open it with the actual version? Please keep in mind to enlarge the image in full screen mode with two finger gestures an the MBP.
Kind regards,Peter 


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Mi, 17. Jul. 2019 16:40
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)


but look into the EXIF data
It seems that about a half of my data is affected.
Could you check from which date to which date this problem was happening for all xml files in your environment?—

**Comment by ryouchinsa** [comment]
For the mid of June, the version is 2.78.
https://www.macupdate.com/app/mac/59522/rectlabel/version-history

We labeled the coin image using trackpad zoom in full screen mode and opened with the latest version.
The boxes are fitted.

Could you give us more detailed information to reproduce the problem?

**Comment by Peewee1963** [comment]
I try tofind the date where the problem ended - as far I know it shoould be on of the July versions. I am a proferssional software developer, machine learning si my hobby so I hope to tell you after the weekend where the problem started. Up ti  now I have to check an partially reannonate ~2300 images.....


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Do, 18. Jul. 2019 18:55
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)

For the mid of June, the version is 2.78.
https://www.macupdate.com/app/mac/59522/rectlabel/version-historyWe labeled the coin image using trackpad zoom in full screen mode and opened with the latest version.
The boxes are fitted.Could you give us more detailed information to reproduce the problem?—

**Comment by ryouchinsa** [comment]
By the way, you told us that "Annotion boxes are too big".
But in our environment, your coin boxes are not too big.
Just slightly not fitted.
Can we send you the screenshot how it is shown in our environment?
On this page or to your e-mail address.

**Comment by Peewee1963** [comment]
Just another example:

**Comment by Peewee1963** [comment]
Just another:

**Comment by ryouchinsa** [comment]
Could you drag & drop those example images on your comment?
We cannot see any images.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by Peewee1963** [comment]
Hello,I had to correct a lot of annotations, but now it is working correctly.
Kind regards,Peter


-----Ursprüngliche Mitteilung-----
Von: Ryo Kawamura <notifications@github.com>
An: ryouchinsa/Rectlabel-support <Rectlabel-support@noreply.github.com>
Cc: Peewee1963 <ochmannp@aol.com>; Author <author@noreply.github.com>
Verschickt: Mo, 26. Aug. 2019 11:07
Betreff: Re: [ryouchinsa/Rectlabel-support] Annotion boxes are too big (#128)

Currently If you need our support to fix this problem, please let us know.—
