### ISSUE TITLE
Tag overlay?

### ISSUE THREAD

**Issue by Gl3nninator** [ryouchinsa/Rectlabel-support#129]
I use rectlabel for images with little variation, so I constantly need a tag in the same position as the previous image- any chance you could add an optional setting to overlay tags from the previous image and make it easy to edit the size or a slight change in position? and also make shortcut options available for it?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can use "Load labels from prev image" in Edit menu.
https://rectlabel.com/help#load_labels

Or you can copy & paste selected labels from another image.
https://rectlabel.com/help#copy_box.
