### ISSUE TITLE
Next Image

### ISSUE THREAD

**Issue by matmoody** [ryouchinsa/Rectlabel-support#13]
I'm sure I'm overlooking something simple, but when I move to the next image in the directory the bounding box from the previous image already appears. Then in the XML, 'filename' is that of the next image, not the original.

Not sure how to save the bounding box for an image, then move to the next image, creating the next xml file in the process.

**Comment by ryouchinsa** [comment]
Thanks for reporting the problem.

We want to reproduce the problem in our environment.
Could you reproduce the problem with the image folder below?
https://github.com/ryouchinsa/Rectlabel-support/tree/master/images_test

Let us ask you some questions.
- The absolute path of the folder
- Image names list in the folder
- After creating a box in the image, does the confirm dialog appear when you move to the next image without pressing the save button?
- Could you show us the xml files of both the previous image and the next image?
- Does it happen every time in the same folder and at the same image?
- If you could, could you give us a test folder with a few images which you can reproduce the problem in your environment?

![1](https://user-images.githubusercontent.com/1954306/29002469-1b514afc-7ade-11e7-96f2-411096fa0000.png)

**Comment by matmoody** [comment]
Ok, your dataset works correctly. 

My images were labeled: 
car1.jpg, car.2.jpg, car.3.jpg, car.4.jpg

When I re-label without "car..." then everything works correctly. 

Thank you!

**Comment by ryouchinsa** [comment]
Thanks for clarifying the problem.

We could reproduce the problem and fix it.
Our string operation to the file name with dots was wrong.

We will submit the new update soon.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update was released.

RectLabel 1.33
Bug fix when saving labels for the image file name with dots
https://github.com/ryouchinsa/Rectlabel-support/issues/13

Added short cut key "delete" to delete the box
Added short cut key "command + D" to duplicate the box
Show which mode you are in by the button color
https://github.com/ryouchinsa/Rectlabel-support/issues/12

Added "Export Settings File" and "Import Settings File" to "File" menu
https://github.com/ryouchinsa/Rectlabel-support/issues/11

Added "Set Image Index to Load Labels" to "File" menu by which you can copy labels to other images
https://github.com/ryouchinsa/Rectlabel-support/issues/9
