### ISSUE TITLE
Memory leak with pixel brush using large images

### ISSUE THREAD

**Issue by aandersonbst** [ryouchinsa/Rectlabel-support#130]
Hello, 

I've been using rectlabel to generate mask images using mostly the pixel brush tool. The images I'm working with are 24MP, and I've noticed what seems to be a severe memory leak. I load a set of maybe 5-10 images at a time in a project with ~10 object types. I've found that if I work on images for maybe 10-15 minutes I'll inevitably hit a system out of memory error and have to restart. I've even watched the memory utilization while I'm erasing and drawing on the image and the memory accumulates very quickly (10's - 100's MB/stroke). 

To fix this, I just restart rectlabel periodically, but is there a setting I can adjust to help prevent this? 

Thanks!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We could find and fix the memory leak when you use the brush tool.

When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 2.88 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved the zoom speed and mouse over speed for pixels tools.
- Fixed the memory leak problem when you use the brush tool.
- Added the brush size max on the settings dialog.
- Added the brush size history on the pixels dialog.
- Added the Flood Fill onto the right-click menu on the pixels.

**Comment by aandersonbst** [comment]
Awesome, thanks so much I'll try out the new version!
