### ISSUE TITLE
New pixel brush features 

### ISSUE THREAD

**Issue by aandersonbst** [ryouchinsa/Rectlabel-support#131]
Hello, 

I use rectlabel on large images primarily with the pixel brush tool and the current feature set works pretty well. However, I was wondering about the possibility of adding the following features (or do these features already exist?):

1. Increase the maximum pixel size of the brush from 200 to maybe 1000? Especially helpful for big images

2. Change brush shape from circle to square or diamond? Would be helpful when annotating images with lots of right angles and straight edges 

3. Clear all pixels for an object type, like a start over button (maybe already a way to do this?) 

4. Similarly, fill all pixels for an object type (especially helpful when leveraging the hierarchy and adding a background annotation)

Thanks!

**Comment by ryouchinsa** [comment]
Thanks for writing those feature requests.

1. You can change the Brush size max. https://rectlabel.com/help#draw
2. Do you know some image annotation tools which implement those square and diamond brush tools?
3. Delete the label on the label table.
4. You can use Flood fill on the right-click menu. https://rectlabel.com/help#label_pixels
https://twitter.com/rectlabel/status/1158916690979147777

**Comment by aandersonbst** [comment]
Awesome I'll try those out! I do not know of another annotation tool that uses square or diamond brush, I just found myself trying to annotate around right angles and corners and thought it'd be nice to have a brush with sharper edges.

**Comment by ryouchinsa** [comment]
Could you show us the image which you want to use the square or diamond brush?
We have to know the details to improve our brush tool.

**Comment by aandersonbst** [comment]
Sorry for the delay, I got the updates in place and the memory leak, flood fill, and pixel brush re-size features are working great! So regarding the square or diamond brush I've attached two screen grabs showing the issue I've been having. Effectively it helps having a bigger brush to annotate large regions at once:
![Screen Shot 2019-08-13 at 9 38 06 AM](https://user-images.githubusercontent.com/53535955/62956143-9b10b280-bdaf-11e9-85e5-5ee044dddb92.png)
But as I work with a lot of right angles I would then have to select a smaller brush to fill in the details around the edge:
![Screen Shot 2019-08-13 at 9 39 43 AM](https://user-images.githubusercontent.com/53535955/62956176-b11e7300-bdaf-11e9-9d08-6cf671b564a0.png)
I actually think the fill tool helps a lot with these cases. Alternatively, maybe the polygon tool would be better for these cases? I haven't explored the polygon tool much yet. 

Thanks so much for the help!

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

We Added polygon brush tool on the pixels dialog.
You can use the polygon tool to label pixels.

The new update version 2.92 was released.
To show the new update on Mac App Store, press command + R to reload.

![polygon_brush](https://user-images.githubusercontent.com/1954306/63995760-9a5c7800-cb34-11e9-8c6f-aea90c1bab93.gif)

**Comment by aandersonbst** [comment]
That's perfect, thanks so much for the help!
