### ISSUE TITLE
hide other boxes when drawing

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#132]
It would be useful to have a feature enabled with hotkey modifier (like shift for square boxes)or via settings, to temporarily hide all other boxes when:
- we are drawing a new box
- we are resizing an existing box
And when we release the mouse, all other boxes will appear again.

This because when we have multiple boxer very near each other, drawing new one or editing, is very difficult.

**Comment by ryouchinsa** [comment]
You can use "Hide other boxes" with command + B when you draw.
https://rectlabel.com/help#hotkeys
