### ISSUE TITLE
checkebox to enable/disable objects

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#133]
Sometimes is useful to limit the annotator to be able to choose only a subset of objects, for avoiding making mistakes (it unfortunately happens) and causes issue when training.

So it would be useful to have in Setting, Object, a checkbox (above the `hidden` checkbox) called `Enabled`.

So, if I disabled for example the object/hot_key `3` and when annotating I try to press the `3` key, a popup should be shown to inform about the error "Object label 3 is disabled".

This will help a lot to reduce errors.

Thanks.

**Comment by ryouchinsa** [comment]
You can disable all objects hotkeys with "Use 0-9 and a-z hotkeys".
https://rectlabel.com/help#label_fast

Or you can enable or disable each object hotkey on the Objects tab.
Clicking x button disables the object hotkey.
https://rectlabel.com/help#objects
