### ISSUE TITLE
hide guide-lines lines when drawing

### ISSUE THREAD

**Issue by mentezar** [ryouchinsa/Rectlabel-support#134]
Horizontal and vertical guide lines are very important and useful.

But I noticed that when I have a lot of nearby annotations, already with different colors, guide lines area some kind annoying/confusing.

It would be useful to have an option in Settings to allow the following behaviour:
guide lines area always shown but when I'm holding the mouse button for drawing, guide lines temporarily disappear and will reappear when I release the mouse button (so when I finisced drawing.

For a general improvement of visibility and attention when drawing, this issue can be seen related to issue #132 

Thanks.

**Comment by ryouchinsa** [comment]
You can use "Hide cross hairs" with control + G.
https://rectlabel.com/help#hotkeys
