### ISSUE TITLE
Count of images when converting video

### ISSUE THREAD

**Issue by foxmlder** [ryouchinsa/Rectlabel-support#135]
Hi,

I converted a video yesterday of 3000 frames and the order is alphabetically.
The problem is that we've got the following order: frame 1, 10, 100, 1000, 1001, 1002 til 1009, then 101, 1010 ...
You should change the way to put a number on the frame converted from a video and put 0 before lower numbers, so frame 0001, 0002 ..... il will be better to work
Best Regards

Fabien 
(France)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
You can use "Numeric" for Sort images.
Does this work for you?

**Comment by foxmlder** [comment]
Thanks, this is working fine!

Sorry to have open an issue for this

Le ven. 9 août 2019 à 05:57, Ryo Kawamura <notifications@github.com> a
écrit :
