### ISSUE TITLE
Minor: Use default arrow key navigation when opening image/annotation folder

### ISSUE THREAD

**Issue by dilpreetsingh** [ryouchinsa/Rectlabel-support#139]
Hey

This is more a minor annoyance, but when choosing an image folder, the "left" and "right" arrow can't be used for folder navigation (they are overridden by the app for image navigation). The "up" and "down" arrows work fine. Would be super convenient if when the dialog box is open, all the arrow keys could be used for folder navigation.

Thanks

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

The new update version 2.93 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved so that you can use right and left arrow key when you are opening folder.
