### ISSUE TITLE
Add a way to define custom hotkeys.

### ISSUE THREAD

**Issue by xvolks** [ryouchinsa/Rectlabel-support#14]
As I use RectLabel in a multi language environment, the default hotkeys are not always suitable for production use.
For example command + 0 (zero) to Zoom Fit needs two hands on a French keyboard, and going from mouse to keyboard and back is not very handy. If one can use his own hotkeys this would solve the problem.

I have personally implemented [MASShortcut](https://github.com/shpakovski/MASShortcut) in my own application with success.

**Comment by ryouchinsa** [comment]
"Command + 0" is used in Photoshop so that we thought it would be comfortable for our users.

It's like an "Edit keyboard shortcuts" in Photoshop.

![2014_05_04mask2](https://user-images.githubusercontent.com/1954306/29092175-5a150fe2-7cc0-11e7-93ff-14557424e81a.jpg)

Thanks for letting us know about MASShortcut.
We would try to implement the feature in RectLabel.

**Comment by ryouchinsa** [comment]
![1](https://user-images.githubusercontent.com/1954306/29387553-7b3ef032-831b-11e7-9d01-ee88d5bab927.png)
![2](https://user-images.githubusercontent.com/1954306/29387556-7d2dd41c-831b-11e7-9508-87cc4c241f85.png)

Added "Hotkeys" on the settings dialog to customize keyboard shortcuts.
Fixed the error message did not show when opening a folder which did not include images.

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
RectLabel 1.38 was released.

**Comment by joaquinperaza** [comment]
What about closing this issue?

**Comment by cpagravel** [comment]
I'm using version 1.43 and don't see the menu for adding hotkeys. What happened to this?

**Comment by ryouchinsa** [comment]
MASShortcut https://github.com/shpakovski/MASShortcut was unstable on OS X High Sierra so that temporarily we removed the feature.
Do you need to define custom hotkeys?

**Comment by cpagravel** [comment]
@ryouchinsa Yes, I would like to define custom hotkeys. I have a lot of annotating to do.

**Comment by ryouchinsa** [comment]
We would find some alternative to MASShortcut or code by ourselves.

**Comment by xvolks** [comment]
What about cloning -> fixing -> PR  the issue ?

**Comment by ryouchinsa** [comment]
When we updated to the OS X High Sierra, MASShortcut was unstable when we cleared each hotkey.
It often cleared other hotkeys at the same time.
But now we checked again, and it looks working.
We are sorry for your inconvenience.

We restored the custom hotkeys feature on RectLabel 1.46.

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

![settings_store_hotkeys](https://user-images.githubusercontent.com/1954306/31858390-647aa248-b731-11e7-8b49-f55d888355c8.jpg)

**Comment by ryouchinsa** [comment]
RectLabel 1.46 was released.

**Comment by cpagravel** [comment]
This is great! Thank you. It's a very handy tool.

**Comment by cpagravel** [comment]
This is not working for me. When trying to enter in a hotkey, my input does not get picked up by RectLabel. Am I doing something wrong?

**Comment by joaquinperaza** [comment]
Hi @cpagravel which key combination are you trying to use? it's working for me, however, only accept key combination with ctrl or cmd plus other keys.

**Comment by ryouchinsa** [comment]
MASShortcut allows any hotkey containing Control or Command modifier.
https://github.com/shpakovski/MASShortcut/blob/master/Framework/MASShortcutValidator.m

It might be possible to customize to source code.

**Comment by cpagravel** [comment]
Ah, yes. It works if I use a modifier. Cheers!
