### ISSUE TITLE
update filename in XML

### ISSUE THREAD

**Issue by lamontagne1982** [ryouchinsa/Rectlabel-support#140]
I have annotated >1000 images and don't want to start over.  YOLO doesn't accept a filename with hyphens so I needed to batch rename the images.  i renamed the images, but now I need to update all the mismatched filenames within the XML file which were already created. so currently the lines in the XML says: 

This is the current format:
<filename>15-08-2019_21.17.39.jpg</filename> 

I want to change any hyphen on that line to an underscore.  Can you provide me with some code to execute that on a mac?  Or is there something built in to Rectlabel?  

This is the format I want:
<filename>15_08_2019_21.17.39.jpg</filename>

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you want to just overwrite the xml content with the new file name, you can use "Resize all images and annotations" in Export menu.

Just let the "Image size max" to be empty.
https://rectlabel.com/help#resize_image

**Comment by lamontagne1982** [comment]
Thank you!

Dan
________________________________
