### ISSUE TITLE
Buy Extra Features

### ISSUE THREAD

**Issue by ryouchinsa** [ryouchinsa/Rectlabel-support#141]
We are preserving features which you bought.
https://github.com/ryouchinsa/Rectlabel-support/issues/64

We added "Copy & Paste Features", "Core ML Features", and "0-9 and A-Z Hotkeys Features" to the purchase dialog.
If you bought Full App before adding these features, these features were added after you bought Full App. 
If you need, please buy them. 

Copy & Paste Features were released at v2.55.
Core ML Features were released at v2.59.
0-9 and A-Z Hotkeys Features were released at v2.62.

- Users who bought Full App before v2.55
We are asking you to pay for "Copy & Paste Features", "Core ML Features", and "0-9 and A-Z Hotkeys Features".

- Users who bought Full App before v2.59
We are asking you to pay for "Core ML Features" and "0-9 and A-Z Hotkeys Features".

- Users who bought Full App before v2.62
We are asking you to pay for "0-9 and A-Z Hotkeys Features".

- Users who bought Full App after v2.62
You can use all features without extra payments.

![purchase_extra](https://user-images.githubusercontent.com/1954306/64526182-99e68d00-d33d-11e9-8a2a-dbbf42177383.jpg)

**Comment by ryouchinsa** [comment]
Undo and Redo Features were released at v2.97.

To unlock features added after you bought, please subscribe to monthly or yearly plan.

![purchase_extra](https://user-images.githubusercontent.com/1954306/66894156-acce3a80-f02a-11e9-95aa-53b156f12d9e.jpg)

**Comment by pietz** [comment]
I cannot keep up with how often you change prices, sell addons or switch to different business models altogether. I understand that it's hard to nail the pricing of an app but following RectLabel it has been nothing but a roller coaster ride. As a customer I'm confused, I'm annoyed, I'm sick of it and quite frankly I'm not willing to do it anymore.

If you're interested in my advice, you need to start being a lot more accommodating with your customers. Give them some things for free and don't start charging them extra for every new feature. Double the price if you must but give at least 12 months of updates. With the new subscription model you might have found a good solution but personally I don't like subscriptions for desktop software. Plus, it's the 100th change you put upon us, so I'm out.

All the best for your future and the future of RectLabel.

**Comment by shiquanwang** [comment]
This is not helping me.
I paid for the app at early stage. Not subscription fee for any selected features, but just a normal one-time fee for an app.
Don't know when it changed to in-app purchase and subscription fee mode.
Currently I cannot export labeled rectangles which are the basic features from the very beginning.

**Comment by ryouchinsa** [comment]
@shiquanwang, 
We are preserving features which you bought.
If you bought RectLabel before the version 1.97 which implemented the in-app purchase for Full App, pixels features and export features were added after you bought.
If you need, please subscribe.
https://github.com/ryouchinsa/Rectlabel-support/issues/64

**Comment by shiquanwang** [comment]
@ryouchinsa 
I searched my gmail and found I paid for RectLabel on 2018-04-23.

Now I see this opening RectLabel
<img width="612" alt="Screen Shot 2019-11-14 at 18 58 43" src="https://user-images.githubusercontent.com/732862/68851755-7101c000-0711-11ea-947f-1d580d51e444.png">

After clicking restore purchases and input apple id and password
<img width="448" alt="Screen Shot 2019-11-14 at 18 59 10" src="https://user-images.githubusercontent.com/732862/68851830-98588d00-0711-11ea-84d2-9d1ab982b9d3.png">

I tried label a random rect, and could not export in any format (txt, CSV for JSON), all export options are grey
<img width="1092" alt="Screen Shot 2019-11-14 at 19 11 42" src="https://user-images.githubusercontent.com/732862/68852381-b4a8f980-0712-11ea-9a04-4dca14be172d.png">

Did I do anything wrong to use?

I remember to annotate rects in image and export them in txt is the basic feature when I paid for the app.
Do I need to subscribe to use them now?

And below is the email from Apple
<img width="945" alt="Screen Shot 2019-11-14 at 19 08 03" src="https://user-images.githubusercontent.com/732862/68852211-685db980-0712-11ea-8076-c119a94e27de.png">

**Comment by ryouchinsa** [comment]
@shiquanwang,
Thanks for the details.
You mean you bought Full App in our in-app purchase after the version 1.97.

Could you send us your app purchase receipt in your RectLabel app?
/Applications/RectLabel.app/Contents/_MASReceipt/receipt

We would investigate the situation.

**Comment by shiquanwang** [comment]
Sure.
What's your email address?
To make it clear, I have reinstalled MacOS on the machine (full reinstall) during the period.

**Comment by ryouchinsa** [comment]
@shiquanwang 

Send an email to support@rectlabel.com
Thank you.

**Comment by shiquanwang** [comment]
@ryouchinsa 
sent, thanks.

**Comment by ryouchinsa** [comment]
@shiquanwang,
We checked your receipt and sent an e-mail to you.

For existing users who have not paid for Full App, export features were added after you bought.
If you want to use them, please subscribe.

If you want to use only "Export XML files to CSV file", we would make it open to existing users.
Because there was the old version "Convert XML files in the folder to a CSV file" in the old version.

**Comment by ryouchinsa** [comment]
Made "Export XML files to CSV file" open to existing users who bought RectLabel before the version 1.97.

The new update version 2.99.7 was released.
To show the new update on Mac App Store, press command + R to reload.

**Comment by shiquanwang** [comment]
@ryouchinsa Nice, thanks.

**Comment by maxcrous** [comment]
I agree with pietz. 
The continuous changes in your pricing policy is not transparent and unfair to customers. 
I paid a certain amount for your software, expecting to be able to actually **use it**.
There were no disclaimers stating that I could loose features .
Certain features I used on a daily basis (copy/paste shapes) have been put behind a pay wall.
Why would purchasing the software at a later date have allow me access to these features without further payment?
This makes no sense. 
Like pietz I will no longer be using or recommending Rectlabel. 
Adios

**Comment by ryouchinsa** [comment]
@maxcrous, 
To be fair, we are preserving features which you bought.
If you bought Full App before v2.55, Copy & Paste Features were added after you bought.
If you want to use them, please subscribe.

Could you send us your app purchase receipt in your RectLabel app to support@rectlabel.com?
/Applications/RectLabel.app/Contents/_MASReceipt/receipt

We would show you the version and date when you bought Full App.

**Comment by ryouchinsa** [comment]
@pietz 
We appreciate your feedback.
In the latest version 3.00.3, except the copy/paste and undo/redo features, all features are open now.

![purchase_subscribe](https://user-images.githubusercontent.com/1954306/73589324-1dd12980-4518-11ea-9fcf-f5fb27df63dc.jpg)

Also, we added "Open from AWS S3" on File menu.
For the AWS S3 bucket settings, please read our document.
https://rectlabel.com/help#open_folder_s3

![aws_s3](https://user-images.githubusercontent.com/1954306/73589369-e020d080-4518-11ea-8ff1-42bb4b8596e1.jpg)

For the team which has multiple users, Apple provides Apple Business Manager and Apple School Manager for volume licenses.

Apple Business Manager
https://support.apple.com/guide/apple-business-manager/welcome/web

Apple School Manager
https://support.apple.com/guide/apple-school-manager/welcome/web

We released another app "RectLabel - One-time payment" for "Apple Business Manager" and "Apple School Manager".
Because they are not supporting the in-app purchases.
https://itunes.apple.com/app/id1490990105

Best regards,
Ryo
