### ISSUE TITLE
Undo Command

### ISSUE THREAD

**Issue by mdc101** [ryouchinsa/Rectlabel-support#142]
I see that there is Undo command in the menu. However, I haven't been able to undo anything. Is there something I'm missing here?

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

Currently we are working on the undo & redo features.
For the first release, we would support except the pixels tools.
For the second release, we would support the pixels tools.
We would let you when the features are available.

**Comment by ryouchinsa** [comment]
The new update version 2.97 was released.
To show the new update on Mac App Store, press command + R to reload.

Added Undo and Redo features except the pixels tools.
You can use undo and redo features for operations below.
The action history size is at most 8.

- Create box, polygon, line, point, and image.
- Move and rotate polygons.
- Edit the polygon shape.
- Duplicate and delete polygons.
- Copy and paste polygons.
- Load previous image labels.
- Change label name.
- Change object color.
- Change layer order.

**Comment by ryouchinsa** [comment]
The new update version 2.98 was released.
To show the new update on Mac App Store, press command + R to reload.

Added Undo and Redo features for the pixels tools.
You can use undo and redo features for operations below.
The action history size is at most 8.
- Create pixels.
- Paint or erase pixels using the brush tool.
- Paint or erase pixels using the brush polygon tool.
- Paint pixels using the "Flood fill" menu.
- Erase pixels using the "Clear pixels" menu.
- Paint or erase pixels using the superpixel tool.

Added "Clear pixels" on the right click menu when you are using the brush tool.
