### ISSUE TITLE
Process all using Core ML slows down after about 400 records

### ISSUE THREAD

**Issue by wildnrg** [ryouchinsa/Rectlabel-support#146]
I had a dataset of about 1700 images, and a CoreML detector model that has one class.  Its very fast < 1s per image up until about 400 -450 images, then it taskes more than 1 second, as it progresses, then slower and slower whereby it might take 10 seconds when it gets to about image #800.  If I move the annotated images out of the folder and restart the app and try again,now with about 1200 images left, it again goes fast for the first 400 or so then slows down really badly.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Another user reported the same issue.
https://github.com/ryouchinsa/Rectlabel-support/issues/145

The new update version 2.99 was released.
To show the new update on Mac App Store, press command + R to reload.

Fixed the memory problem when you use "Process all images using Core ML".
