### ISSUE TITLE
Video Conversation with proper naming.

### ISSUE THREAD

**Issue by sod1684** [ryouchinsa/Rectlabel-support#147]
Currently when I convert a video to images it will be like: 

    frame1_xxx.jpg
    frame2_xxx.jpg
    frame3_xxx.jpg
    ... etc

The issue is that when I step through on the app it loads them out of sequence. So I end up with. 

    frame1_xxx.jpg
    frame10_xxx.jpg
    frame100_xxx.jpg
    frame101_xxx.jpg
    ...
    frame2_xxx.jpg
    frame20_xxx.jpg
    frame200_xxx.jpg
    frame201_xxx.jpg

If you prefix the numbers it will let it sort correctly.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can use "Numeric" for Sort images.
https://rectlabel.com/help#others

Another user reported the same issue before.
We would improve the prefix.
https://github.com/ryouchinsa/Rectlabel-support/issues/135

**Comment by ryouchinsa** [comment]
The new update version 2.99.3 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved "Process all images using Core ML" memory usage on Activity Monitor.
- Improved video frame file prefix to have the same number of digits.
