### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tgreenwood83** [ryouchinsa/Rectlabel-support#148]
Hi dude, 

I use this product a lot and there are a few things that would be cool if you incorporated them.
1. real-time class stats - Instances per class in maybe a graph like Microsofts VoTT tool. This would assist in the collection and labelling of remaining requirement of images. eg. between 200 - 500 per class. I have been doing this after a labelling session to estimate remaining effort.
2.Export attributes as part of the class string. eg- Shoe-Yellow-Right_side etc. I am not 100% sure why attributes are in here if they are exported to be used as classes in a model?
3. Basic Image adjustment, Resizing is great. Cropping would be really great as well.

Hope this helps improving the product.

Thanks

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

1. real-time class stats
Could you show us the screenshot or url of the "real-time class stats" of VoTT?
https://github.com/microsoft/VoTT

2. Export attributes as part of the class string
Which export feature are you using?
https://rectlabel.com/help

3. Basic Image adjustment, Resizing is great.
You can resize images and annotations at the same time.
https://rectlabel.com/help#resize_image
Is this feature not enough for your use-case?

**Comment by ryouchinsa** [comment]
For the 1. real-time class stats, we understood it meant "Tag & Labels".

![スクリーンショット 2019-11-03 13 33 40](https://user-images.githubusercontent.com/1954306/68080966-3a8e9000-fe49-11e9-8b8b-8360aa06f740.png)

**Comment by tgreenwood83** [comment]
Hi Ryouchinsa/Rectlabel-Support

yes, that's correct.

Thankyou

**Comment by tgreenwood83** [comment]
1.

   Which export feature are you using?
   https://rectlabel.com/help

   For yolo, only the objects are exported. So for example.

   Object = Car

   Attribute = Red.

   Only Car is exported, the correct result would be Car-Red.
   2.

   Basic Image adjustment, Resizing is great.
   You can resize images and annotations at the same time.
   https://rectlabel.com/help#resize_image
   Is this feature not enough for your use-case?

   No, Data acquisition is certainly something that is quite difficult and
   expensive. So the goal is to see if the same image can be used multiple
   times, for multiple reasons. Cropping is a great one, this enables the
   image to be split into multiple images with changing the number of pixels
   being used to determine an object.


   thank you for your work

**Comment by ryouchinsa** [comment]
Hi,

> real-time class stats - Instances per class

Added "Show objects and attributes stats" in View menu.
You can show the number of objects and attributes which are used in the current folder.

The new update version 3.00.0 was released.
To show the new update on Mac App Store, press command + R to reload.

![objects_stats](https://user-images.githubusercontent.com/1954306/70502698-e1f79480-1b64-11ea-9ba5-a3385e248917.jpg)

**Comment by ryouchinsa** [comment]
> For yolo, only the objects are exported.

YOLO uses only an object index.
https://rectlabel.com/help#xml_to_yolo

If you want to train both objects and attributes, we recommend that you should train using the PASCAL VOC xml files.

> Cropping is a great one, this enables the
   image to be split into multiple images with changing the number of pixels
   being used to determine an object.

We think this is the data augmentation process which will be done in your code after labeling.
Changing the image translation, scale, rotation, and contrast, you can obtain randomized object samples from the originally labeled image.

**Comment by ryouchinsa** [comment]
- Improved "Show objects and attributes stats" in View menu to "Export objects and attributes stats" in Export menu.

The new update version 3.00.1 was released.
To show the new update on Mac App Store, press command + R to reload.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
