### ISSUE TITLE
Rectlabel won't load a version 3 .mlmodel 

### ISSUE THREAD

**Issue by ShreshthSaxena** [ryouchinsa/Rectlabel-support#149]
Error : The .mlmodel supplied is of version 3, intended for a newer version of Xcode. This version of Xcode supports model version 2 or earlier.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Could you tell us the version of your Xcode and Turi Create?

**Comment by ryouchinsa** [comment]
You need "include_non_maximum_suppression=False" when you export from your python script.

`model.export_coreml('MyDetector.mlmodel', include_non_maximum_suppression=False)`

Deployment for iOS 11 and macOS 10.13
https://apple.github.io/turicreate/docs/userguide/object_detection/export-coreml.html

The .mlmodel supplied is of version 3, intended for a newer version of Xcode. This version of Xcode supports model version 2 or earlier.
https://github.com/apple/turicreate/issues/701

**Comment by ShreshthSaxena** [comment]
That worked, thanks !
