### ISSUE TITLE
Create ML JSON Error

### ISSUE THREAD

**Issue by chintan39** [ryouchinsa/Rectlabel-support#150]
Key "image" has needs to be changed to "imagefilename" in the JSON file
Create ML version 0.5 (15502)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

It looks they changed the JSON format.
https://developer.apple.com/documentation/createml/mlobjectdetector/datasource

```
[
   {
     "imagefilename": "cat and dog.png",
     "annotation":
     [
       {
         "label": "cat",
         "coordinates":
         {
           "y": 2.0,
           "x": 3.9,
           "height": 40.1,
           "width": 20.0
         }
       }
       {
         "label": "dog",
         "coordinates":
         {
           "y": 40.0,
           "x": 38.9,
           "height": 100.1,
           "width": 70.0
         }
       }
     ]
   },
   ...
 ]
```

**Comment by ryouchinsa** [comment]
We checked the previous JSON format and the new JSON format on the macOS Catalina 10.15.1 and Create ML 0.5.
Both worked.

Could you tell us how to reproduce the error?

The previous JSON format
```
[
{
    "image": "raccoon-1.jpg",
    "annotations": [
    {
        "label": "raccoon",
        "coordinates":
        {
            "y": 247,
            "x": 301,
            "width": 442,
            "height": 321
        }
    }]
},
```

New JSON format
```
[
{
    "annotation": [
    {
        "label": "raccoon",
        "coordinates":
        {
            "y": 247,
            "x": 301,
            "width": 442,
            "height": 321
        }
    }],
    "imagefilename": "raccoon-1.jpg"
},
```

**Comment by chintan39** [comment]
It turns out I face error if the json file is formatted to multi line.
With single line it works well

**Comment by ryouchinsa** [comment]
The new update version 2.99.8 was released.
To show the new update on Mac App Store, press command + R to reload.

- Updated so that "Export XML files to JSON file for Create ML" exports the JSON format with "imagefilename" and "annotation" keys.
https://developer.apple.com/documentation/createml/mlobjectdetector/datasource
