### ISSUE TITLE
Mac: Saving an annotation to PNG 

### ISSUE THREAD

**Issue by jeremy-gozlan** [ryouchinsa/Rectlabel-support#151]
Hello, thanks for the good work!
I just subscribed and trying to get my hands around your software, every time I save an image, it is exported as an .xml file even if i clicked on one of the three option " export image as..."
Can you help me?

Jeremy

**Comment by jeremy-gozlan** [comment]
Didnt see the option, thanks

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can export mask images from "Export" menu.
https://rectlabel.com/help#mask_image
