### ISSUE TITLE
Export cropped images from bounding boxes

### ISSUE THREAD

**Issue by marksuman** [ryouchinsa/Rectlabel-support#153]
Feature idea:
We have tagged many images with bounding boxes. There are multiple bboxes per image. Part of our training requires us to have a cropped image of each object within each bounding box. It would be awesome if RectLabel could use the tagged data to create new images for us and also export an XML for each new image with the bbox data for that single image.

Is there a way to do this in RectLabel already? I looked around and haven't found one.

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

Convolutional neural network could use the texture outside the box as context.
This is a great feature.
Why do you want to crop and train the texture inside the bounding box?
We need a clear use-case.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by ryouchinsa** [comment]
Cropped images in bounding boxes can be exported using exporting images for classification feature.

![classification](https://github.com/user-attachments/assets/d1440eea-29ee-443e-94d9-db9c49017c3d)
![aedrian-salazar-ECt01A5HZtw-unsplash_0](https://github.com/user-attachments/assets/0b44dc0e-7fec-44ef-ad7e-23b49096989b)
![aedrian-salazar-ECt01A5HZtw-unsplash_1](https://github.com/user-attachments/assets/0d2329d8-1023-4b2c-a107-25bb82ae6c8e)
![aedrian-salazar-ECt01A5HZtw-unsplash_2](https://github.com/user-attachments/assets/c5b6ad28-747d-42a2-bee6-3696303a1b42)
![aedrian-salazar-ECt01A5HZtw-unsplash_3](https://github.com/user-attachments/assets/898edac1-b0f2-459c-9c03-37761fcfdb48)
