### ISSUE TITLE
Cannot create index color table

### ISSUE THREAD

**Issue by JesperA75** [ryouchinsa/Rectlabel-support#154]
It looks as if an index color table image should be generated and saved when exporting either using "Export mask images for the image" or "Export mask images for all images", but I only get the mask images..

Im using the unlocked version 3.00.2

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you check on "Export an image includes all objects", The mask image which includes all objects is saved as "{image_file_name}_all_objects.png".
This is the png image file which includes the index color table.
https://rectlabel.com/help#export_mask

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
