### ISSUE TITLE
Reverting

### ISSUE THREAD

**Issue by zayala88** [ryouchinsa/Rectlabel-support#156]
Unable to revert to previous version.

<img width="468" alt="Screen Shot 2020-02-05 at 8 51 20 AM" src="https://user-images.githubusercontent.com/52177351/73852385-aee42100-47f4-11ea-87ad-58ddd906c60e.png">

<img width="437" alt="Screen Shot 2020-02-05 at 9 00 13 AM" src="https://user-images.githubusercontent.com/52177351/73853302-426a2180-47f6-11ea-9fed-2d08c9470e03.png">

I have deleted and downloaded the app and still receive the "damaged" error

**Comment by zayala88** [comment]
<img width="437" alt="Screen Shot 2020-02-05 at 9 00 13 AM" src="https://user-images.githubusercontent.com/52177351/73853302-426a2180-47f6-11ea-9fed-2d08c9470e03.png">

**Comment by ryouchinsa** [comment]
Hi,

This troubleshooting might work.
https://rectlabel.com/help#troubleshooting

1. Delete RectLabel via the Launchpad app
2. Log out of the Mac App Store and iTunes.
3. Reboot your Mac.
4. Log back in to the Mac App Store and install RectLabel.

Best regards,
Ryo

**Comment by zayala88** [comment]
The issue was not resolved following the steps provided.

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

Could you send the version 3.00.3 which was downloaded from Mac App Store to your device to support@rectlabel.com?

We would continue supporting you on the e-mail.
