### ISSUE TITLE
Create Box in MacOs 10.15.3 doesn't work properly

### ISSUE THREAD

**Issue by jllarraz** [ryouchinsa/Rectlabel-support#158]
When I try to create a box, the pointer seems to be displaced and the box don'g get the right size neither be in the right place. It makes the app unusable

RectLabe version is 3.00.3

**Comment by ryouchinsa** [comment]
In the latest version 3.00.4, you can create a box with 2 points.
https://rectlabel.com/help#create_box

![createbox](https://user-images.githubusercontent.com/1954306/74593590-1fe6cc80-5070-11ea-860d-032c51db8d8e.gif)
