### ISSUE TITLE
one-click button doesn't work in 3.00.7

### ISSUE THREAD

**Issue by cotevincent94** [ryouchinsa/Rectlabel-support#159]
Attributes don't work when One click box option is selected in version 3.00.7. 

![image](https://user-images.githubusercontent.com/59746730/75930786-647cb100-5e41-11ea-88e4-fb428b92bcd4.png)
![image](https://user-images.githubusercontent.com/59746730/75930826-7ceccb80-5e41-11ea-91bb-64f73834704d.png)
![image](https://user-images.githubusercontent.com/59746730/75930847-870eca00-5e41-11ea-9f8e-63557d365e5c.png)

![image](https://user-images.githubusercontent.com/59746730/75930808-71010980-5e41-11ea-8055-e9d783f004ec.png)

**Comment by ryouchinsa** [comment]
Thanks for your feedback.
Currently 1-click buttons are to select an object and immediately close the label dialog.
Do you want to use the 1-click buttons with attributes?
In this case, 1-click buttons should not close the label dialog when you click.

**Comment by cotevincent94** [comment]
Hi, as illustrated in screen shots, the one-click buttons make the
attributes disappear, which it used to not do. It's useful to have both
options activated
*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Again, we are asking you why do you use the 1-click buttons and attributes at the same time?
Because the 1-click buttons close the label dialog immediately so that you cannot select attributes.

**Comment by ryouchinsa** [comment]
The new update version 3.00.8 was released.
To show the new update on Mac App Store, press command + R to reload.

Improved the 1-click buttons when you are using attributes.
For the object with attributes, 1-click buttons do not close the label dialog.

![1click_buttons_with_attributes](https://user-images.githubusercontent.com/1954306/76124371-dae60280-603d-11ea-8989-6f63a3f095e8.gif)

**Comment by cotevincent94** [comment]
That's great !

Exactly what I needed.

Thanks,

*Vincent Côté.*
C: (514) 214-1522
