### ISSUE TITLE
Search function is not functionning well

### ISSUE THREAD

**Issue by cotevincent94** [ryouchinsa/Rectlabel-support#160]
cmd+F function not working well. File name is present in folder and can be found using search function of finder, but not able to be found in rectlabel. Sample file name : 
200110_045516_1578653723195_1683920-007_XX_XXX_SR1683921-008.jpg

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.
"Search images" feature searches images whose label files include the search keyword.
It does not search the image file name.
https://rectlabel.com/help#search_images
