### ISSUE TITLE
Import Create ML JSON annotations

### ISSUE THREAD

**Issue by NachoVarga** [ryouchinsa/Rectlabel-support#161]
Hi, I would like to import JSON annotations (Create ML format) and I did not find a way to do so in the help document - is it possible?
Thanks a lot!

[ { "image": "IMAGE_0149.PNG",
      "annotations": [ {
                "label": "top_left",
                "coordinates": {
                    "x": 541,
                    "y": 286,
                    "width": 290,
                    "height": 276
                } }, {
                "label": "top_right",
                "coordinates": {
                    "x": 1550,
                    "y": 280,
                    "width": 291,
                    "height": 272
              } ] } ]

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you tell us the use-case when you have to import the Create ML JSON file?

**Comment by NachoVarga** [comment]
The use case is quality control for a Create ML training set: check that all the bounding boxes have been set right and correct if necessary.

**Comment by ryouchinsa** [comment]
Thanks for the details.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
- Added "Import Create ML JSON file to XML files" on Export menu.

The new update version 3.01.3 was released.
To show the new update on Mac App Store, press command + R to reload.

**Comment by NachoVarga** [comment]
Wow, this was really quick - excellent!
Thank you very much!
