### ISSUE TITLE
How to export train.txt

### ISSUE THREAD

**Issue by daliu-daliu** [ryouchinsa/Rectlabel-support#163]
How to export train.txt?Thank you!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can use "Export train, val, and test.txt" on Export menu.
https://rectlabel.com/help#split_images

![スクリーンショット 2020-04-26 19 37 19](https://user-images.githubusercontent.com/1954306/80305059-60439300-87f5-11ea-943b-12cc9f689162.png)

**Comment by daliu-daliu** [comment]
Thank you very much for your answer, but I can't find the button where to export train.txt?
There was a second problem: I was using the visual genome data set with the property detection, so rectlabel was the annotation tool I found to be satisfactory.
However, I found that there are some differences between the two formats. Rectlabel directly adds the attribute to &lt;
Name&gt;
& lt;
/ name&gt;
The visual genome is in each &lt;
Object&gt;
& lt;
/ object&gt;
One or more attributes are added to it &lt;
Attribute&gt;
& lt;
/ attribute&gt;
Tag. I wonder if this will cause an error when the data set is read?
Thank you very much!

**Comment by ryouchinsa** [comment]
Thanks for the details.
We understand that whether the attributes are saved with the object name or saved as separate tags is important for our users.
Could you show us the image and annotation file as an example?
We need to know the detailed data format.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
