### ISSUE TITLE
Improve mouse functionality 

### ISSUE THREAD

**Issue by Goldenstarc** [ryouchinsa/Rectlabel-support#164]
Hi,
please add Right Click to discard creating box (alternative to ESC button) .
(its needed when using mouse)
mouse Middle click to change to next image.
there are also additional button on side of mouses which can be used for this.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We are using Magic Mouse.
https://www.apple.com/shop/product/MLA02LL/A/magic-mouse-2-silver

Which mouse are you using?

Magic Mouse gestures
https://rectlabel.com/help#magic_mouse

Slide a finger to move the image.
Double-tap with a finger for smart zoom.
Swipe left or right with two fingers to change the image.

System Preferences > Mouse > Point & Click tab > Smart zoom.
System Preferences > Mouse > More Gestures tab.
For "Swipe between pages", select "Swipe with two fingers".

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
