### ISSUE TITLE
Issue login 

### ISSUE THREAD

**Issue by Tharwa86** [ryouchinsa/Rectlabel-support#165]
I already have purchased and paid for a yearly account of $59 for tharwa_86@yahoo.com, not sure why are saying' a free account '. please confirm.

Thanks,
Tharwa
<img width="1026" alt="Screen Shot 2020-05-15 at 7 09 26 AM" src="https://user-images.githubusercontent.com/53162443/82048903-11ae4980-967b-11ea-9841-07b18c805fc7.png">

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In the current version, there is a problem that purchase dialog is shown for one-time payment users.
We fixed the problem and submitted the new update to Apple.

When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 3.01.7 was released.
To show the new update on Mac App Store, press command + R to reload.

- Fixed the purchase dialog problem for one-time payment users.

**Comment by Tharwa86** [comment]
I updated my version to 3.01.7, but I still have the issue.

**Comment by ryouchinsa** [comment]
Hi,

We have "RectLabel - One-time payment" in our environment.
The version is 3.01.7.
https://itunes.apple.com/app/id1490990105

The purchase dialog is not shown for both when it launches and labeling changing some images for tens of minutes after launched.

To reproduce the problem, could you tell us when the purchase dialog shows up?

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
