### ISSUE TITLE
Boolean operators and disconnected objects

### ISSUE THREAD

**Issue by fabmeyer** [ryouchinsa/Rectlabel-support#166]
How can I assign two polygons to the same object? (Add two polygons)
How can I subtract one polygon from another?

I want to create a dataset for COCO / Mask R-CNN

Thanks!

**Comment by fabmeyer** [comment]
Excuse me, I found out how to solve the problem (Label Pixels)

Maybe It would be nice to be able to merge and subtract layers of labels in the labels list (on the right side of the window) via right click on two selected labels?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

As you know, using brush polygon tool, you can merge/subtract multiple polygons.

> Maybe It would be nice to be able to merge and subtract layers of labels in the labels list

We wonder that how is the data format in COCO JSON format.
http://cocodataset.org/#format-data
```
annotation{
"id": int, 
"image_id": int, 
"category_id": int, 
"segmentation": RLE or [polygon], 
"area": float, 
"bbox": [x,y,width,height], 
"iscrowd": 0 or 1,
}
```

When merge multiple polygons, it would be like this.
```
"segmentation": [[polygon1], [polygon2], ...], 
```
When subtract, we do not know the data format.
