### ISSUE TITLE
showing label name on top left of image border-box

### ISSUE THREAD

**Issue by nicole234** [ryouchinsa/Rectlabel-support#168]
sometimes working with images that have multiple objects, it's getting a bit hard to which one is which (you have to select the label from right side-bar to know where is a specific label-box on the image), having the label on the box makes it easier.

![image](https://user-images.githubusercontent.com/26182673/85831116-020a4080-b7a3-11ea-8c4f-7ad0a3419d3c.png)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can use "Show label on the box" in View menu to show each label name on the box.
https://rectlabel.com/help#show_label_on_box

![スクリーンショット 2020-06-27 5 49 21](https://user-images.githubusercontent.com/1954306/85900114-3715a200-b83a-11ea-96e0-b746efb346b7.png)

**Comment by nicole234** [comment]
thanks, I didn't see this before.
