### ISSUE TITLE
[Regression] the mode is not shown in 1.35

### ISSUE THREAD

**Issue by xvolks** [ryouchinsa/Rectlabel-support#17]
Since I've upgraded to 1.35 the mode described in #12 in not working anymore.

**Comment by ryouchinsa** [comment]
We thought the original button design was not the best to show which mode we were in.
So in 1.35, we removed the feature until the next update.
We are working on the new button design using "SYFlatButton" below.
https://github.com/Sunnyyoung/SYFlatButton

We would update soon.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

![json_web](https://user-images.githubusercontent.com/1954306/29230997-59790590-7f20-11e7-94c4-a76d7f069f95.jpg)

**Comment by ryouchinsa** [comment]
RectLabel 1.36 was released.
Changed the style of buttons on the main window.
Restored the feature of which mode you are in.
