### ISSUE TITLE
Pixel blending makes pixel-wise segmentation into a more difficult task.

### ISSUE THREAD

**Issue by Jaro93** [ryouchinsa/Rectlabel-support#170]
Hi,

We're using PNG (but have also tried BMP and TIFF image format) in RectLabel. The result at high zoom level is that it seems like there is a gradient added to the centre of each pixel going outwards. This makes pixel-wise segmentation more difficult to achive accurately.

For example, zoomed in image in RectLabel:

<img width="1467" alt="RectLabel" src="https://user-images.githubusercontent.com/36230358/86829863-9a56ce00-c09d-11ea-9b98-e29a3d92e9bb.png">

Compared to a zoomed in image in MacOS's Preview app:

<img width="541" alt="PreviewApp" src="https://user-images.githubusercontent.com/36230358/86830018-cbcf9980-c09d-11ea-92d5-06bd8b3649dd.png">

It's important for us to create accurate labels, and this is a bit of a hinderance. Could you please remedy the issue ASAP? Thanks.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We are using linear filter for the image and the mask.
white/black box: image
cyan: mask

![スクリーンショット 2020-07-09 12 21 32](https://user-images.githubusercontent.com/1954306/86993625-6e436600-c1df-11ea-9055-d1aa095e43ef.png)

We can change to nearest filter.

![スクリーンショット 2020-07-09 12 18 46](https://user-images.githubusercontent.com/1954306/86993790-e0b44600-c1df-11ea-8036-6f8659065f2d.png)

Does this work for you?

**Comment by Jaro93** [comment]
That would be fantastic, thank you!

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 3.02.3 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved image and mask filter from linear to nearest so that you can label pixel-wise mask when high zoom.

Let us know your feedback.

**Comment by Jaro93** [comment]
Thank you so much!
