### ISSUE TITLE
Keypoint with Skeleton Issue

### ISSUE THREAD

**Issue by panchgonzalez** [ryouchinsa/Rectlabel-support#172]
I noticed that the "Draw keypoints with Skeleton" is not available in the Edit menu after upgrading. The issue persists even after following the troubleshooting steps.

<img width="331" alt="Screen Shot 2020-09-21 at 2 30 18 PM" src="https://user-images.githubusercontent.com/15077029/93814487-35c9fa80-fc1a-11ea-92fe-49eb22b84f6e.png">
<img width="194" alt="Screen Shot 2020-09-21 at 2 37 18 PM" src="https://user-images.githubusercontent.com/15077029/93814497-382c5480-fc1a-11ea-8f20-e8fdb6656fff.png">

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You mean that you can use "Create keypoints" feature but the skeleton is not shown with keypoints, correct?

Keypoints names/edges are saved in the settings file.
https://rectlabel.com/help#create_keypoints

Please check whether the skeleton exists in your settings file.
https://rectlabel.com/help#export_settings

The skeleton is associated with the object name.
An object name can have only one skeleton settings.

![スクリーンショット 2020-09-22 5 48 11](https://user-images.githubusercontent.com/1954306/93819888-4bc9d080-fc97-11ea-8756-a18607b61226.png)

**Comment by panchgonzalez** [comment]
Thanks for the response @ryouchinsa!

I managed to get around it by importing a base COCO json file with the skeleton information in the `categories` entry. That seemed to also update the settings file properly. 

I'm wondering if there is any planned feature to create skeletons through the GUI instead of editing the settings file? That would be very helpful.

Cheers!

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

You can change keypoints names/edges through the GUI.
To add an edge, drag from one to another point holding option button.
https://rectlabel.com/help#create_keypoints

The object name "person" should be set on the objects table in advance.
https://rectlabel.com/help#objects

![keypoints](https://user-images.githubusercontent.com/1954306/94090383-68f5cf00-fe50-11ea-9437-c965a706fa97.gif)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
