### ISSUE TITLE
Width and height of bounding boxes not appearing anymore

### ISSUE THREAD

**Issue by cotevincent94** [ryouchinsa/Rectlabel-support#173]
The width and height of bounding boxes used to be appearing at the bottom of the screen when the object was selected. This essential feature has now disappeared.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

To restore the feature, we need to know the detailed use-case.
Why do you need to check the box width and height during labeling?

**Comment by cotevincent94** [comment]
Hi Ryo,

My teammates and I from IBM use this feature daily to view the size of
objects. One of the specific use cases is to use the size to inform a
rule-based classification (e.g. if distance from vertical is more than 5
px, object is slanted). Another use case for the feature could be to
quickly compare a predicted bounding box to its ground truth to see
the measurement accuracy of its length.

Let me know if you want more examples.

Thanks,
*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Thanks for the details.

We would restore the showing box size feature in the next update.
When the new update is released, we will let you know.

**Comment by cotevincent94** [comment]
Thank you !
*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
The new update version 3.03.5 was released.
To show the new update on Mac App Store, press command + R to reload.

- Restored "Showing box size" feature when create/edit boxes.
- Added "Import objects table from all images" on App menu. 
This feature reduces time to set up your objects table when you opened new images/annotations folders which are already labeled.

**Comment by cotevincent94** [comment]
Hi Ryo,

Thanks for the follow up.

I was also wondering what is the best way to propose improvements for the
software. One of the simple improvements that has been suggested by the
team is the ability to select the image name directly in Rectlabel to allow
to a rapid search outside of it (e.g. in Finder on Excel).

Thanks,

*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Thanks for your feedback.
To copy the current image file name, click on the image file name shown on the top-left corner.

**Comment by cotevincent94** [comment]
Wow, thanks for the tip ! Would also be great to be able to search for an
image by its name.

Thanks,
*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Thanks for the request.

Please tell us the reason why you need to search the image by its name.
How many images are there in your images folder?

**Comment by cotevincent94** [comment]
An image folder can have up to a couple of thousand images. Use cases are
numerous, but the most common one would be to look for an image for which
you know there are the following :
- A problem with the annotation according to a team member
- A model error that you want to inspect. For example, the model gave a FP
or a FN for a specific image and you want to understand the conditions of
the image.
- You have a specific annotation you want to show a coworker, but do not
have opened at the moment.

As I said, there are more, but I think these will be more than enough.
Searching by annotation is useful, but not sufficient.

Thanks,

*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Thanks for the details.

When the new update is released, we will let you know.

**Comment by cotevincent94** [comment]
Great thanks a lot ! Really happy you are taking some feedback and
suggestions. We are a group of 50 IBMers using the software day to day so
it's good to be able to influence it.

Thank again,
*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Today we submitted the new update to Apple.

> We are a group of 50 IBMers using the software day to day

Are you using Apple Business Manager to buy multiple RectLabel apps and distribute to your members?
https://support.apple.com/guide/apple-business-manager/welcome/web

If not, please tell us the reason why you are not using Apple Business Manager.

**Comment by cotevincent94** [comment]
Wow, that was fast!

We are not using Apple Business Manager because this does not follow IBM's
license management policies. It is simpler for us to buy the licenses
individually.

I checked on the App store and I don't see version 3.03.6

Let me know,

Thanks,

*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
The new update is waiting for the app review from Apple.

> this does not follow IBM's license management policies.

Do you know some companies which are using Apple Business Manager around you?

**Comment by cotevincent94** [comment]
I do not, unfortunately.

Sorry,

*Vincent Côté.*
C: (514) 214-1522

**Comment by ryouchinsa** [comment]
Thank you.

The new update version 3.03.6 was released.
To show the new update on Mac App Store, press command + R to reload.

- Improved "Search images" so that you can search images by label name or image name.

![スクリーンショット 2020-10-08 20 17 49](https://user-images.githubusercontent.com/1954306/95503329-2e5e6b80-09e6-11eb-8b59-e94a8aa6d5a1.png)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
