### ISSUE TITLE
Bounding box labels shift by approximately half a pixel

### ISSUE THREAD

**Issue by hjedwardkim** [ryouchinsa/Rectlabel-support#174]
Upon opening an image with its annotations (bounding box labels in this case), all the labels are shifted slightly by approximately half a pixel right and half a pixel down. This phenomena is replicable by several labellers of my team.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Could you show us the screenshot to understand the details?
If you could give us an example image and annotation file, it would be very helpful.

**Comment by hjedwardkim** [comment]
[rectlabel-bug.zip](https://github.com/ryouchinsa/Rectlabel-support/files/5338492/rectlabel-bug.zip)

Sure thing. Attached you will find a before and after screenshot zoom of the label, a screen recording replicating the issue, the JPG image, and the XML annotation of the picture in question. In our team's image set, this seems to occur with all bounding box labels.

**Comment by ryouchinsa** [comment]
Thanks for the details.

It is the floating-point rounding error.

When we read/write the annotation file, we have to convert between integer coordinates and floating-point coordinates.
To restore the exact floating-point coordinates, you can use "Save as floating-point values" on the settings dialog.
https://rectlabel.com/help#others

To obtain the integer coordinates from floating-point coordinates in your application, round it by yourself.
xi = roundf(xf)

Let us know your opinion.

![others](https://user-images.githubusercontent.com/1954306/95329293-b018a100-08e1-11eb-84d5-95631e6b1a2d.jpg)

**Comment by hjedwardkim** [comment]
Okay thank you for the response. I will have everyone have their settings saved to save as floating-point values in the future.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
