### ISSUE TITLE
Convert XMLs to Text format

### ISSUE THREAD

**Issue by bjanfeshan** [ryouchinsa/Rectlabel-support#179]
How I can convert all XMLs in one directory into one txt file?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you tell us the details of the text file format?
Which ml tools are using the text file format to train object detection models?

**Comment by bjanfeshan** [comment]
I am using [MMDetection](https://github.com/open-mmlab/mmdetection) tool for training an SSD or YOLO model.

**Comment by ryouchinsa** [comment]
Thanks for the details.

We read their document and they says "we recommend to convert the data into COCO formats and do the conversion offline".
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_dataset.md

Please use "Export XML files to COCO JSON file" on RectLabel.
https://rectlabel.com/help#xml_to_coco

Does this work for you?

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
