### ISSUE TITLE
App Icon Size on macOS Big Sur

### ISSUE THREAD

**Issue by philimat** [ryouchinsa/Rectlabel-support#180]
Hello, been using the app for a month or so now and really like it. One thing that I find annoying and would be an easy fix (I think) is that your app's icon size is much larger than all the rest of the square-like icons and sticks out like sore thumb. Is there a way to make the icon size more in line with the rest of the system so it doesn't look so out of place?

<img width="1373" alt="Screen Shot 2021-03-31 at 10 11 43 AM" src="https://user-images.githubusercontent.com/42723984/113168402-40d59700-920a-11eb-815b-5775ac216284.png">

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We made the app icon smaller.

![スクリーンショット 2021-04-01 19 51 32](https://user-images.githubusercontent.com/1954306/113284514-b6358a80-9324-11eb-88d4-c20be185bfbe.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 3.04.5 was released.
To show the new update on Mac App Store, press command + R to reload.

- Made app icon smaller
- Added Enter Full Screen hotkey on View menu

**Comment by philimat** [comment]
Wow that was amazingly fast. Thank you! Keep up the great work.
