### ISSUE TITLE
Prompted to unlock full app

### ISSUE THREAD

**Issue by mqLevan** [ryouchinsa/Rectlabel-support#181]
Updated the App and was now prompted to pay to unlock free app. Restore past purchases does nothing, the app was paid for over a year ago as a one time purchase

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you bought "RectLabel - One-time payment", we do not show the purchase dialog in the app.
Also, in app menu, "Unlock Full App" menu is not shown in the app.

Do you mean "RectLabel - One-time payment" is showing the purchase dialog?

**Comment by mqLevan** [comment]
I had purchased the one time payment option in the past and I have the invoice but the app store is prompting me to re-pay the full price as it says I don't have the one time payment app.

**Comment by ryouchinsa** [comment]
Could you send your purchase receipt to support@rectlabel.com?
This is the path where your purchase receipt is.
/Applications/RectLabel.app/Contents/_MASReceipt/receipt

**Comment by ryouchinsa** [comment]
The new update version 3.04.6 was released.
To show the new update on Mac App Store, press command + R to reload.

- Fixed the problem that the purchase dialog appears for some users who bought Full App.
- Improved multiple selection for drag/drop and layer up/down.
- Added "Save as jpg" button on Hotkeys tab on the settings dialog.
- Restored "Create point" on Edit menu.

**Comment by mqLevan** [comment]
Everything is working as before once again!
 
Thank you again for your support and timely responses.
___________________________
 
Michael Levan
Consultant - Consulting by Degree - Canada
Watson IoT & Industry 4.0
BEng, Electrical Engineering
 
 
----- Original message -----From: Ryo Kawamura ***@***.***>To: ryouchinsa/Rectlabel-support ***@***.***>Cc: mqLevan ***@***.***>, Author ***@***.***>Subject: [EXTERNAL] Re: [ryouchinsa/Rectlabel-support] Prompted to unlock full app (#181)Date: Thu, May 6, 2021 2:26 PM      The new update version 3.04.6 was released. To show the new update on Mac App Store, press command + R to reload. Fixed the problem that the purchase dialog appears for some users who bought Full App. Improved multiple selection for drag/drop    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
The new update version 3.04.6 was released.To show the new update on Mac App Store, press command + R to reload.
        Fixed the problem that the purchase dialog appears for some users who bought Full App.        Improved multiple selection for drag/drop and layer up/down.        Added "Save as jpg" button on Hotkeys tab on the settings dialog.        Restored "Create point" on Edit menu.
