### ISSUE TITLE
No CoreML tab in BigSur

### ISSUE THREAD

**Issue by yongja-jayong** [ryouchinsa/Rectlabel-support#183]
![image](https://user-images.githubusercontent.com/39395433/125381938-c3f0b680-e3cf-11eb-8ca1-9386a1084603.png)

I installed Rectlabel to Macbook(BigSur 11.2.3, 16 inch, 2019) and there is no CoreML tab. 
There was CoreML tab when I first opened the application but in a second, it disappears.

However, my other MacBook which is Catalina (10.15, 15 inch, 2017), there is CoreML tab.
Does Rectlabel not support BigSur? 
If it is not, do you have a plan to support BigSur?

**Comment by ryouchinsa** [comment]
Hi, 
Thanks for writing the issue.

Which app are you using among RectLabel, RectLabel Lite, RectLabel Pro?

For RectLabel, on macOS Big Sur 11.4, 13-inch, M1, 2020, we are subscribing to monthly plan, and Core ML tab is shown on the top-bar menu.

Could you send your app receipt below to support@rectlabel.com?
/Applications/RectLabel.app/Contents/_MASReceipt/receipt

Best regards,
Ryo

**Comment by yongja-jayong** [comment]
Hi,
Thanks for replying.
I sent my app receipt to support@rectlabel.com.

1. 
I am using Rectlabel and my free trial period is over.
- Macbook BigSur 11.2.3, 16 inch, 2019: CoreML is not shown. I sent this receipt.
- Macbook Catalina 10.15, 15 inch, 2017):  CoreML is shown. and it was possible to use CoreML during the free trial period (January).

2.
I found a colleague subscribing Rectlabel, and there is CoreML tab. (BigSur 11.3.1, 16-inch 2019)

So now I guess that if I subscribe Rectlabel, CoreML could be shown.

**Comment by yongja-jayong** [comment]
I just subscribed to the app and now I can see CoreML tab. Thank you so much!

**Comment by ryouchinsa** [comment]
Thanks for subscribing.
If you have some feature requests for Core ML features, please let us know.
