### ISSUE TITLE
Memory leak when augmenting images

### ISSUE THREAD

**Issue by jimjam-slam** [ryouchinsa/Rectlabel-support#188]
Hi there! I'm trying to augment the images in my dataset (about 1057) images using the rotate and contrast options. When I start the process, RectLabel's memory consumption immediately starts rising from a steady 110 MB or so, by about a gigabyte every 5-10 seconds. The app crashes when my laptop's 16 GB is exhausted (well before all images are processed), and I get a macOS dialog asking me to kill apps.

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

To reproduce the problem in our environment, let us ask some questions.

- The number of "Augmented images per an image"
- Average Image size for those 1057 images
- Drawing object types(boxes, polygons, pixels, etc.)

**Comment by jimjam-slam** [comment]
I'm asking for 2 augmented images per image. All of the 1057 source images are 3024x4032 (although I note that the augmented images come out a little bigger due to the padding the rotation introduces). The object types are boxes.

**Comment by ryouchinsa** [comment]
Thanks for the details.

We could reproduce and solve the problem using autoreleasepool.
https://developer.apple.com/documentation/foundation/nsautoreleasepool

Heap memory used for image processing was not released immediately.

When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update version 3.06.2 was released.
To show the new update on Mac App Store, press command + R to reload.

Improved the heap memory problem for "Augment all images".

Let us know your feedback.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
