### ISSUE TITLE
Access to brush and superpixel tools.

### ISSUE THREAD

**Issue by joaourbano** [ryouchinsa/Rectlabel-support#190]
Hi,

Looked everywhere but couldn't find out how to access both brush and super pixel tools.

I have rectlabel pro installed on a Mac, using macOS Monterey.

Thanks

**Comment by ryouchinsa** [comment]
Thanks for using RectLabel.

You can find at the top bar Edit -> Label pixels menu to use brush and superpixel tools.
https://rectlabel.com/help#label_pixels

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by tongclement** [comment]
Hi - I have the same problem and can't find see label pixel under the edit menu - many thanks!

**Comment by ryouchinsa** [comment]
We think that you are using the YOLO text format.
In the YOLO text format, using the "Create polygon" feature, you can create the mask and export to the YOLO segmentation format.
To use the "Create pixels" feature, please use the PASCAL VOC XML format.
https://rectlabel.com/help#label_fast

**Comment by tongclement** [comment]
> We think that you are using the YOLO text format.
> In the YOLO text format, using the "Create polygon" feature, you can create the mask and export to the YOLO segmentation format.
> To use the "Create pixels" feature, please use the PASCAL VOC XML format.
> https://rectlabel.com/help#label_fast

Yes you are right @ryouchinsa - I was wondering whether superpixel can be used to create polygons though - many thanks

**Comment by ryouchinsa** [comment]
After creating pixels using the superpixels tool, you can convert the pixels to the polygons right clicking on the label.
https://rectlabel.com/help#create_pixels
