### ISSUE TITLE
Superpixel and brush tools.

### ISSUE THREAD

**Issue by joaourbano** [ryouchinsa/Rectlabel-support#191]
Hi,

How can I access these tools?

Thanks

**Comment by ryouchinsa** [comment]
Thanks for using RectLabel.

You can find at the top bar Edit -> Label pixels menu to use brush and superpixel tools.
https://rectlabel.com/help#label_pixels

**Comment by joaourbano** [comment]
Hi Ryo,

I understood from your your support page https://github.com/ryouchinsa/Rectlabel-support/blob/master/README.md that the automatic labeling of images is possible using Core ML from within rectLabel pro.

Cold you please provide me some guidance on this? It could a time saver for me, I am currently labeling around 10k pictures, where the automatic labeling of bottles, boxes and cans could be extremely useful.

Regards,

João

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you are training your images/annotations on Create ML, the trained model is in Core ML format.
https://rectlabel.com/help#xml_to_createml

Otherwise you have to convert your trained model to Core ML format.
https://coremltools.readme.io/docs

RectLabel can load the Core ML model and automatically label images.

**Comment by joaourbano** [comment]
Hi Ryo,

I must have misunderstood something…

Indeed, my aim is to train a model in Create ML, and I am annotating images using RectLabel pro for that.

From your site https://github.com/ryouchinsa/Rectlabel-support/blob/master/README.md I got the following  picture.



And my understanding was that rectLabel provided this functionality. Is this correct? And if yes, where can I download the model from?

Further to that on your site it says that “This blog provides MobileNetV2 + SSDLite with Core ML.” Where can download these pre-trained models?

Regards,

João

**Comment by ryouchinsa** [comment]
Hi, 

You can use the Developer Tools menu in Xcode to open Create ML.
https://developer.apple.com/machine-learning/create-ml/

![スクリーンショット 2022-01-08 22 00 01](https://user-images.githubusercontent.com/1954306/148651510-aa2612e2-55cb-45ec-b6f0-57147bf54342.png)

Our document for loading core ml model is here.
https://rectlabel.com/help#load_coreml

Apple provides Core ML Models for YOLOv3.
https://developer.apple.com/machine-learning/models/

This blog provides MobileNetV2 + SSDLite with Core ML.
https://machinethink.net/blog/mobilenet-ssdlite-coreml/

You can download the MobileNetV2 + SSDLite from here.
https://github.com/hollance/coreml-survival-guide

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
