### ISSUE TITLE
COCO JSON import doesn't work properly

### ISSUE THREAD

**Issue by mamromer** [ryouchinsa/Rectlabel-support#192]
I have augmented my images outside of Rectlabel to make the image square. I generated a new Coco JSON file and try to import it in Rectlabel. I placed the json file in the images map where the images are.
When I import the json file the xml files are generated but in only a few xml files the annotations are added. In the rest I only get:
<annotation>
    <folder>images</folder>
    <filename>filename.jpg</filename>
    <size>
        <width>608</width>
        <height>608</height>
        <depth>3</depth>
    </size>
</annotation>

As far as I can see all the information is present in the json file but just not saved in the xml files.

Any ideas?
[traincoco.json.zip](https://github.com/ryouchinsa/Rectlabel-support/files/7765036/traincoco.json.zip)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Currently we assume that annotations array is sorted in ascending order by image_id.
So that collecting annotations for each image_id is fast.
In the next update, we will change so that for each image_id we search all annotations.

**Comment by mamromer** [comment]
Hi Ryo,
Thanks for the prompt answer! When will the next update come out?

**Comment by ryouchinsa** [comment]
The next update will be released in a week.
Until then, if you arrange your annotations array in ascending order by image_id, importing would work.

**Comment by mamromer** [comment]
I just did that and now it is working great. Thanks!

**Comment by ryouchinsa** [comment]
Hi, 

Thanks for the feedback.

The new update version 3.07.6 was released.
To show the new update on Mac App Store, press command + R to reload.

For importing coco json file, we were assuming that annotations array is sorted in ascending order by image_id.
In this update, we changed so that for each image_id we search all annotations array elements.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
