### ISSUE TITLE
Processing with Core ML error

### ISSUE THREAD

**Issue by caichunjian520** [ryouchinsa/Rectlabel-support#194]
If there are only several objects in the image, when I press ^A to process the image with Core ML, everything is fine. Rectlabel will label all objects immediately.

But if the number of objects in a image is 54 (There are 52 classes in mlmodel file, so every class's object is included in this image), after process the image with ^A, it says
performRequests error
encountered unknown exception

**Comment by ryouchinsa** [comment]
Thanks for writing the detailed issue.

To reproduce the problem in our environment, could you send the image and Core ML model to support@rectlabel.com?

**Comment by caichunjian520** [comment]
Sorry, the Core ML model will be used for business purpose app, so it can't be sent.
And I tried to drag and drop the image into Xcode Core ML model, no object was detected, so I think it is not a issue within Rectlabel. I will close this issue.

**Comment by ryouchinsa** [comment]
Hi,

We understand that business purpose app cannot be sent.
How about reproducing the problem using a public Core ML model and an image?

There are more than 50 objects detected by a Core ML model and had no problem.

Let us know your opinion.

![スクリーンショット 2022-01-22 3 00 00](https://user-images.githubusercontent.com/1954306/150577093-200061c6-8ef2-4c86-aee3-f09fc8b99664.png)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
