### ISSUE TITLE
Importing Projects, objects and attributes

### ISSUE THREAD

**Issue by joaourbano** [ryouchinsa/Rectlabel-support#195]
Hi,

Could you please provide me with some help with the following?

I am currently labelling a few thousand images where it is important to import projects, objects and attributes from an existing CSV.

In this project I have to label road vehicles according to Type, brand and model. I am currently using a **Project** for each type of vehicle (SUV, Van, Sports Car, Roadster, ...); I use **objects** for the BRAND (Ford, GM, Fiat, Seat,...) and **attributes** for the individual models (Fiat 600, Fiat Mirafiori, Fiat 500, etc).

Is it possible to upload a list of all the existing labels into rectlabel from a csv file? 

Looking forward to your reply,

Thanks in advance

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

To understand the current situation, could you export the settings file and send to support@rectlabel.com?
RectLabel -> Export settings file.

In the settings file, you are using Projects, Objects, and Attributes to label a variety of car types.

For the csv file to import to RectLabel, could you show us the detailed format?

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by joaourbano** [comment]
Hi,

It has been a long time, here goes a sample civ file. Can you help?

Thanks
[sample.csv](https://github.com/ryouchinsa/Rectlabel-support/files/9821738/sample.csv)
[sample.csv](https://github.com/ryouchinsa/Rectlabel-support/files/9821741/sample.csv)

**Comment by ryouchinsa** [comment]
We implemented to import the CSV file below to projects, objects, and attributes tables.
Are they correct?
Please let us know your opinion.

Brand;Type;Model;motor;Model Ref
Fiat;Sports;500;1700;asfdf125
;;500;1900;gagdgd54
;;500;2000;hhheree55
Fiat;Urban;127;1700;dsffsad415
;;127;1900;15545adfs
;;127;2000;855444a
Fiat;Family;131;1700;dafsdf4
;;131;1900;4747a
;;131;2000;4882524a
Fiat;Sedan;Mirafiori;1700;455855b
;;Mirafiori;1900;adsfa445
;;Mirafiori;2000;448554c
Ford;Urban;Fiesta;1350;454545421c
;;Fiesta;1700;asdfa54c
;;Fiesta;1900;4545455c
Ford;Family;Focus;2000;6458484c
;;Focus;2500;aadfsdf4444
;;Focus;1700;adfadf5577
Ford;Sports;Mustang;1700;adssdf4444
;;Mustang;1900;adfasdf444
;;Mustang;2000;adfaasd447785
Ford;SUV;Kuga;1700;bbbb121b
;;Kuga;1900;bbbb122b
;;Kuga;2000;bbb25474c

![スクリーンショット 2022-11-18 11 31 20](https://user-images.githubusercontent.com/1954306/202603475-cacf9e25-2378-4e9e-88c1-9ceb5b196f8e.png)
![スクリーンショット 2022-11-18 11 31 23](https://user-images.githubusercontent.com/1954306/202603482-78267028-8cac-4c75-839e-0e495edffae0.png)
![スクリーンショット 2022-11-18 11 31 27](https://user-images.githubusercontent.com/1954306/202603484-7c933698-98e9-4fda-b473-a462de779149.png)
![スクリーンショット 2022-11-18 11 31 49](https://user-images.githubusercontent.com/1954306/202603487-4c3ed21e-21c6-4271-b6f0-47234bbb4476.png)
![スクリーンショット 2022-11-18 11 31 52](https://user-images.githubusercontent.com/1954306/202603489-26dadcb8-9a19-42e2-b049-7e8a64bb36ac.png)
![スクリーンショット 2022-11-18 11 31 56](https://user-images.githubusercontent.com/1954306/202603490-9ab9fc8a-bbda-4e90-b38a-ec67ed2a902c.png)
![スクリーンショット 2022-11-18 11 32 05](https://user-images.githubusercontent.com/1954306/202603493-6ccfb2fa-dbbb-44ef-bd50-e1ea5d2db318.png)
![スクリーンショット 2022-11-18 11 32 09](https://user-images.githubusercontent.com/1954306/202603495-acdd8b28-ff9c-4a9f-923a-8997e37c50ec.png)
![スクリーンショット 2022-11-18 11 32 14](https://user-images.githubusercontent.com/1954306/202603496-08f6030b-93df-41b6-9fd1-3e203328d429.png)
![スクリーンショット 2022-11-18 11 32 20](https://user-images.githubusercontent.com/1954306/202603498-cca75271-1da9-4b70-89f2-4a0fe283f7c5.png)
![スクリーンショット 2022-11-18 11 32 25](https://user-images.githubusercontent.com/1954306/202603502-ac83d51f-0256-47f7-bc10-5944c9a51355.png)
![スクリーンショット 2022-11-18 11 32 29](https://user-images.githubusercontent.com/1954306/202603507-df042649-bb28-4ce6-a95f-925406b1bc2e.png)
![スクリーンショット 2022-11-18 11 32 35](https://user-images.githubusercontent.com/1954306/202603508-9651fda6-07c1-4eef-956f-bd09a2b2a8c2.png)
![スクリーンショット 2022-11-18 11 32 38](https://user-images.githubusercontent.com/1954306/202603512-8adf54eb-2905-418b-84a4-184996121f89.png)
![スクリーンショット 2022-11-18 11 32 43](https://user-images.githubusercontent.com/1954306/202603514-35dc3433-409b-42f7-b91a-ab7cc5cdceff.png)

**Comment by ryouchinsa** [comment]
Updated. We implemented to import the CSV file below to projects, objects, and attributes tables.
Are they correct?
Please let us know your opinion.

> In this project I have to label road vehicles according to Type, brand and model. I am currently using a Project for each type of vehicle (SUV, Van, Sports Car, Roadster, ...); I use objects for the BRAND (Ford, GM, Fiat, Seat,...) and attributes for the individual models (Fiat 600, Fiat Mirafiori, Fiat 500, etc).

Brand;Type;Model;motor;Model Ref
Fiat;Sports;500;1700;asfdf125
;;500;1900;gagdgd54
;;500;2000;hhheree55
Fiat;Urban;127;1700;dsffsad415
;;127;1900;15545adfs
;;127;2000;855444a
Fiat;Family;131;1700;dafsdf4
;;131;1900;4747a
;;131;2000;4882524a
Fiat;Sedan;Mirafiori;1700;455855b
;;Mirafiori;1900;adsfa445
;;Mirafiori;2000;448554c
Ford;Urban;Fiesta;1350;454545421c
;;Fiesta;1700;asdfa54c
;;Fiesta;1900;4545455c
Ford;Family;Focus;2000;6458484c
;;Focus;2500;aadfsdf4444
;;Focus;1700;adfadf5577
Ford;Sports;Mustang;1700;adssdf4444
;;Mustang;1900;adfasdf444
;;Mustang;2000;adfaasd447785
Ford;SUV;Kuga;1700;bbbb121b
;;Kuga;1900;bbbb122b
;;Kuga;2000;bbb25474c
Fiat;Sports;501;1700;asfdf125
Fiat;Urban;128;1700;dsffsad415

![スクリーンショット 2022-11-19 4 31 36](https://user-images.githubusercontent.com/1954306/202787729-de859c58-d631-4f24-9227-6026790d7c2b.png)

![スクリーンショット 2022-11-19 4 31 52](https://user-images.githubusercontent.com/1954306/202787749-4ecd84c5-ff59-48df-99ae-544c9da77e0a.png)

![スクリーンショット 2022-11-19 4 32 14](https://user-images.githubusercontent.com/1954306/202787760-d04565a5-5a6d-4d05-a28f-0fed2ea897e3.png)

**Comment by ryouchinsa** [comment]
The new update version 71 was released.

- Improved "Import object names file" on Export menu so that it can import projects, objects, and attributes from a CSV file.

Please let us know your opinion.

**Comment by joaourbano** [comment]
Hi,

I am having problems importing the CSV file.

I am using 
Could you please help me by providing a template csv that I could user to import my projects, objects and attributes?\\

Thanks in advance

**Comment by ryouchinsa** [comment]
We can import your attached CSV file using "Import object names from a file" on Export menu.
If you have another CSV file which is not imported correctly, please send to support@rectlabel.com.

![スクリーンショット 2022-12-29 13 17 49](https://user-images.githubusercontent.com/1954306/209902803-efc32701-c217-42f5-a49d-d95424f396d7.png)
![スクリーンショット 2022-12-29 13 17 09](https://user-images.githubusercontent.com/1954306/209902818-5c2acbd3-468d-44ff-a29c-481a0c628d4c.png)
