### ISSUE TITLE
Feature request to scale the rect

### ISSUE THREAD

**Issue by caichunjian520** [ryouchinsa/Rectlabel-support#197]
Is it possible to scale the rect from center point.

In settings, add the default scale, rect zoom in and zoom out factor.

For example, I can tap on the center point of an object, then press hot key to get a rect immediately. Another two hot keys to make the rect larger or smaller.

I have 50000 images been labeled, but recently find all the images' rect are too large that if two objects are too close will get bad result. So I have to shrink the size of rect one by one.

So if RectLabel has this feature will save a lot of time when there are lots of object with the same size in an image.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If you drag on the box pressing option key, the box size is scaled up/down from the center.
Does this work for your use-case?
This feature will be released in the next update.

![scale_box](https://user-images.githubusercontent.com/1954306/164587728-5e6d8915-c99b-472d-9dbe-cf27ce909ae1.gif)

**Comment by caichunjian520** [comment]
Yes, this is the exact feature for my case, I think this will save me a lot of time. Really thanks for your work.

**Comment by ryouchinsa** [comment]
The new update version 37 was released.
To show the new update on Mac App Store, press command + R to reload.

Let us know your opinion.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
