### ISSUE TITLE
different between rectlabel pro and rectlabel for object detection

### ISSUE THREAD

**Issue by JunHyungKang** [ryouchinsa/Rectlabel-support#199]
Is there any difference?
If it is, please add description for that.

In rectlabel pro, is there any way to change box type from rectangle to polygon?

**Comment by ryouchinsa** [comment]
Hi,

We had the feature to change the polygon type from rectangle to polygon in the previous version.
If you need, we will add the feature again.

As shown on the Mac App Store, "RectLabel Pro" is a paid up-front version of RectLabel and fully feature equivalent with "RectLabel for object detection".
https://rectlabel.com/pricing

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
In "RectLabel Pro", you can draw bounding boxes, rotated boxes, polygons, cubic bezier curves, line segments, points, keypoints, and pixels.
If you subscribed to "RectLabel for object detection", you can use the same drawing options as "RectLabel Pro".
If you not subscribed, you can draw only bounding boxes.

By the way, if you need to change the polygon type from rectangle to polygon, now you have right-click menu "to polygon". We hope that this feature is helpful for you.

If you have any other questions, please let us know.

![スクリーンショット 2022-06-13 8 05 22](https://user-images.githubusercontent.com/1954306/173257744-ad726362-4832-4872-95b4-d1c0f510cdec.png)

**Comment by JasSong** [comment]
I have the same issue.
I tried right-click as you suggested when I created box , but the "to polygon" function didn't exist.

https://user-images.githubusercontent.com/26897442/173291011-7accfd32-c856-49aa-88f7-da78b70996f3.mov

**Comment by ryouchinsa** [comment]
In the latest version 43, if you subscribed to a monthly or yearly plan on "RectLabel for object detection" or bought "RectLabel Pro", you can use the "To polygon" right click menu.

If you need to use the polygon feature, please subscribe or buy "RectLabel Pro".
https://rectlabel.com/pricing

![to_polygon](https://user-images.githubusercontent.com/1954306/173339757-73eacebb-0fbb-4621-b73a-d186f3265ab2.gif)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
