### ISSUE TITLE
building oriented bounding boxes

### ISSUE THREAD

**Issue by JunHyungKang** [ryouchinsa/Rectlabel-support#200]
From the description of the app, it seems that drawing oriented bounding boxes is available.
Is there any way to edit angle with horizontal boxes??

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can use the "Rotate" button to rotate the bounding box.
Drag up/down on the box to rotate the box.
https://rectlabel.com/help#rotate_box

If you have any other questions, please let us know.

![oriented_box](https://user-images.githubusercontent.com/1954306/173474375-067ddc55-96f1-467e-8900-e49474de4a9e.gif)

**Comment by JasSong** [comment]
I was already subscribed. The version seems to be the issue(42 version). Thanks for solving the problem :)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
