### ISSUE TITLE
"Images not found" error

### ISSUE THREAD

**Issue by kwseow** [ryouchinsa/Rectlabel-support#201]
Hi there,
I used "Open image folder" and I keep getting an Error message "No images found".  I am on Mac 12.5.1.

Any advice?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Fixed the crash reading the old settings file when launch. 
The new update version 55 was released.

If you have any other problems, please let us know.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
