### ISSUE TITLE
Import object names

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#202]
In the past we could import object names from the xml, however I don't see that option anymore. How can I do this in RectLabel Pro?

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.
If you need, we will restore the "Import objects names from xml files" menu.

In the current version, please export the CSV file and import the CSV file, then new object names are added to objects table.

Let us know your opinion.

**Comment by lonnylundsten** [comment]
"restore the "Import objects names from xml files" menu" -- this makes the most sense to me. I can do it the other way, now that you mention it but Import objects from xml is more intuitive and less steps for the user.

Thank you!

**Comment by ryouchinsa** [comment]
Thanks for your opinion.

We restored "Import object names from xml files" on Export menu.
The new update version 64 was released.

If you have any other requests, please let us know.

![スクリーンショット 2022-10-05 14 26 24](https://user-images.githubusercontent.com/1954306/193987801-cb32cc4e-4f25-46a5-b419-bb7602349c01.png)

**Comment by lonnylundsten** [comment]
Thank you!

**Comment by ryouchinsa** [comment]
If you have any other requests, please let us know.
