### ISSUE TITLE
Object detection model for grocery shelves

### ISSUE THREAD

**Issue by joaourbano** [ryouchinsa/Rectlabel-support#206]
Hi,

First of all, thank you for your great software. 

I am currently annotating a few thousand images of grocery shelves. I have trained an object detection model using Create ML (YoloV2). I use this model with Rectalbel Pro to speed up my annotation process.

I understand that yoloV5 offers quite a few improvements and I would like to train a new model with it. Could you please help me out? Do you have a pre-trained model that I could download and use with RectLabel Pro?

Thank you

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

For the yolov5 models, you can download here, such as yolov5s.pt.
https://github.com/ultralytics/yolov5/releases/tag/v6.2

To convert the .pt model to .coreml model, run the command.
python export.py --weights yolov5s.pt --include coreml
https://github.com/ultralytics/yolov5/issues/251

Then, you can load the yolov5s.coreml on RectLabel, process your images for automatic labeling.
https://rectlabel.com/help#process_images_coreml

Please let us know your opinion.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
