### ISSUE TITLE
Importing object names and attributes - updated

### ISSUE THREAD

**Issue by joaourbano** [ryouchinsa/Rectlabel-support#207]
Hi,

It has been a long time, here goes a sample csv file. Can you help?

Thanks
[sample.csv](https://github.com/ryouchinsa/Rectlabel-support/files/9821738/sample.csv)
[sample.csv](https://github.com/ryouchinsa/Rectlabel-support/files/9821741/sample.csv)

_Originally posted by @joaourbano in https://github.com/ryouchinsa/Rectlabel-support/issues/195#issuecomment-1284175400_

**Comment by ryouchinsa** [comment]
Thanks for the sample .csv file.
We can understand the format from the file.
But, to know the details, do you have some documents about the annotation format?
We want to know which annotation tools or deep learning tools are using the  format.

**Comment by ryouchinsa** [comment]
We implemented to import the CSV file below to projects, objects, and attributes tables.
Are they correct?
Please let us know your opinion.

Brand;Type;Model;motor;Model Ref
Fiat;Sports;500;1700;asfdf125
;;500;1900;gagdgd54
;;500;2000;hhheree55
Fiat;Urban;127;1700;dsffsad415
;;127;1900;15545adfs
;;127;2000;855444a
Fiat;Family;131;1700;dafsdf4
;;131;1900;4747a
;;131;2000;4882524a
Fiat;Sedan;Mirafiori;1700;455855b
;;Mirafiori;1900;adsfa445
;;Mirafiori;2000;448554c
Ford;Urban;Fiesta;1350;454545421c
;;Fiesta;1700;asdfa54c
;;Fiesta;1900;4545455c
Ford;Family;Focus;2000;6458484c
;;Focus;2500;aadfsdf4444
;;Focus;1700;adfadf5577
Ford;Sports;Mustang;1700;adssdf4444
;;Mustang;1900;adfasdf444
;;Mustang;2000;adfaasd447785
Ford;SUV;Kuga;1700;bbbb121b
;;Kuga;1900;bbbb122b
;;Kuga;2000;bbb25474c

![スクリーンショット 2022-11-18 11 31 20](https://user-images.githubusercontent.com/1954306/202604324-2c4dcb5a-03b1-4854-beec-8895923cc1cc.png)
![スクリーンショット 2022-11-18 11 31 23](https://user-images.githubusercontent.com/1954306/202604328-fae8bb13-8d9b-4975-9244-c8517f93da86.png)
![スクリーンショット 2022-11-18 11 31 27](https://user-images.githubusercontent.com/1954306/202604330-a3990bf9-cba7-4eb9-b884-23cc4b9a5af8.png)
![スクリーンショット 2022-11-18 11 31 49](https://user-images.githubusercontent.com/1954306/202604331-0f78fa37-c3c9-480c-b10f-be263d3e60d1.png)
![スクリーンショット 2022-11-18 11 31 52](https://user-images.githubusercontent.com/1954306/202604332-2f2ef642-d427-4c77-8386-e2c2701c7c78.png)
![スクリーンショット 2022-11-18 11 31 56](https://user-images.githubusercontent.com/1954306/202604334-7fe05b6f-b739-4bf1-8e98-3ebc589d99d6.png)
![スクリーンショット 2022-11-18 11 32 05](https://user-images.githubusercontent.com/1954306/202604338-a6e91598-20f4-4aab-909e-8f058b686b05.png)
![スクリーンショット 2022-11-18 11 32 09](https://user-images.githubusercontent.com/1954306/202604340-1ec4ef1b-5585-4894-90e4-15c498d411f1.png)
![スクリーンショット 2022-11-18 11 32 14](https://user-images.githubusercontent.com/1954306/202604341-c4ec002b-2226-45ee-b96f-2317a43e7f6a.png)
![スクリーンショット 2022-11-18 11 32 20](https://user-images.githubusercontent.com/1954306/202604342-16eca61e-d4d4-4fcd-ac78-5f3c32e1c6d0.png)
![スクリーンショット 2022-11-18 11 32 25](https://user-images.githubusercontent.com/1954306/202604345-1e5905f4-c585-4c8c-b65c-5899cc368867.png)
![スクリーンショット 2022-11-18 11 32 29](https://user-images.githubusercontent.com/1954306/202604346-5bd328da-b36b-4746-8a55-937702c6cf07.png)
![スクリーンショット 2022-11-18 11 32 35](https://user-images.githubusercontent.com/1954306/202604348-e67797f6-5b35-4d3c-bcc4-051ac9bcdd9e.png)
![スクリーンショット 2022-11-18 11 32 38](https://user-images.githubusercontent.com/1954306/202604350-1761ca4d-d566-4653-b6d5-9764a8986ec4.png)
![スクリーンショット 2022-11-18 11 32 43](https://user-images.githubusercontent.com/1954306/202604352-fa06c116-4661-47cd-be41-444845f70731.png)

**Comment by ryouchinsa** [comment]
Updated. We implemented to import the CSV file below to projects, objects, and attributes tables.
Are they correct?
Please let us know your opinion.

> In this project I have to label road vehicles according to Type, brand and model. I am currently using a Project for each type of vehicle (SUV, Van, Sports Car, Roadster, ...); I use objects for the BRAND (Ford, GM, Fiat, Seat,...) and attributes for the individual models (Fiat 600, Fiat Mirafiori, Fiat 500, etc).

Brand;Type;Model;motor;Model Ref
Fiat;Sports;500;1700;asfdf125
;;500;1900;gagdgd54
;;500;2000;hhheree55
Fiat;Urban;127;1700;dsffsad415
;;127;1900;15545adfs
;;127;2000;855444a
Fiat;Family;131;1700;dafsdf4
;;131;1900;4747a
;;131;2000;4882524a
Fiat;Sedan;Mirafiori;1700;455855b
;;Mirafiori;1900;adsfa445
;;Mirafiori;2000;448554c
Ford;Urban;Fiesta;1350;454545421c
;;Fiesta;1700;asdfa54c
;;Fiesta;1900;4545455c
Ford;Family;Focus;2000;6458484c
;;Focus;2500;aadfsdf4444
;;Focus;1700;adfadf5577
Ford;Sports;Mustang;1700;adssdf4444
;;Mustang;1900;adfasdf444
;;Mustang;2000;adfaasd447785
Ford;SUV;Kuga;1700;bbbb121b
;;Kuga;1900;bbbb122b
;;Kuga;2000;bbb25474c
Fiat;Sports;501;1700;asfdf125
Fiat;Urban;128;1700;dsffsad415

![スクリーンショット 2022-11-19 4 31 36](https://user-images.githubusercontent.com/1954306/202788307-24ad27b1-ab72-4723-89ee-00afe5220b9a.png)

![スクリーンショット 2022-11-19 4 31 52](https://user-images.githubusercontent.com/1954306/202788312-21fb6463-a295-4c99-ba6f-c8722e329f72.png)

![スクリーンショット 2022-11-19 4 32 14](https://user-images.githubusercontent.com/1954306/202788313-c60a1d9e-f563-4333-9a68-913c9b02497f.png)

**Comment by ryouchinsa** [comment]
The new update version 71 was released.

- Improved "Import object names file" on Export menu so that it can import projects, objects, and attributes from a CSV file.

Please let us know your opinion.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
