### ISSUE TITLE
Sorting bounding boxes by minX or minY Or mouse over to select a bbox

### ISSUE THREAD

**Issue by caichunjian520** [ryouchinsa/Rectlabel-support#208]
If processing image using CoreML, and there are lots of object, is it possible to sort bounding boxes based on its position such as minX or minY. Because I find it is hard to select a bbox I want if all the labels are the same.

I think if there is a hot key to sort xml file contains bounding box info would be good.

Or mouse over on a bounding box and click to select.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

> Or mouse over on a bounding box and click to select.

How about using the "Move" feature on Edit menu and clicking on the box to select?
If this does not work, please tell us the details.

"Hide other boxes" feature on View menu increases the visibility when there are many boxes.

**Comment by caichunjian520** [comment]
This is exact what I expect, thanks!

**Comment by ryouchinsa** [comment]
If you have any other requests, please let us know.
