### ISSUE TITLE
language option

### ISSUE THREAD

**Issue by JunHyungKang** [ryouchinsa/Rectlabel-support#209]
Is there any way to select a language option?
I need to roll back to English default within app.

**Comment by ryouchinsa** [comment]
Thanks for the feature request.
In the next update, we will add "Use English as an app language" option on the settings dialog.

If localized sentences are not accurate for you, please tell us the details.
We will improve our localized sentences.

![スクリーンショット 2022-11-25 8 14 44](https://user-images.githubusercontent.com/1954306/203873277-7b8ce069-88ee-4b36-a68b-37f1a0a6166d.png)

**Comment by ryouchinsa** [comment]
The new update version 72 was released.

- Added "Use English as an app language" option on the settings dialog.

Please let us know your opinion.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
If you have any other requests, please let us know.
