### ISSUE TITLE
Rectangle is not shown 

### ISSUE THREAD

**Issue by cipri-tom** [ryouchinsa/Rectlabel-support#21]
I can create boxes and they are shown in the right panel, but once I accept a box, it is no longer shown on the image. I tried to `focus` or `edit` or `move`  but it just won't show. So I have no idea what I am editing.

MacOS High Sierra

**Comment by ryouchinsa** [comment]
Thanks for reporting the problem.

We have not experienced the problem.

Could you download the test folder below and check if you could reproduce the problem with the folder?
https://github.com/ryouchinsa/Rectlabel-support/tree/master/images_test

**Comment by ryouchinsa** [comment]
Thanks for the screenshot.

1. What happens when you change the box color using color picker at the upper right corner?
2. Push the "Save button" and could you show us the annotation file?
3. Push "File -> Export Settings File" and could you show us the settings file?

**Comment by mpuig** [comment]
I have the same problem since I upgraded to MacOS High Sierra, and also, the next/prev arrows don't follow the correct sequence.

**Comment by ryouchinsa** [comment]
We thought the latest macOS Sierra was the macOS High Sierra.
We would install macOS High Sierra and check the problem soon.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

- Fixed rectangles are not shown on MacOS High Sierra.
- Removed hot key customization because the open source tool "MASShortcut" were unstable on MacOS High Sierra.

**Comment by ryouchinsa** [comment]
RectLabel 1.40 was released.

**Comment by cipri-tom** [comment]
It works. Thank you for the quick action !
