### ISSUE TITLE
Annotating objects and COREML results

### ISSUE THREAD

**Issue by IzzyHibbert** [ryouchinsa/Rectlabel-support#210]
Hi.

My compliments for the product. I am evaluating the trial in order to move to pro.

I am trying to tag some signatures. I have available a model, so I 

1) Connect my model to RectLabel
2) Load one image, and for that one I use my model, which works quite fine detecting one signature (bottom of the page) :

![1st step with COREML](https://user-images.githubusercontent.com/45388237/205484360-fa72915f-d48c-42dc-84f0-88e31a4a5223.png)

3) There are two more signatures - not detected by my model - that I need to tag
4) As soon as I create a rectangle over the signature in the mid of the page, 

![Mid](https://user-images.githubusercontent.com/45388237/205484822-9067ed69-89b1-4cc5-90a9-8f2c945bedd7.png)

then my rectangle disappear and instead seems that the COREML logic applies inside of the region I tried to create, and kind of detect a small portion of an object 

![2nd step](https://user-images.githubusercontent.com/45388237/205484528-900d2581-ae89-47c2-90a3-7153f769a079.png)

The problem is that with this sequence I cannot create my additional objects anymore: as soon as I create a rectangle the COREML runs and either detects something or does not. The only possible alternative is to cancel the COREML model and repeat the steps, all, including creating a new object for the object that was detected anyway correctly by COREML.

The behavior I expected somehow was..
- Add a COREML model
- Open one image
- Apply the model for the image and see results. If FINE save and move on, if KO modify or add regions and move on. It makes no sense to me that I create new object regions and the COREML tries again (first time was when I applied it to the image) to find something, this time inside of the portion I designed.

THANKS A LOT

**Comment by ryouchinsa** [comment]
Thanks for using RectLabel and writing the issue.

We understood the problem and apologize that we decreased your labeling speed.
In the current version, when you loaded a Core ML model, Create Box mode is being used to auto label the cropped area.
This was implemented for segmentation models.

We changed so that for box detection Core ML models, Create Box mode is used for labeling boxes manually.
Today we submitted the new update to Apple.
When the new update is released, we will let you know.

If you have any other requests, please let us know.

![auto_label_box](https://user-images.githubusercontent.com/1954306/205615819-7d9226dc-d83c-4e9c-9e75-adfc39aa6a29.gif)

**Comment by IzzyHibbert** [comment]
@ryouchinsa I downloaded the new version and tested.
It works exactly as expected. Nice work.
I am going to close a couple of tests before the final purchase.

**Comment by IzzyHibbert** [comment]
@ryouchinsa Just one thing.
Could it be possible to also align the PRO version with this, so that I buy it and get the same features on ?
THANKS

**Comment by ryouchinsa** [comment]
Thanks for testing the new update and giving us your feedback.
RectLabel and RectLabel Pro have the same features.
We are updating those 2 apps on the same day, basically. 
If you bought RectLabel Pro, you can use the same features as RectLabel.
If you have any other questions, please let us know.

**Comment by ryouchinsa** [comment]
In the latest version, you can use "Automatic text recognition using OCR" feature on Core ML menu.
Changing the confidence threshold and the language to be recognized, you can adjust the auto labeling results.

We hope this feature will help your labeling work.
Please let us know your opinion.

![ocr](https://user-images.githubusercontent.com/1954306/210030909-f0fe214a-0845-4384-a811-32779583844a.jpg)
