### ISSUE TITLE
Using CoreML models for OCR in images

### ISSUE THREAD

**Issue by Mast3rChief** [ryouchinsa/Rectlabel-support#212]
Hi,

do you have a "best practice" for OCR in RectLabel? Could be bounding box based or segmentation. 

Use Case: I would like to label/detect large letters and ID on assets in my images.

Thanks a lot for your help.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

On RectLabel, you can use a "Text input" attribute for labeling free text.
Also, you can label bounding boxes and rotated bounding boxes.

You have to convert to a format for text detection and text recognition, train the data on a training tool, convert to Core ML model, then you can use the OCR model for auto labeling on RectLabel.

Currently we are reading the MMOCR document.
https://github.com/open-mmlab/mmocr

Which training tool are you going to use?

**Comment by ryouchinsa** [comment]
In the latest version 79, you can use "Automatic text recognition using OCR" feature on Core ML menu.
Changing the confidence threshold and the language to be recognized, you can adjust the auto labeling results.

We hope this feature will help your labeling work.
Please let us know your opinion.

![ocr](https://user-images.githubusercontent.com/1954306/209554434-b9718d0b-d520-4127-b66b-12c2b2a067d0.jpg)

**Comment by Mast3rChief** [comment]
Sorry for the late feedback. Thx…. Works great

**Comment by ryouchinsa** [comment]
If you have any other requests, please let us know.
