### ISSUE TITLE
[MacOs] Dialog box is behind another one.

### ISSUE THREAD

**Issue by ande4485** [ryouchinsa/Rectlabel-support#214]
[BUG]
A dialog box to choose file is behind another one. 

[HOW TO REPRODUCE]
* Click on "opened folder" ( in french it's "Dossier ouvert")
* A dialog box appears with title "Open images folder and annotations folder"
* Click on "+"
* A new row appears in the list.
* Click on "Change" ( or changement in french).
* A dialog box appears to choose a folder behind the other one.

[ENV]
* Mac OS Ventura 13.2
* Version 2023.02.12 (2023.02.12)
<img width="798" alt="Capture d’écran 2023-02-15 à 10 57 02" src="https://user-images.githubusercontent.com/38383248/218995868-33a5e6c3-089d-4658-b786-339c0c0c8f09.png">

**Comment by Denizzje** [comment]
I had the same issue on an older Macbook I was using, due to the small screen space I could no longer select things from the finder properly because the folder selection was in front of it. This window needs a minimalise option. That was on MacOS 12 by the way.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
To fix the problem, we have to reproduce the problem in our environment.

We are using the same macOS version 13.2.
We attached the captured video in our environment.
Could you capture what happens in your environment using QuickTime Player?

![open_folder](https://user-images.githubusercontent.com/1954306/219660718-2ac05ce3-1dc5-4e39-84f4-6eb114fb0b89.gif)

**Comment by ande4485** [comment]
https://user-images.githubusercontent.com/38383248/220071197-de9eb246-c947-4a28-bb7d-451a7200c48b.mov

I forgot it's on free version.

**Comment by ryouchinsa** [comment]
Thanks for sharing the video.
We think some problem happened before pressing the open folder button, so that the UI does not work correctly.
Could you delete cache files and launch RectLabel and check whether the same problem happens or not?
1. Back up the current cache folder. ~/Library/Containers/RectLabel
2. Delete the cache folder, clean up the trash box, and launch RectLabel.

**Comment by ryouchinsa** [comment]
Thanks for the feedback.
Is this problem continuing since you started using RectLabel?
Or, at a time, suddenly this problem started to happen?

**Comment by ande4485** [comment]
@ryouchinsa it was always like that.

**Comment by ryouchinsa** [comment]
We will improve our code so that certainly the open folder dialog should be shown over the open images and annotations dialog.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
Fixed so that when you press the change button, the open folder dialog is shown in front of the current dialog.
The new version 2023.02.27 was released.
Please let us know your feedback.

**Comment by ande4485** [comment]
It works with the new version 2023.02.27

**Comment by ryouchinsa** [comment]
Thanks for your feedback. If you have any other problems, please let us know.
