### ISSUE TITLE
why need merge_multi_segment?

### ISSUE THREAD

**Issue by lyf6** [ryouchinsa/Rectlabel-support#216]

**Comment by ryouchinsa** [comment]
When the object is occluded, multiple polygons are necessary to label the polygon mask.

![yolo_polygon](https://user-images.githubusercontent.com/1954306/214472214-a9c2775d-247a-4bd1-87f6-9d90818ef8ff.jpg)

Please read this issue.
https://github.com/ultralytics/ultralytics/issues/979

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
