### ISSUE TITLE
Arrow image navigation

### ISSUE THREAD

**Issue by joaquinperaza** [ryouchinsa/Rectlabel-support#22]
As title says it would be great to just use arrows while navigating.

**Comment by ryouchinsa** [comment]
Changed the shortcuts for "Next Image" and "Prev Image" from ctrl + arrow to arrow.

![2017-10-05 3 12 23](https://user-images.githubusercontent.com/1954306/31192649-cb41e738-a97c-11e7-8fbd-00bfe77e6e6c.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by joaquinperaza** [comment]
Thanks for your fast response!

**Comment by ryouchinsa** [comment]
RectLabel 1.41 was released.
