### ISSUE TITLE
unable to click on label name buttons to change label of a polygon

### ISSUE THREAD

**Issue by hqm** [ryouchinsa/Rectlabel-support#220]
Problem: after drawing a polygon and double clicking on it to change its label, a dialog with all  label name buttons come up, but I am unable to click on any of the buttons to change the label. 

I can change the label by typing first letters of a label, or using mouse down to get a list menu. But the label name buttons  themselves do not change the label for the polygon.

See attached quicktime movie

https://user-images.githubusercontent.com/1862/227414426-ff7d14a7-92ee-4623-bb38-619154454ff0.mp4

**Comment by ryouchinsa** [comment]
Thanks for writing the issue and attaching the detailed video.

We are sorry for late reply.
We were working for the update of erasing polygon feature.

In the latest version, the problem when you press the 1-click buttons was solved.
Please let us know you feedback.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
