### ISSUE TITLE
Export mask images

### ISSUE THREAD

**Issue by chaewonS** [ryouchinsa/Rectlabel-support#223]
I tried opening the color mask image using the code below.
`originalFormat = np.array(Image.open(f))`

And I checked that the pixel value of the image is indexed by the class id.
if it is a person, all of them are output as 25, but I want to distinguish each person (for example, 25000, 25001, 25002)
Is there any solution?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

For the semantic segmention, the indexed color mask image is exported, and each pixel value is defined by the object id. If there are multiple person objecs in the image, all pixel values in those persons have the same pixel value defined by the object id.
For the instance segmentation, use "Export an image per object" option. If there are multiple persons in the image, for each person, each grayscale mask image is exported.

If you have any questions, please let us know.

**Comment by chaewonS** [comment]
Thanks for the answer!e
Where can I use "Export an image per object" option?

**Comment by ryouchinsa** [comment]
You can choose on the Export -> Export mask images menu.

![スクリーンショット 2023-05-17 15 59 28](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/e205e704-16c8-4782-9a06-72f1efbeffa2)
