### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by chaewonS** [ryouchinsa/Rectlabel-support#228]
If labels overlap, how are they displayed in json?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Please let us know which JSON format you are mentioning.
Basically each label is separately exported.

**Comment by chaewonS** [comment]
Thanks for the reply.
I wonder how the duplicated label is displayed in the json format of "export mask images" -> "all Images".

**Comment by ryouchinsa** [comment]
Thanks for the details. We understood what you meant.

The layer order determines the overlay when export.

![layer_order](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/c3e93b99-86b2-4715-9017-f2353ca14524)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
