### ISSUE TITLE
Allow auto save function

### ISSUE THREAD

**Issue by joaquinperaza** [ryouchinsa/Rectlabel-support#23]
Allow to enable an autosave function to save every annotation we make or modify automatically.

**Comment by ryouchinsa** [comment]
Added "Auto Save" on the settings dialog.
Checking the checkbox, we will not show the confirm dialog when you change the image.

![2017-10-05 3 12 13](https://user-images.githubusercontent.com/1954306/31192695-f023bc16-a97c-11e7-91eb-a44785534728.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by joaquinperaza** [comment]
Great! Thanks a lot!

**Comment by ryouchinsa** [comment]
RectLabel 1.41 was released.
