### ISSUE TITLE
Batch load COCO JSON

### ISSUE THREAD

**Issue by alelordelo** [ryouchinsa/Rectlabel-support#230]
Hi,

How can I batch load thousands of COCO JSON files?

I tried:

- File -> import 
Cannot multiple select files

- Drag into annotation and image folders
the JSOn annotations are not loaded into the images

thanks!

**Comment by ryouchinsa** [comment]
We will improve the "Import COCO RLE JSON files" to import the usual COCO JSON files.
Each JSON file name should be the same as image file name.
image.jpg -> image.json, etc.

**Comment by ryouchinsa** [comment]
- Improved so that you can drag & drop the COCO JSON file to the labels table.
- Improved so that "Import COCO JSON per image files" can import per image COCO JSON files.

The new version 2023.07.05 was released.
Please let us know your opinion.

**Comment by rromanchuk** [comment]
@ryouchinsa  This is a really dumb question i'm embarrassed to ask, i've just been using bash and `jq` to pre-process but it's super annoying and i want to be lazy. 

How do you import a coco json file that has `file_name`s that have RIDICULOUSLY nested file paths? Painfully nested. I need something like  `-r ./images && ./images/annotations` so i can do a clean import in one shot.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We think this question is about how to import the COCO format when images are in multiple folders.
Before importing, you have to open multiple images/annotations folder.

For the "file_name" in the "images" array in the COCO format, if opened_images_folder_i + "file_name" exists, the annotation is imported and saved in the opened_annotations_folder_i.

If the "file_name" is "subpath/1.jpg", we check both opened_images_folder_i + "1.jpg" and opened_images_folder_i + "subpath/1.jpg".

If this algorithm does not satisfy with your use-case, please show us the detailed folder structure and the "file_name" in your COCO file.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
