### ISSUE TITLE
Export RGB images

### ISSUE THREAD

**Issue by chaewonS** [ryouchinsa/Rectlabel-support#233]
First of all, RectLabel is a really cool tool!
And I have a question about the result exported to RectLabel.

When I checked the pixels with "Export Screenshots", the RGB values were the colors of the original image.
But, I want an image with color RGB values that I specified in the settings as color attribute.
I would like to know if there is any way.

Thank you!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

When export, for pixels objects, each color is set according to the object color on the settings dialog.
If there are any problems, please let us know.

![wembley-S3Vq97p3gSk-unsplash_labels](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/6037cc02-ba9d-4fe4-a06f-e58ff4e8d0e6)
![スクリーンショット 2023-09-16 2 08 06](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/25178cdc-6d59-4d18-977e-960663ad3104)
