### ISSUE TITLE
Unable to open images

### ISSUE THREAD

**Issue by darhsu** [ryouchinsa/Rectlabel-support#235]
I am unable to Open images folder and annotations folder. I'm running Version 2023.07.05 (2023.07.05)

Here is my folder structure:
<img width="747" alt="Screenshot 2023-08-25 at 12 08 17 PM" src="https://github.com/ryouchinsa/Rectlabel-support/assets/35377472/6bcf5d08-5995-40ef-a17c-9a87cc8990f2">

Here the RectLabel popup:
<img width="653" alt="Screenshot 2023-08-25 at 12 09 15 PM" src="https://github.com/ryouchinsa/Rectlabel-support/assets/35377472/3fe98996-da3c-49eb-9980-16a82f907a9b">

Here is my error message:
<img width="492" alt="Screenshot 2023-08-25 at 12 10 26 PM" src="https://github.com/ryouchinsa/Rectlabel-support/assets/35377472/d226d867-54dd-4817-a6e6-c65eac35d405">

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Could you check the folder permission so that RectLabel can read/write?

Otherwise, If you recreated the same named folder, you have to open the folder again from the panel.

**Comment by darhsu** [comment]
It seems like all the folders and files have read/write permission. I've also tried reinstalling RectLabel too

```
(base) darren@Darrens-MBP Downloads % ls -ld Rectlabel                 
drwxrwxrwx@ 5 darren  staff  160 Aug 26 09:34 Rectlabel

(base) darren@Darrens-MBP Downloads % ls -ld Rectlabel/images          
drwxrwxrwx@ 3 darren  staff  96 Aug 26 09:37 Rectlabel/images

(base) darren@Darrens-MBP Downloads % ls -ld Rectlabel/images/u9jjk.jpg
-rw-rw-rw-@ 1 darren  staff  521478 Jul 18 11:11 Rectlabel/images/u9jjk.jpg

(base) darren@Darrens-MBP Downloads % ls -ld Rectlabel/annotations     
drwxrwxrwx@ 3 darren  staff  96 Aug 26 09:35 Rectlabel/annotations

(base) darren@Darrens-MBP Downloads % ls -ld Rectlabel/annotations/u9jjk.txt 
-rw-rw-rw-  1 darren  staff  0 Aug 26 09:35 Rectlabel/annotations/u9jjk.txt
```

**Comment by ryouchinsa** [comment]
Thanks for the detailed feedback.

According to the error message, the images folder or annotations folder is staled.
The bookmarked resource is moved or renamed within a directory that your app already has permission to access.
What happens if you re-open the images and annotations folder?
https://stackoverflow.com/questions/23954662/what-is-the-correct-way-to-handle-stale-nsurl-bookmarks

**Comment by darhsu** [comment]
>What happens if you re-open the images and annotations folder?

Can you clarify you mean by reopening the images and annotations folder?


Also, I've granted RectLabel full disk access to and I am still getting the same "cannot open bookmark to the folder" error. 
<img width="484" alt="Screenshot 2023-09-01 at 10 38 12 PM" src="https://github.com/ryouchinsa/Rectlabel-support/assets/35377472/140cb919-be40-4072-a151-8c9ce492802c">

**Comment by ryouchinsa** [comment]
Thanks for the detailed information.

Using the change button, please select the same directory for images and annotations again.
When you select each directory, RectLabel can regenerate the access permission to the folder.

![reopen](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/98b706c3-9959-4775-9034-e84632c99a45)

**Comment by ryouchinsa** [comment]
Here is a sample images folder and annotations folder.
https://github.com/ryouchinsa/Rectlabel-support/tree/master/sample

If you download this sample folder on your download folder or on another directory such as home directory, does RectLabel show the error message when open those folders?

**Comment by darhsu** [comment]
Hey, thanks for the help. I have followed your instructions but it still did not work. 

Instead, I wiped my MacBook and it works now!

**Comment by ryouchinsa** [comment]
Thanks for the detailed feedback.

According to your feedback, for the permission issue, deleting cache files might work.
https://rectlabel.com/help#troubleshooting

- The cache files path is one of the paths below.
~/Library/Containers/RectLabel
~/Library/Containers/com.waysify.roi
~/Library/Containers/com.waysify.roi.vpp
- Backup the settings file "the_cache_files_path/Data/settings_labels.json".
- Delete the cache files.
- Clean up the trash box and launch RectLabel.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
