### ISSUE TITLE
Multiple CoreML application

### ISSUE THREAD

**Issue by TheCodingHornet** [ryouchinsa/Rectlabel-support#237]
When you use a CoreML model, it will remove all previous labels you draw or you find with another model.
It could be interesting to add a checkbox : 
"Would you want to clean / remove old labels ?"
Yes : Good, same as now
No : Ok, we will merge old and new (nevermind if you have multiple label for same figure)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue. We are sorry for late reply. 

The new version 2023.10.09 was released.
As default, when you run a Core ML model to all images, new labels are added to the existing labels.
On the settings, if you check on the "Clear existing labels when auto label all images" checkbox, you can clear the existing labels when you run a Core ML model.

Please let us know your opinion.

![スクリーンショット 2023-10-09 9 26 30](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/63bd3055-36f0-4e5c-a4d7-d72d5dd8a14f)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
