### ISSUE TITLE
yolov8 text import not working correctly

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#239]
When importing labels from ultralytics yolov8, the localizations are now appearing as lines. I've tested the yolov8 output from Mac's using CPU and MPS and, also, a T100 GPU on Google Colab and the import is the same -- lines instead of boxes. I have not tried importing from yolov5 output.

I've attached an example of the imported yolo file in rectlabel, a close-up showing the line, and a saved image from yolov8.

 
<img width="320" alt="Screenshot 2023-09-14 at 2 39 28 PM" src="https://github.com/ryouchinsa/Rectlabel-support/assets/32526132/99e2922b-be5c-4760-92fd-f4b7a29cb34e">

<img width="387" alt="Screenshot 2023-09-14 at 2 42 46 PM" src="https://github.com/ryouchinsa/Rectlabel-support/assets/32526132/219438ef-b152-4ffa-b775-2425ac81a0fb">

![images-1](https://github.com/ryouchinsa/Rectlabel-support/assets/32526132/58d2e3c3-684b-4c87-84ce-3294efb45d39)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Predicting bounding boxes in images or an video, labels folder is generated.
```
yolo predict model=best.pt save_txt=True source='/Users/ryo/rcam/test_annotations/test/_test_min_pixels/images'
yolo predict model=yolov8n.pt save_txt=True source='Pexels Videos 4800.mp4'
```

![スクリーンショット 2023-09-19 12 57 37](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/fc98c86d-90fc-4e0c-9970-508bb54fb42d)

When YOLO mode, we can open the labels folder and the annotations are shown correctly.
When XML mode, we can import the labels folder and convert to the XML format, and the annotations are shown correctly.

To reproduce the problem, could you show us the image and YOLO text file?
We can debug in our environment.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
We could reproduce the problem with the save_conf option.
`yolo predict model=best.pt save_txt save_conf source='/Users/ryo/rcam/test_annotations/test/_test_min_pixels/images'`

**Comment by ryouchinsa** [comment]
The new version 2023.09.27 was released.

RectLabel can read YOLO bbox format and the confidence value.
```
2 0.858291 0.444129 0.107388 0.13604 0.879111
2 0.923084 0.762919 0.0915834 0.119568 0.816483
1 0.461847 0.497682 0.401854 0.232201 0.745329
2 0.623991 0.857444 0.124704 0.115432 0.700138
2 0.471908 0.719623 0.0527512 0.0871587 0.254708
```

In the next update, the confidence value is shown on each box.

![スクリーンショット 2023-09-28 8 38 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/e806b8c2-0cb5-49ff-951b-d80efe9d2919)

**Comment by ryouchinsa** [comment]
The new version 2023.10.09 was released.

- Improved so that when run Core ML model, confidence values are saved in the YOLO format and shown using "Show labels on boxes" feature.

Please let us know your opinion.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
