### ISSUE TITLE
Move annotated images

### ISSUE THREAD

**Issue by joaquinperaza** [ryouchinsa/Rectlabel-support#24]
It would be useful to have a prefix or re-locate tagged images to a different folder so i dont have to check which images are ready to train the model.

**Comment by ryouchinsa** [comment]
Is it the same as https://github.com/ryouchinsa/Rectlabel-support/issues/16 ?
Pressing ctrl + delete, you can move the image to the deleted folder which we create.
So that images which are ready to train remain in the original folder.

**Comment by joaquinperaza** [comment]
yes, but when you discard lot of images is not so practical

**Comment by ryouchinsa** [comment]
> Sometimes in the train corpus, we can see the same image twice or an image that we do not want to label (since it has nothing to do here). So we need to delete it.

This is the use case to move images in https://github.com/ryouchinsa/Rectlabel-support/issues/16.

> It would be useful to have a prefix or re-locate tagged images to a different folder

This is your use case.
Could you tell us the details of your use case and how to implement it?
Usually all images with annotations would be ready to train.

**Comment by ryouchinsa** [comment]
Added "Move image" and removed "Delete image". You can specify both images folder and annotations folder.

![sc2](https://user-images.githubusercontent.com/1954306/45324796-2d9a4780-b58a-11e8-8fd8-61540314b6d3.png)

The new update version 2.09 was released.

**Comment by ryouchinsa** [comment]
In the latest version 2024.06.18, we added "Create memo" feature on Edit menus. You can add text memo to each image and can be used for searching. This feature works for the PASCAL VOC xml format.

1. Create memo as "training" for images ready to train.
2. Search "training" to show only images ready to train.
3. Copy/Move images to different folder.

![memo2](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/d8c7eca5-7f40-46c4-bc5f-d5f341448565)
