### ISSUE TITLE
Exporting Yolo includes 6th column with confidence score I would assume, can we turn this off?

### ISSUE THREAD

**Issue by zoomphoto** [ryouchinsa/Rectlabel-support#240]
Firstly, this app is amazing!  I left a review which I never do, this has already saved me hundreds of hours of time.

I have 2100 images in a folder, and I imported a CoreML model to pre-annotate my images, and see where I can make adjustments and re-export as Yolo folders train/val.  Everything works perfectly, but for the detections done by the CoreML, there is a 6th column in the .txt yolo file which I assume is the confidence score. 

I wrote a really quick python script to remove the column if it exists, but is there a setting somewhere I am missing?  It would be nice to have this extra column just not exported.

`
  import os
  
  def remove_specific_column_in_txt_files(folder_path, column_index_to_remove=5):
      for filename in os.listdir(folder_path):
          if filename.endswith('.txt'):
              filepath = os.path.join(folder_path, filename)
              
              with open(filepath, 'r') as file:
                  lines = file.readlines()
  
              new_lines = []
              for line in lines:
                  elements = line.strip().split()
                  if len(elements) > column_index_to_remove:
                      del elements[column_index_to_remove]
                  new_line = ' '.join(elements)
                  new_lines.append(new_line)
              
              with open(filepath, 'w') as file:
                  file.write('\n'.join(new_lines))
  
  if __name__ == "__main__":
      folder_path = "/Volumes/4tb_nvme/2023-10-24_2_bibs/train/labels"
      remove_specific_column_in_txt_files(folder_path)
` 
    
    
 Thank you again for this awesome app... I can't believe it took me to long to find, and I think of all the wasted hours on much worse systems!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue and thanks for writing a great review on Mac App Store.

In the latest version 2023.11.01, as default, the YOLO confidence scores are not saved.
If you need to save the confidence scores, please check on the "Save confidence values when YOLO format" checkbox.

We need to increase our revenue. If you have any great ideas, please share with us.

![スクリーンショット 2023-11-01 8 37 13](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/5ffef4a7-1ee4-4aee-b5c9-9d6ba8d366ce)

**Comment by zoomphoto** [comment]
I would say charge more.  ;). $25USD is very low price for this awesome app.  Even if that would hit my own wallet!

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
