### ISSUE TITLE
Getting no label file with if ann['iscrowd']: continue statement.

### ISSUE THREAD

**Issue by mimansa1907** [ryouchinsa/Rectlabel-support#241]
I am trying to convert the COCO1.0 annotation files generated in CVAT to Yolo format. The COCO json file created consists of segmentation masks in RLE format therefore 'iscrowd' variable is True across all annotations. Based on the code given in the function `convert_coco_json`, the  statement  `if ann['iscrowd']: continue` will skip the rest of the code of for loop statement in `for ann in anns:`. I commented the `if` condition and after that I am able to create text files, so what is exactly the purpose of this if statement in the function.

Code Snippet :
```
for ann in anns:
                if ann['iscrowd']:  **## Significance of this statement?**
                   continue
                # The COCO box format is [top left x, top left y, width, height]
                box = np.array(ann['bbox'], dtype=np.float64)
                box[:2] += box[2:] / 2  # xy top-left corner to center
                box[[0, 2]] /= w  # normalize x
                box[[1, 3]] /= h  # normalize y
                if box[2] <= 0 or box[3] <= 0:  # if w <= 0 and h <= 0
                    continue

                cls = coco80[ann['category_id'] - 1] if cls91to80 else ann['category_id'] - 1  # class
                box = [cls] + box.tolist()
                if box not in bboxes:
                    bboxes.append(box)
                if use_segments:
                    if len(ann['segmentation']) == 0:
                        segments.append([])
                        continue
                    if isinstance(ann['segmentation'], dict):
                        ann['segmentation'] = rle2polygon(ann['segmentation'])
                    if len(ann['segmentation']) > 1:
                        s = merge_multi_segment(ann['segmentation'])
                        s = (np.concatenate(s, axis=0) / np.array([w, h])).reshape(-1).tolist()
                    else:
                        s = [j for i in ann['segmentation'] for j in i]  # all segments concatenated
                        s = (np.array(s).reshape(-1, 2) / np.array([w, h])).reshape(-1).tolist()
                    s = [cls] + s
                    if s not in segments:
                        segments.append(s)
                if use_keypoints:
                    k = (np.array(ann['keypoints']).reshape(-1, 3) / np.array([w, h, 1])).reshape(-1).tolist()
                    k = box + k
                    keypoints.append(k)
```

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
As you said, `if ann['iscrowd']: continue` should be commented out.

We updated our [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py) script and we confirmed that the RLE mask with `"iscrowd": 1 `is converted to YOLO segmentation format correctly.

![スクリーンショット 2023-11-22 1 54 51](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/3c5620c0-f85e-47c9-b886-25f864c40aa9)

In this update, the RLE mask with holes can be converted to the YOLO segmentation format correctly.
We hope this script would help your business.

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by ryouchinsa** [comment]
A user told us that converting RLE masks with "iscrowd": 1 to YOLO format might decrease the segmentation accuracy,
https://github.com/ultralytics/JSON2YOLO/issues/38#issuecomment-2013148445

We added skip_iscrowd_1 flag to the `convert_coco_json()` function in the [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py) script.
Please give us your feedback.

Set skip_iscrowd_1=True.

![スクリーンショット 2024-03-30 1 06 06](https://github.com/ultralytics/JSON2YOLO/assets/1954306/6bc5c44b-f18c-4797-b68b-b4f9ddae3df1)

Set skip_iscrowd_1=False.

![スクリーンショット 2024-03-30 1 06 44](https://github.com/ultralytics/JSON2YOLO/assets/1954306/a142e3a7-0d6e-4c55-9df9-6a5e0d486c41)
