### ISSUE TITLE
下载Sam失败

### ISSUE THREAD

**Issue by maqiangThunder** [ryouchinsa/Rectlabel-support#242]

**Comment by ryouchinsa** [comment]
You can manually download the sam model.

https://huggingface.co/rectlabel/segment-anything-onnx-models/blob/main/sam_vit_l_0b3195.zip

Unzip the file and put into RectLabel's models folder.

RectLabel
~/Library/Containers/com.waysify.roi/Data/models

RectLabel Pro
~/Library/Containers/com.waysify.roi.vpp/Data/models

Currently If you need our support to fix this problem, please let us know.
