### ISSUE TITLE
[Video] can't create images

### ISSUE THREAD

**Issue by ande4485** [ryouchinsa/Rectlabel-support#244]
I think it's a regression, but I can't export video in multiples images on version "Version 2023.12.08 (2023.12.08)" on Mac.
[Step to reproduce]
* click on Folder > convert images from video
* select a video
* select a folder for output
* click convert
* A message appears "Operation done"
* Enter in your output folder and there's nothing 

My Rectlabel isn't in english so may be some descriptions aren't the same.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Could you provide me the sample video file which cannot be converted on RectLabel?

**Comment by ande4485** [comment]
Sorry because my video file seems to have a problem, because quickTime can't read it but on Google Drive I can. But may be if you have time, you can display an error message instead of "operation done" ?

**Comment by ryouchinsa** [comment]
If the video file name has a problem, could you tell me the file name? I want to reproduce the problem in my environment. I will check showing the error message.

**Comment by ande4485** [comment]
https://github.com/ryouchinsa/Rectlabel-support/assets/38383248/de518cb5-187c-4392-9dc3-0c998d75927e

This is the video

**Comment by ryouchinsa** [comment]
Using ffmpeg, you can convert  the vp9 codec to h264 codec.
Then, RectLabel can convert the h264 video file to image frames.

`ffmpeg -i 290499344-de518cb5-187c-4392-9dc3-0c998d75927e.mp4 -codec:v h264 290499344-de518cb5-187c-4392-9dc3-0c998d75927e_h264.mp4
`

**Comment by ande4485** [comment]
Ok thank you.
