### ISSUE TITLE
coco2yolo error

### ISSUE THREAD

**Issue by QYY66666** [ryouchinsa/Rectlabel-support#246]
Annotations E:\PyCode\JSON2YOLO-master\datasets\coco\annotations\coco.json:   0%|          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\PyCode\JSON2YOLO-master\123.py", line 543, in <module>
    convert_coco_json('datasets/coco/annotations',  # directory with *.json
  File "E:\PyCode\JSON2YOLO-master\123.py", line 325, in convert_coco_json
    with open((fn / f).with_suffix('.txt'), 'a') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'new_dir\\labels\\coco\\JPEGImages\\0.txt'

I only have coco.json and some images, but no txt. Json file was transferd by labelme's json.
[coco.json](https://github.com/ryouchinsa/Rectlabel-support/files/13719938/coco.json)
Here is my json. Thank you~

**Comment by QYY66666** [comment]
![1](https://github.com/ryouchinsa/Rectlabel-support/assets/153831562/5bb3cc6c-7a7b-4f63-b074-d1897a85d1bc)
![2](https://github.com/ryouchinsa/Rectlabel-support/assets/153831562/03e379bd-c65e-441d-bd7b-95f26de20e99)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In my environment, the coco file is converted to YOLO segmentation format correctly.
Currently If you need our support to fix this problem, please let us know.


![スクリーンショット 2024-01-23 23 07 07](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/add2dc15-5709-464b-8286-a81dfebabbf8)
