### ISSUE TITLE
Problems with creating polygon with SAM using geo TIF files

### ISSUE THREAD

**Issue by joaourbano** [ryouchinsa/Rectlabel-support#248]
Hi,

I am trying to use some with geo TIF files.  The geo TIF files load without problems and are correctly displayed in Rectlabel, however when I click on 'start' on the 'Create Polygon with SAM' window I get the message "Preprocessing failed".

Can you help?

Thanks in advance

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We apologize for your inconvenience. If you could send the geo TIFF file to us, we can debug the reason why the image file does not work on RectLabel SAM feature.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
