### ISSUE TITLE
how to save SAM label

### ISSUE THREAD

**Issue by haozhen315** [ryouchinsa/Rectlabel-support#252]
i have used SAM to label 100 images, after each labelling i click save, but when i finished i found there is empty label in each labelling file!!!!
```

<annotation>
    <folder>Label</folder>
    <filename>30656645_0.png</filename>
    <size>
        <width>2514</width>
        <height>1196</height>
        <depth>3</depth>
    </size>
</annotation>
```

**Comment by ryouchinsa** [comment]
Thanks for using RectLabel and writing the issue.

In the "Create polygon using SAM" mode, after clicking points to draw each object shape, you have to press an enter key and select the object name. Then, you can save annotations.

Before pressing an enter key.

![スクリーンショット 2024-03-21 14 12 24](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/9678afdf-7aad-4234-b066-d652cdd48b4d)

After pressing an enter key.

![スクリーンショット 2024-03-21 14 12 35](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/7ea53f81-4516-4e38-890d-9b13cd60e3ed)

**Comment by haozhen315** [comment]
thank you very much, it is very helpful!

**Comment by haozhen315** [comment]
thank you very much, it is very helpful!

**Comment by ryouchinsa** [comment]
Thanks for your feedback. If you encountered any other problems, please let us know.
