### ISSUE TITLE
how to show label again after moving files

### ISSUE THREAD

**Issue by haozhencop1** [ryouchinsa/Rectlabel-support#254]
i found after i moved files to a different folder, though i correctly set the label dir and img dir, the previously labelled xml information cannot be rightly shown on the img as before.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you record the screen to reproduce the problem in our environment?
https://support.apple.com/en-us/102618

In our environment, for the COCO 5000 validation dataset, when we move the image/annotation one by one, RectLabel shows annotations correctly.

![move_images](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/be1395d0-096e-4824-803a-52ca0d0c8ebe)

**Comment by haozhencop1** [comment]
i use python shutil.move(file, dst) function to move input pngs files from folder A to folder B, then i found some labels are wrong so i open folder B and the same label dir as before to correct, now i can see that the sofeware "know" i previously labelled them, and there is label name on the right panel, but i found in the label dir, all my labelling has become empty, with the label png mask became all zero, i have lost my label for 500 imgs, this is such an awful experience.

**Comment by haozhencop1** [comment]
<img width="1141" alt="image" src="https://github.com/ryouchinsa/Rectlabel-support/assets/165232771/8a2f7ea2-c58e-43fe-955f-49e4a79edb9e">
<img width="484" alt="image" src="https://github.com/ryouchinsa/Rectlabel-support/assets/165232771/91c27f8d-0ae6-47bb-985a-8a4878ed2a7e">

**Comment by haozhencop1** [comment]
i found it was my mistake, my code for moving file was wrong

**Comment by ryouchinsa** [comment]
Thanks for your detailed feedback and showing us your sample images.

We understood that you are labeling images about Normalized Difference Water Index) using the pixels tool.
The pixels file is saved as {image_file_name}_pixels{pixels_idx}.png in the annotations folder.
So if you copy/move annotations, please copy both the xml file and the png file.

If you published some papers, please let us know.
We have to study use-cases of RectLabel.

Best regards,
Ryo
