### ISSUE TITLE
Create folder error

### ISSUE THREAD

**Issue by dhu5-utk** [ryouchinsa/Rectlabel-support#255]
Keep receiving this error when opening the app.
<img width="421" alt="image" src="https://github.com/ryouchinsa/Rectlabel-support/assets/29313094/2105675e-c93e-48d6-b653-8eaa71ba896e">

**Comment by ryouchinsa** [comment]
The new version 2024.04.23 was released.
Please try the latest version.

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
