### ISSUE TITLE
Earlier version of app for macOS 10.12

### ISSUE THREAD

**Issue by gomba999** [ryouchinsa/Rectlabel-support#26]
Hi,

I'd like to ask you if it would be possible for me to download a previous version which is compatible with my OSX version (10.12)? As I've seen version 1.35 would be just fine for me.

Thanks,
Peter

**Comment by ryouchinsa** [comment]
Could you tell us which feature is not working for your OS X version 10.12?

**Comment by gomba999** [comment]
I can't download a previous version (1.35) from the App Store, just the current version (1.41), which isn't compatible with OSX 10.12, it would need OSX 10.13.

**Comment by ryouchinsa** [comment]
Thanks for reporting the problem.
We added support for OS X 10.12 by "macOS Deployment Target 10.12".

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
RectLabel 1.42 was released.
Now you can download RectLabel onto your OS X 10.12.

**Comment by eren-aydemir** [comment]
I am using OSX 10.11 can't download without updating my system. Is there a way to download previous versions? AppStore does not allow.

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.
We added 10.11 to the deployment target of our app.

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

Hopefully it would work.

**Comment by ryouchinsa** [comment]
RectLabel 1.54 was released.
You can download RectLabel onto OS X 10.11.
