### ISSUE TITLE
SAM Start button keyboard shortcut

### ISSUE THREAD

**Issue by aronhoff** [ryouchinsa/Rectlabel-support#265]
Hey,
When you are creating polygons using SAM, you have a popup window where you can choose the model, etc, and then you can press the Start button to preprocess the image.
As it is, I have to press it using the cursor for every image. Perhaps I'm missing something, but I haven't been able to find a keyboard shortcut.
Could you please add a shortcut (or point out what it is if it exists) so that I don't need to move the cursor that much for every image?

Thanks for the useful tool!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In the latest version 2024.09.20, we added hotkeys of "Copy as erase mask", "Cut using erase mask", and "Start SAM preprocessing".

![hotkeys_edit](https://github.com/user-attachments/assets/1ff91f0b-b0bc-4acf-986d-ded1ab7d430b)

![hotkeys_settings](https://github.com/user-attachments/assets/20ffdb5f-e40a-4f91-ab55-ead2d0a96397)

**Comment by aronhoff** [comment]
Thanks for that!
