### ISSUE TITLE
Currently Cannot Import COCO Json File

### ISSUE THREAD

**Issue by ajenez** [ryouchinsa/Rectlabel-support#266]
Currently seeing this error every time I try to import a coco json file. Makes that feature unusable. I have closed the app and restarted.

<img width="384" alt="Screenshot 2024-09-20 at 11 01 21 AM" src="https://github.com/user-attachments/assets/5a4bb326-5eab-4d97-9dcd-d71272bffcb3">

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In our environment, using the importing a coco json file feature, [instances_val2017.json](https://cocodataset.org/#download) can be imported.

Could you show us the sample COCO JSON file to reproduce the problem?

**Comment by rromanchuk** [comment]
(on  macos 15.0 (24A335), but has been no issue Betas through RC)

**Comment by rromanchuk** [comment]
@ryouchinsa i just needed to restart 🤣

**Comment by ajenez** [comment]
@ryouchinsa In my case it continues to happen after restart and after clearing the cache files as you mentioned above. It also happens when trying to "replace labels". Also to be clear I can't ever select a file to import. The error shows up after I pick a folder to put the backup labels. I'm not on macos 15 yet so I'll try updating there and see if anything improves.

**Comment by ryouchinsa** [comment]
To fix the problem, in the current version, File -> Move/Copy images, change the folder for "Output images folder", then import COCO or process all images using a Core ML model.
The point is, when backup, only annotations folder is necessary, but as a bug, both folders are needed to be set up to complete the backup process.

We submitted the new update version  2024.09.28 to Apple.
When the new update is released, we will let you know.

We apologize for your inconvenience.

**Comment by ryouchinsa** [comment]
In the latest version 2024.10.06, the problem of showing the "cannot get url from bookmark" message when backup was solved.
