### ISSUE TITLE
Can Rectlabel export mask as jpg/png?

### ISSUE THREAD

**Issue by willweimike** [ryouchinsa/Rectlabel-support#268]
Hello, I have a question
Can Rectlabel export mask as jpg/png?

I want to do semantic segmentation in UNet, so I need mask to be jpg/png
Thank you.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Please use Export menu -> Export mask images.
If you train a semantic segmentation model, check on the "Export an image per object class" checkbox.
https://rectlabel.com/export/#export-mask-images

A labeled image.

![coco_image](https://github.com/user-attachments/assets/6c999ade-9add-4778-9999-0a7745bfcf2e)

Export an image includes all objects: An indexed color image which includes all objects is saved as {image_file_name}_all_objects.png.

![000000000139_all_objects](https://github.com/user-attachments/assets/5b097dfc-5555-4935-b39b-921034d50d90)

Export an image per object class: A grayscale image per object class is saved as {image_file_name}class{class_name}.png.

![000000000139_class_chair](https://github.com/user-attachments/assets/3b588273-f5e6-4da0-aa55-8895d0acd9d7)

Export an image per object: A grayscale image per object is saved as {image_file_name}_object{object_idx}.png.
![000000000139_object3](https://github.com/user-attachments/assets/0abd33ed-93e9-4235-aca9-477e59349c4e)

This is a list of exported mask images.

![mask_list](https://github.com/user-attachments/assets/f2c5f34f-da35-4e16-a0bd-cc723223bee3)

**Comment by willweimike** [comment]
Thank you!!!
