### ISSUE TITLE
[Feature request] No prompt for single label

### ISSUE THREAD

**Issue by cipri-tom** [ryouchinsa/Rectlabel-support#27]
It is getting annoying and tiring to have the pop-up dialog for every annotation.

I believe it would be much much faster if we could select a label, then make all boxes for that label. No prompting in between. Then we change to the next label, and again do all boxes.

Obviously, if you have only 1 label, you never get the prompt, which is just getting in the wa

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Added "Skip Label Dialog When Create" on the settings dialog.
RectLabel remembers the previously created or edited label text.

![settings_store_others](https://user-images.githubusercontent.com/1954306/31576425-80f69dc0-b135-11e7-8305-e133add3a8eb.jpg)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
RectLabel 1.43 was released.
- Added "Skip Label Dialog When Create" on the settings dialog.
- RectLabel remembers the previously created or edited label text.

**Comment by cipri-tom** [comment]
Thank you for moving so fast ! 
I can't wait to try it !

**Comment by cipri-tom** [comment]
It works really nicely! Thank you!

It is worth to document that in order to change the label you can double click on a box
