### ISSUE TITLE
Bboxes look like shifted to left side compared to the other tool

### ISSUE THREAD

**Issue by linked-drug-data** [ryouchinsa/Rectlabel-support#28]
Thank you for providing a nice tool. 
RectLabel is useful for us to be able to load large size images.

But I found a problem that bboxes look like shifted to left side when RectLabel reads a Pascal VOC annotation file which is created with LabelImage. (https://github.com/tzutalin/labelImg)

Image Size: 10000 * 2500 pixels
Format: PNG
MacOS 10.13

Do you have any idea to fix it?
Thank you.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We respect the amazing tool LabelImage.

If you could, could you show us the screenshot and the annotation file?

We did some simple tests.
We created a box of (xmin, ymin, xmax, ymax) = (1, 1, 100, 100) at the top left corner on RectLabel.

![2017-10-16 12 45 51](https://user-images.githubusercontent.com/1954306/31594461-02c3533a-b270-11e7-9428-a068745620d0.png)

![2017-10-16 12 45 23](https://user-images.githubusercontent.com/1954306/31594463-0475b7ea-b270-11e7-86cb-27cb7f32e568.png)

When LabelImage reads this xml file, it looks there is 1 pixel margin between the box and the image boundary.
![2017-10-16 12 47 11](https://user-images.githubusercontent.com/1954306/31594493-2a63255a-b270-11e7-87c3-4c048675b250.png)

When we drag the box to the top left corner on LabelImage, the box coordinates change to (xmin, ymin, xmax, ymax) = (1, 1, 99, 99).
![2017-10-16 12 48 25](https://user-images.githubusercontent.com/1954306/31594521-5c2f5e46-b270-11e7-908f-ba64fe985385.png)

![2017-10-16 12 47 53](https://user-images.githubusercontent.com/1954306/31594526-6103bd54-b270-11e7-9a70-8808cda9008e.png)

This means the box size becomes 1 pixel smaller than the original size around the image corner.

We think there should be some improvements on LabelImage to maintain the same size around the image corner.
Or there might be the floating point rounding error.

Let us know your opinion.

Best regards,
Ryo

**Comment by linked-drug-data** [comment]
Hi Ryo-san, 

Thank you for response.

The shift may occur depending on the aspect ratio of the image.
I will give you an email instead of uploading screenshots here because of licence issue.

Regards,

**Comment by ryouchinsa** [comment]
Thanks for finding this problem.

We could fix that box positions were misaligned when the image had a large aspect ratio such as width:height = 9079:816.
The image view had a slightly different aspect ratio compared with the original image.

Created a box on LabelImg.
![2017-10-17 0 59 01](https://user-images.githubusercontent.com/1954306/31622802-5e552846-b2d8-11e7-89e7-13755a447215.png)

Xml file saved from LabelImage.
![2017-10-17 1 12 24](https://user-images.githubusercontent.com/1954306/31622817-65c65668-b2d8-11e7-946c-b0f128bcac65.png)

Read on RectLabel. The box is slightly misaligned.
![2017-10-17 1 00 20](https://user-images.githubusercontent.com/1954306/31622824-6fa86bbc-b2d8-11e7-863f-4557c5b3fef6.png)

Xml file saved from RectLabel.
![2017-10-17 1 12 39](https://user-images.githubusercontent.com/1954306/31622828-726c5278-b2d8-11e7-9276-33c5b82ca69a.png)

Now the box is correctly aligned.
![2017-10-17 1 00 36](https://user-images.githubusercontent.com/1954306/31622832-77153416-b2d8-11e7-8427-ef3143ae9855.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by linked-drug-data** [comment]
Hi, Ryo

Thank you for quick response. I appreciate it.
I can not wait fixing it !!

Regards,
Yoshi

**Comment by ryouchinsa** [comment]
RectLabel 1.45 was released.

**Comment by linked-drug-data** [comment]
I confirmed the problem is fixed.
Thanks!
