### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by TernaK** [ryouchinsa/Rectlabel-support#3]
First of all, let me just say thanks for creating Rectlabel. I have found Rectlabel very simple and straight to the point whereas other labelling tools require PyQt4 which isn't compatible with modern macOS releases.
I find it quicker to just label the smaller objects right away than have to zoom in to get a clearer view of them. Resizing the windows to make them large causes some of the UIViews to disappear and the image view also gets displaced. I get around that by keeping the window size small enough for the UIViews to still be visible. It's not very high priority as everything else still works great but a few more Auto Layout constraints could definitely make this great app even better.

**Comment by ryouchinsa** [comment]
Thanks for reporting the problem.

When you resize the window, you drag one of the four corner points of the window.
Could you give us the screenshot?

In our environment, we are using both the thunderbolt display and the MacBook Pro display.
In each display, we could resize the RectLabel window without any problem.

But when we drag the RectLabel window from the thunderbolt display to the MacBook Pro dislay,
Buttons in the upper area disappear.
This would be a problem of our Auto Layout constraints.

![1](https://user-images.githubusercontent.com/1954306/27668445-12b53c72-5cbc-11e7-8e8a-523440e2ecd7.png)

![2](https://user-images.githubusercontent.com/1954306/27668450-160d9ab8-5cbc-11e7-8f71-da81ee36d517.png)

We would start fixing this problem to make Auto Layout constraints work normally.

Let us know your opinion.

Best regards,
Ryo

**Comment by TernaK** [comment]
<img width="1440" alt="screen shot 2017-06-28 at 7 56 12 pm" src="https://user-images.githubusercontent.com/11550520/27669522-f9686274-5c3b-11e7-913d-0bdcc30714c1.png">
This is similar to the photo you posted.

**Comment by ryouchinsa** [comment]
Thanks for the screenshot.
The problem in the screenshot would be the same as we could reproduce in our environment.

To solve the problem, we removed the aspect ratio for the main view.
When we drag the window from the thunderbolt display to the MacBook Pro display, it works normally.

![1](https://user-images.githubusercontent.com/1954306/27693984-c72994b4-5d25-11e7-98dc-681486d170c4.png)

![2](https://user-images.githubusercontent.com/1954306/27693991-cadef266-5d25-11e7-88cf-b9a913d1ea4f.png)

We submitted the update to iTunes Connect.
We will let you know when the new update could be released.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
The new update has been released.
Could you check whether this update would solve the problem in your environment or not?

**Comment by TernaK** [comment]
Here is the app window resized to fit the screen.
<img width="1440" alt="screen shot 2017-06-29 at 6 04 12 pm" src="https://user-images.githubusercontent.com/11550520/27716902-5c841bea-5cf6-11e7-84f4-5f47896e65f8.png">

That issue with the disappearing buttons has been resolved, thanks for the quick fix.
I noticed one more small issue - the labels TableView (right sub-window) takes up almost 50% of the total window space when resized to fit the screen, as you can see in the photo above. Perhaps more space for the image labeling window is better.

Otherwise, in true "fullscreen" mode like the photo below, it looks perfect!
<img width="1440" alt="screen shot 2017-06-29 at 6 13 20 pm" src="https://user-images.githubusercontent.com/11550520/27716972-e4ac1e5a-5cf6-11e7-9259-e5d51b1cbe07.png">

**Comment by ryouchinsa** [comment]
Thanks for checking the new update.

For the width of the table view, you can drag the right side of the window to adjust the width.
Once you could adjust to your favorite width, RectLabel remembers the window's position and width.
When you launch RectLabel at the next time, the same position and width would be restored.

![1](https://user-images.githubusercontent.com/1954306/27718069-5252b904-5d84-11e7-8ee0-512a75b87fb4.png)

![2](https://user-images.githubusercontent.com/1954306/27718072-55a5e8ba-5d84-11e7-8627-ab0092e940e5.png)

**Comment by ryouchinsa** [comment]
We agree that fullscreen-like auto layout would be preferable.
Thanks for pointing out.

The new update was released on Mac App Store today.

![1](https://user-images.githubusercontent.com/1954306/27773986-1aff029c-5fc2-11e7-9282-d662cd10ccf8.png)

**Comment by TernaK** [comment]
I tested it, and it's perfect.

**Comment by ryouchinsa** [comment]
Thanks for testing and your feedback.
We could make this product better.
