### ISSUE TITLE
[FEATURE] The canvas should resize when resizing the window

### ISSUE THREAD

**Issue by cipri-tom** [ryouchinsa/Rectlabel-support#30]
This is a UX problem:

the labels box is stuck with the canvas, and they're centered in the app's window. If you make the window wider, only the sides go wider, but the size of the canvas is the same.

I suggest having the list of boxes stick to the right size, and the canvas (along with the "<", ">" buttons) take up all the remaining space. This makes it easy to still keep the whole document width when zooming in, for annotating small objects in big images.

As a plus, consider making the background of the app window a little bit darker in colour or putting a small border around the image canvas. This helps when you have images with white background (documents) and you cannot see where the image finishes and the rest starts. I admit my monitor is not perfectly calibrated and there may be a difference between the two, but it is too small.

Many thanks for your support !

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you show us a simple mockup to meet your request?

**Comment by cipri-tom** [comment]
![mockup-1](https://user-images.githubusercontent.com/2991890/32320720-fd606a0c-bfbe-11e7-98c8-b5e1872cb424.png)
![mockup-2](https://user-images.githubusercontent.com/2991890/32320721-fd7e3370-bfbe-11e7-9739-c7bad905586c.png)

**Comment by ryouchinsa** [comment]
Thanks for your mockup.

We would start coding so that the canvas would be shown widely.

**Comment by cipri-tom** [comment]
Thank you ! Your efforts are greatly appreciated !!

If it's not too much to ask, consider integrating with touchpads too. So two finger zoom and pan. Imagine: left hand for zooming/panning, right hand on mouse for annotating. With the previous feature which you already implemented to not ask for confimartion dialog, this app transforms you in an annotation machine !! \m/

**Comment by ryouchinsa** [comment]
In the next update, these features are included.
- Added wide canvas
- Added image border
- Fixed image name background was not shown

![2017-11-04 5 43 42](https://user-images.githubusercontent.com/1954306/32395121-3590f72e-c123-11e7-937d-0b40ae703da0.png)

![2017-11-04 5 43 17](https://user-images.githubusercontent.com/1954306/32395122-39487b44-c123-11e7-88a1-b2308a1fba1e.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
RectLabel 1.48 was released.

> Imagine: left hand for zooming/panning, right hand on mouse for annotating

That would help in the production use.
We would integrate with trackpads.

> this app transforms you in an annotation machine !! \m/

That sounds great.

**Comment by cipri-tom** [comment]
Works great ! Thank you !
