### ISSUE TITLE
No way to convert from json format to pascal VOC

### ISSUE THREAD

**Issue by nilsou** [ryouchinsa/Rectlabel-support#31]
I annotated a bunch of images and then realized that the setting was set to json which is not the format I want.

I switched to Pascal VOC but now I would have to re-annotate everything.

Is there a way to convert the json files to Pascal VOC xml?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We have not coded the converter yet.

If you could code the converter by yourself and make it public on your Github repository, we would introduce your repository as one of the useful converters on our Github support page.
https://github.com/ryouchinsa/Rectlabel-support

@softwaremill could code the converter to the KITTI format on Nvidia DIGITS.
https://github.com/softwaremill/detectnet-tests

Let us know your opinion.

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
From File menu, you can convert the JSON files to XML files in the folder.
We finished supporting the JSON format.

![2017-11-23 1 46 14](https://user-images.githubusercontent.com/1954306/33140873-b264bc74-cff4-11e7-8b12-eceabe61301a.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

RectLabel 1.50
- added rotate box mode
- added drawing polygon mode
- added drawing cubic bezier mode
- added convert JSON files to XML files menu
- removed JSON file format support
- removed smart guides

**Comment by ryouchinsa** [comment]
RectLabel 1.50 was released.
