### ISSUE TITLE
Negative coordinates

### ISSUE THREAD

**Issue by mistiansen** [ryouchinsa/Rectlabel-support#32]
Is there support for negative coordinates (say, for an object with some occlusion)?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Do you mean you want to move the box outside the image?

**Comment by mistiansen** [comment]
Yes

**Comment by mistiansen** [comment]
Imagine having a "canvas" of sorts (like in Photoshop) and being able to draw boxes outside of the image for objects whose bounds extend beyond the image. It may seem strange, but it would be very helpful for use with certain OpenCV functions like findContours, which can find contours even with occlusion of the object. I didn't know if something like this is already possible or not.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.

RectLabel 1.55
- Added "Allow outside the image" on the settings.

When the new update is released, we will let you know.
Thank you.

![2017-12-13 1 49 39](https://user-images.githubusercontent.com/1954306/33897222-3ae6bb0c-dfa8-11e7-8cd9-da3f971e59a3.png)

![2017-12-13 1 51 01](https://user-images.githubusercontent.com/1954306/33897225-3ca2f1fe-dfa8-11e7-9524-68dcf53c8a7e.png)

**Comment by ryouchinsa** [comment]
RectLabel 1.55 was released.
