### ISSUE TITLE
Idea for new program.

### ISSUE THREAD

**Issue by opensprayer** [ryouchinsa/Rectlabel-support#34]
I made a video to talk about an idea I had for a simple program to generate small labeled images fast. You would load an image into the program and then use the mouse to take snapshots and automatically save them to folders for each class. You might use hotkeys to designate classes. Not sure if this exists already? https://www.youtube.com/watch?v=FDouW7fSIms

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue and creating the video.

We added "Label image" to label the image without drawing any boxes. 

![2017-12-16 17 38 07](https://user-images.githubusercontent.com/1954306/34068901-07dace8c-e288-11e7-8069-3f9060e382ff.png)

Using "Skip Label Dialog When Create", you do not have to set the label text every time.

![2017-12-16 17 38 26](https://user-images.githubusercontent.com/1954306/34068902-09368370-e288-11e7-9211-04f9cf011304.png)

With these features, you can label many images without drawing any boxes and setting the label  text on the label dialog.

If you want to label the rectangle region in the image, we think you have to draw boxes.
For image resizing, you could do that in your python program.

Best regards,
Ryo
