### ISSUE TITLE
select and delete multiple annotations

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#36]
Hello,
We have an automated process which detects salient features and automatically draws bounding boxes for us. We then open the images and corresponding Pascal VOC in RectLabel for final naming and cleanup of the labels. Because our saliency detection often find more objects of interest than we actually desire, I would like to be able to select and delete multiple annotations at once. Is it possible for you to add this feature?
Thanks,
Lonny Lundsten

**Comment by ryouchinsa** [comment]
Hi, 

Thanks for writing this issue.
You want to select multiple boxes at the same time and delete them, correct?

Best regards,
Ryo

**Comment by lonnylundsten** [comment]
Yes. Thank you!

**Comment by ryouchinsa** [comment]
We would implement the feature in the next update.
We will let you know when the update is released.

**Comment by lonnylundsten** [comment]
Would it also be possible to select and delete multiples in the column list? Something like command-click to select specific names and shift-select to select a series of names from x->z.
Thanks!

**Comment by ryouchinsa** [comment]
The new update 1.91 was released.

- On the label table, using command + click or shift + click, you can select multiple boxes and delete them.
- Drag & drop with multiple boxes is working as well on the label table.

![multiple_select_label_table](https://user-images.githubusercontent.com/1954306/39957947-778744c8-5636-11e8-993b-6b335aba3839.gif)
