### ISSUE TITLE
Convert csv to SFrame not working

### ISSUE THREAD

**Issue by Kevinator123** [ryouchinsa/Rectlabel-support#38]
When I run the script I run into the error shown in the picture
<img width="823" alt="screen shot 2018-05-04 at 11 18 20" src="https://user-images.githubusercontent.com/17850642/39624019-f97cfae0-4f97-11e8-91d5-67720e69d9d4.png">

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you show us the RectBoundsData.csv for debugging?

Best regards,
Ryo

**Comment by Kevinator123** [comment]
can't attach a .csv file so here are the first lines:
annotation,folder,filename,path,source,database,size,width,height,depth,segmented,object,name,pose,truncated,difficult,bndbox,xmin,ymin,xmax,ymax
,"Thermostat off","IMG_0073.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat off/IMG_0073.jpg",,"Unknown",,"3024","3024","3","0",,"off","Unspecified","0","0",,"1082","1150","1906","1831"
,"Thermostat off","IMG_0001.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat off/IMG_0001.jpg",,"Unknown",,"3024","3024","3","0",,"off","Unspecified","0","0",,"987","1105","1769","1776"
,"Thermostat on","IMG_0179.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat on/IMG_0179.jpg",,"Unknown",,"3024","3024","3","0",,"on","Unspecified","0","0",,"1022","1156","1563","1624"
,"Thermostat off","IMG_0011.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat off/IMG_0011.jpg",,"Unknown",,"3024","3024","3","0",,"off","Unspecified","0","0",,"1298","1140","2036","1796"
,"Thermostat on","IMG_0169.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat on/IMG_0169.jpg",,"Unknown",,"3024","3024","3","0",,"on","Unspecified","0","0",,"1006","1150","1514","1568"
,"Thermostat off","IMG_0087.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat off/IMG_0087.jpg",,"Unknown",,"3024","3024","3","0",,"off","Unspecified","0","0",,"1008","907","1793","1563"
,"Thermostat on","IMG_0220.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat on/IMG_0220.jpg",,"Unknown",,"3024","3024","3","0",,"on","Unspecified","0","0",,"893","1386","1490","1905"
,"Thermostat on","IMG_0230.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat on/IMG_0230.jpg",,"Unknown",,"3024","3024","3","0",,"on","Unspecified","0","0",,"1006","1308","1625","1800"
,"Thermostat off","IMG_0018.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat off/IMG_0018.jpg",,"Unknown",,"3024","3024","3","0",,"off","Unspecified","0","0",,"1372","1029","2077","1713"
,"Thermostat off","IMG_0008.jpg","/Users/Kevin/MLClassifier/Non active datasets/Thermostat off/IMG_0008.jpg",,"Unknown",,"3024","3024","3","0",,"off","Unspecified","0","0",,"1174","1144","1953","1842"

**Comment by ryouchinsa** [comment]
Our feature "Convert XML to CSV in the folder" saves the CSV file in the format below.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/example.csv

```
path,annotations
/Users/ryo/Desktop/test_data_small/1.jpg,"[{'label':'shoes','type':'rectangle','coordinates':{'height':56,'width':26,'x':14,'y':779}},{'label':'shoes','type':'rectangle','coordinates':{'height':83,'width':35,'x':444,'y':812}},{'label':'shoes','type':'rectangle','coordinates':{'height':80,'width':41,'x':352,'y':837}},{'label':'shoes','type':'rectangle','coordinates':{'height':100,'width':49,'x':293,'y':855}},{'label':'shoes','type':'rectangle','coordinates':{'height':116,'width':48,'x':228,'y':896}}]"
/Users/ryo/Desktop/test_data_small/2.jpg,"[{'label':'bare feet','type':'rectangle','coordinates':{'height':138,'width':60,'x':437,'y':832}},{'label':'bare feet','type':'rectangle','coordinates':{'height':145,'width':71,'x':483,'y':854}}]"
```

![dbgkzfxvqaabh2h](https://user-images.githubusercontent.com/1954306/39646883-e422ba06-5017-11e8-9b3a-c506414f8c23.png)

Could you tell us which tool saved the CSV file?

**Comment by Kevinator123** [comment]
Aaah ok so it's the CSV files fault. I've purchased the tool now but I already had 100 images labeled with labelimg.py (a free visual python image labeler) so I merged the 100 xml files and then converted it to csv with an online converter. Came a cross many converters that didn't work at all but this one seemed to be ok. Apparently it was not. Well time to re label 100 images I guess :')

**Comment by ryouchinsa** [comment]
LabelImg saves label files in the PASCAL VOC xml format. 
RectLabel can read and write in the same format. 
We think you can continue using the same xml files on RectLabel, too.

**Comment by Kevinator123** [comment]
Possibly, tho they are both using VOC they are a little different but it might work, will try monday. Don't have access to the program at home, only at work, will let you know if it works. Thanks for the help :)

**Comment by Kevinator123** [comment]
It works with my xmls but for the record if anyone else wants to try this: You need to put a folder in the folder with your pictures called "annotations" and you have to have you pictures in the folder you open in rect image (it looks for the names of the pictures to create the csv from the xmls with the same name)

**Comment by Kevinator123** [comment]
Ok so next issue: 
<img width="822" alt="screen shot 2018-05-07 at 10 48 08" src="https://user-images.githubusercontent.com/17850642/39693401-2d5fc1be-51e4-11e8-8b9c-20649dff1e6e.png">

My csv file now is in the right format, exactly like depicted in the example.csv file, yet it still gives this error when running the convert script.
