### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#39]
Working with tons of images in a dark room with a bright white app can really begin cause fatigue and eye strain. It would be nice to have a dark theme for working in 'dark room' type environments. Photoshop, Pixelmator, and Affinity Photo all have dark backgrounds and are excellent examples to emulate.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We would check Photoshop's dark UI colors.

**Comment by ryouchinsa** [comment]
On the new update 1.92, we made RectLabel darker to improve your fatigue and eye strain.
For the settings dialog, if you think you need, we would make it darker, too.

![dark](https://user-images.githubusercontent.com/1954306/40870934-35d20260-666d-11e8-9a84-f04787e79f30.png)
