### ISSUE TITLE
Label boundaries exceed image range

### ISSUE THREAD

**Issue by sebastian-schlecht** [ryouchinsa/Rectlabel-support#4]
Hey,

I noticed that the boundaries of annotations can exceed the image ranges, i.e.

- Obtain -2 for xmin/ymin
- Obtain 325 for xmax/ymax even though the images sizes are 320x320

I don't know if this is the desired behaviour, but I was definitely not expecting it.

It can happen in case I adjust my annotations and drag the anchors outside of the image boundary. I haven't tested JSON yet, but this definitely occurs with PASCAL-VOC format which broke some of my machine learning pipelines.

Version: 1.24

**Comment by ryouchinsa** [comment]
Thanks for reporting the problem.

Currently when you move the box outside the image, the coordinates exceed the image ranges.
But we are going to change so that you are limited to create, transform and move the box inside the image.

We will get in touch with you in a few days.

**Comment by ryouchinsa** [comment]
Today we submitted the new update.
You are limited to create, transform and move the box inside the image.
The top-left pixel in the image has coordinates (1, 1).
http://host.robots.ox.ac.uk/pascal/VOC/voc2007/devkit_doc_07-Jun-2007.pdf

Here is an example.
If you create a box as the same size as the image, annotations will be like below.
xmin = 1
ymin = 1
xmax = width
ymax = height

Let us know your opinion.

![1](https://user-images.githubusercontent.com/1954306/27846134-1e606818-6170-11e7-9dd2-b6c67e6b029f.png)

```xml
<annotation>
    <folder>_image_material</folder>
    <filename>0ttycfo61xs-don-ross-iii.jpg</filename>
    <size>
        <width>1600</width>
        <height>1067</height>
    </size>
    <segmented>0</segmented>
    <object>
        <name>image</name>
        <bndbox>
            <xmin>1</xmin>
            <ymin>1</ymin>
            <xmax>1600</xmax>
            <ymax>1067</ymax>
        </bndbox>
    </object>
</annotation>
```

**Comment by ryouchinsa** [comment]
The new update RectLabel 1.26 has been released.
- Limited to create, transform and move the box inside the image.
- The top-left pixel in the image has coordinates (1, 1).
