### ISSUE TITLE
Launch Rectlabel from command line & open folder

### ISSUE THREAD

**Issue by zacharymostowsky** [ryouchinsa/Rectlabel-support#40]
Hello,

I can launch rectlabel form the terminal using this command: "open -a rectlabel"

Is there a way to pass in an argument to specify what folder to open? I have a need to launch rectlabel from a script, opening a different folder of images each time for labelers.

Thanks in advance,
Zach

**Comment by ryouchinsa** [comment]
Hi,

Thanks for writing the issue.

Usually RectLabel could obtain the folder access right when users opened the folder.
We started investigating whether the app sand box could work with the command line or not.

https://stackoverflow.com/questions/11821632/mac-os-app-sandbox-with-command-line-tool

https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
Off course, RectLabel can handle the command line arguments, but we could not have access right to the folder without opening the folder using NSOpenPanel.
So that it looks difficult to open the folder passed by the command line arguments.

**Comment by zacharymostowsky** [comment]
Thank you for your response. I decided to go with a python based solution called LabelImg.
