### ISSUE TITLE
Rectlabel keeps quitting unexpectedly

### ISSUE THREAD

**Issue by khorie93** [ryouchinsa/Rectlabel-support#41]
I am no longer able to open RectLabel without it quitting right as I open it, and then I get an error message asking if I should ignore, report, or reopen the app. I am on a Mac.

How can I resolve this issue?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We have not experienced the problem yet.

You were able to use RectLabel for a while, correct?
It would be very helpful if you could tell us what kind of action you did recently, for example, opening the new folder or updated the OS X version.

You can clear the cache files of RectLabel.
https://stackoverflow.com/questions/7982740/where-is-a-mac-applications-nsuserdefaults-data-stored

Cache files are under the folder below.
~/Library/Containers/com.waysify.roi/

Move the folder to other place, for example, your desktop.

After that you should open RectLabel again.
Hopefully this might work.
