### ISSUE TITLE
Export to COCO format

### ISSUE THREAD

**Issue by tomcin** [ryouchinsa/Rectlabel-support#45]
Awesome tool! But I think you need to support more export format options like COCO, JSON!

**Comment by ryouchinsa** [comment]
Hi,

Thanks for writing the issue.

Now we are implementing in-app purchase to realize 2-Week Free Trial to acquire more new users and prevent pirating.

After that, we would start implementing basic output format such as COCO, KITTI, Turi create, segmentation mask image, etc.

Labelbox is a good reference.
https://github.com/Labelbox/Labelbox#exporting-labels

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
The new update version 2.06 was released.

Now we support some export format options.

Export XML files to COCO JSON file
https://rectlabel.com/help#xml_to_coco

Export mask images for the image
https://rectlabel.com/help#mask_image

Export label map
https://rectlabel.com/help#label_map

Export TFRecord for Tensorflow
https://rectlabel.com/help#tf_record
