### ISSUE TITLE
Polygon bounding box?

### ISSUE THREAD

**Issue by dxoigmn** [ryouchinsa/Rectlabel-support#46]
Would it be possible to automatically compute and add the minimum bounding box for a polygon object? This would be helpful for Tensorflow.

**Comment by ryouchinsa** [comment]
Thanks for the feature request.

Could you show us the new data format which you want?
https://rectlabel.com/help#output_format

```
<object>
    <name>buckle</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <polygon>
        <x1>1860</x1>
        <y1>3712</y1>
        <x2>2010</x2>
        <y2>3711</y2>
        <x3>2021</x3>
        <y3>3799</y3>
        <x4>1867</x4>
        <y4>3803</y4>
    </polygon>
</object>
```

In the Tensorflow object detection API, bounding boxes are used for training.
You mean you want to train polygons as bounding boxes?

**Comment by dxoigmn** [comment]
Here's an example of what I was thinking:

```
<object>
    <name>buckle</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <polygon>
        <x1>1860</x1>
        <y1>3712</y1>
        <x2>2010</x2>
        <y2>3711</y2>
        <x3>2021</x3>
        <y3>3799</y3>
        <x4>1867</x4>
        <y4>3803</y4>
    </polygon>
    <bndbox>
        <xmin>1860</xmin>
        <ymin>3711</ymin>
        <xmax>2021</xmax>
        <ymax>3803</ymax>
    </bndbox>
</object>
```

Basically, the bndbox would be the coordinates of the minimum bounding box that contains that polygon.

**Comment by ryouchinsa** [comment]
Thanks for the output format.

1. If we add the bndbox when you save the polygon, the bndbox will be shown on the image, too.
Which timing would be the best for you to add the bndbox?

2. We have to understand the detailed reason when we add features on RectLabel.
When you use polygon with Tensorflow, usually Tensorflow needs the segmentation mask image.
Why do you need the bndbox of the polygon?

**Comment by dxoigmn** [comment]
> 1. If we add the bndbox when you save the polygon, the bndbox will be shown on the image, too.
> Which timing would be the best for you to add the bndbox?

I don't really care to see the bounding box so long as it is saved with the XML. I imagine the drawing logic could be the following:

```
if object is 'polgygon':
  drawPolygon()
elif object is 'bndbox':
  drawBoundingBox()
else
 ...
```

> We have to understand the detailed reason when we add features on RectLabel.
> When you use polygon with Tensorflow, usually Tensorflow needs the segmentation mask image.
> Why do you need the bndbox of the polygon?

The [create_pascal_tf_record.py](https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py) tool in the Tensorflow Object Detection API wants a bounding box. I labeled my images using polygons because I also want to generate masks from the polygon data for Mask R-CNN. However, it would also be useful to train a R-CNN (with no masks). I have modified the tool for now to compute the bounding box, so it's unclear whether this feature would be actually useful to others.

**Comment by ryouchinsa** [comment]
Thanks for the details.
We appreciate your feature request.
We would implement the new feature.

**Comment by ryouchinsa** [comment]
The new update version 2.04 was released.
- Added "bndbox" when you save the rotated box, polygon, and cubic bezier.
- Added "polygon" when you save the rotated box.

https://rectlabel.com/help#output_format
