### ISSUE TITLE
Double-clicking deletes shape which is very frustrating

### ISSUE THREAD

**Issue by ageitgey** [ryouchinsa/Rectlabel-support#47]
When I am creating a polygon outline for an object, sometimes I'll accidentally double click instead of single click.

In the current version of RectLabel, double clicking while drawing a polygon instantly deletes and clears the entire shape for some reason. This is very frustrating if you are annotating complex objects:

![rectlabel ui issue](https://user-images.githubusercontent.com/896692/44280022-5ab43e00-a208-11e8-912b-5bf97e9de9c0.gif)

Is there any way to disable this feature? If not, could you consider that as a future feature?

**Comment by ageitgey** [comment]
Thanks!

**Comment by ryouchinsa** [comment]
The new update version 2.02 was released.

**Comment by ageitgey** [comment]
Thanks!
