### ISSUE TITLE
13" Macbook Pro bounding box is only square

### ISSUE THREAD

**Issue by TernaK** [ryouchinsa/Rectlabel-support#5]
When trying to label objects, the bounding box is forcing me to use a square. What I mean is no matter how much I drag the mouse when I'm drawing the box or when I attempt to resize an already drawn box, it's forcing the aspect ration to be 1:1, so I can't draw a rectangle. 

![square_box](https://user-images.githubusercontent.com/11550520/27968135-a361d5f2-62fa-11e7-9666-f1367726c77b.gif)

Rectlabel v1.26

Note: I did not see this behaviour on my 15" Macbook Pro with Rectlabel v1.24.

**Comment by ryouchinsa** [comment]
Could you open "Settings" and click "face" in the "Objects" table?
If you set the "Aspect Ratio" field to empty, the aspect ratio becomes free.

![1](https://user-images.githubusercontent.com/1954306/27971332-4f907cd8-638d-11e7-8ab9-b5a9488fca5f.png)

**Comment by TernaK** [comment]
Thanks! That fixed it.

**Comment by ryouchinsa** [comment]
Thanks for writing this issue.
Other users would read and understand what to do when they have troubles for the aspect ratio.
