### ISSUE TITLE
Create an image rotation tool

### ISSUE THREAD

**Issue by vintserg** [ryouchinsa/Rectlabel-support#51]
Please,
Add an image rotation tooll (all photo)

In my dataset a lot of images rotated by 180 or 90 degrees.
I tried to turn them by imagemagick (autoorientation), but the result is not 100%.

Thank you!!

**Comment by ryouchinsa** [comment]
Thanks for writing the feature request.

We would add the "Rotate image by 180 or 90 degrees" feature.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
The new update version 2.11 was released.

Added "Rotate image" feature.
When you are in the "Rotate" mode and drag upper or lower on the image, you can rotate the image by 90 degrees step and save it.

![2018-09-22 18 25 51](https://user-images.githubusercontent.com/1954306/45915728-fdf61400-be94-11e8-9d4c-ec6562c7f7af.png)

**Comment by vintserg** [comment]
Great !!!

Thank you!

**Comment by ryouchinsa** [comment]
From Edit menu, use these menus.
"Rotate image right" rotates the image by 90 degrees clockwise.
"Rotate image left" rotates the image by 90 degrees counter-clockwise.
https://rectlabel.com/help#rotate_image
