### ISSUE TITLE
In-App Purchase Issue

### ISSUE THREAD

**Issue by SoroushKadineh** [ryouchinsa/Rectlabel-support#53]
I have gone through the troubleshooting of "To solve the problem when you buy in-app purchase" on the Help page, I've done the steps 4 times by now! Even bought another app on the Mac App Store to make sure there's nothing wrong with payment stuff. Please HELP ME!

Error that I get is: 

> Your Purchase Could Not Be Completed

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We really want to help you, but we are wondering how to fix it.
Until today, hundreds of users succeeded to download the in-app purchase items.

We know some users are having troubles for in-app purchase.
https://twitter.com/rectlabel/status/1042875410071973888

> Even bought another app on the Mac App Store to make sure there's nothing wrong with payment stuff.

In which app could you buy the in-app purchase?

> Your Purchase Could Not Be Completed

Could you give us the screenshot?

Best regards,
Ryo

**Comment by SoroushKadineh** [comment]
I didn't buy any in-app purchase, just bought another app to make sure there's nothing wrong with my credit card.

![screen shot 2018-09-28 at 2 02 52 pm](https://user-images.githubusercontent.com/29879921/46228360-7a6e7400-c327-11e8-91be-5ccd6ad75b5d.png)
![screen shot 2018-09-28 at 2 03 02 pm](https://user-images.githubusercontent.com/29879921/46228367-7e01fb00-c327-11e8-9fbc-8c9f553430c1.png)

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Did this troubleshooting work for you?
http://rectlabel.com/help#troubleshooting

**Comment by SoroushKadineh** [comment]
@ryouchinsa, I didn't do anything but to try purchasing the In-App Purchase 18 days later, EVERYTHING WOKRED SOMEHOW!!!

**Comment by ryouchinsa** [comment]
Thanks for letting us know the good news.
We do not know how to fix the problem yet, but we appreciate your best effort.

**Comment by florischabert** [comment]
I'm also having an issue with in-app purchase.
I've had the app on my Mac for months (when it was still free) and now want to be able to save again but I'm not able to buy the in-app purchase. I've tried the steps from the help page (remove app, log out of App Store and reboot) but it didn't help.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/89882/49330587-c96e9a80-f55e-11e8-8143-735a4c199894.png">

I love the app but really need to be able to save my annotations again!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

At first, could you restore purchase from app menu?

From the version 2.18, we started asking existing users(downloaded before Aug 5 2018) to pay the same total amount $4.99 as new users pay. 

To be fair, we are considering the amount you paid when you downloaded.
So that the amount you have to pay varies according to the download date.
$4.99 Mar 28 2017
$3.99 Dec 14 2017
$2.99 Jun 2 2018

Please read the details and discuss here.
https://github.com/ryouchinsa/Rectlabel-support/issues/64

Best regards,
Ryo
