### ISSUE TITLE
 "Export bndboxes in XML files to CSV file" produces an empty csv file

### ISSUE THREAD

**Issue by SoroushKadineh** [ryouchinsa/Rectlabel-support#55]
How do I reproduce this (version 2.11):
Open folder 
set Images and Annotations folder (1 image in the Images and nothing within Annotations) 
Create Polygon for my image -> Save
File -> Export bndboxes in XML files to CSV file -> Do you start converting label files?
then I choose OK, then choose a location and save. 
Results in having an empty csv file with only two titles: path, annotations.
Am I doing something wrong?

UPDATE: updated to version 2.13 everything works now, WOW!

**Comment by ryouchinsa** [comment]
In the version 2.13, we fixed the problem.

- Improved that both exporting and importing a CSV file include boxes, rotated boxes, polygons, and cubic bezier objects.

Thank you.
