### ISSUE TITLE
Export to tfrecord

### ISSUE THREAD

**Issue by nathanaherne** [ryouchinsa/Rectlabel-support#56]
On this page you show the instructions on how to [export to tfrecord](https://rectlabel.com/help#tf_record)

It seems the instructions are incomplete as the command runs on a non existent folder. None of the dependencies of the script are documented (as far as I can see). While I am certain that I could get the script working by tracking everything down, it would be far easier if the instructions were complete.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

In the sample code below, the default annotations folder is "images folder/annotations".

If the command runs on a non existent folder, you have to specify your annotations folder path relative to your images folder.

```
python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py \
    --images_dir="${IMAGES_DIR}" \
    --label_map_path="${LABEL_MAP_PATH}" \
    --output_path="${OUTPUT_PATH}" \
    --include_masks

flags.DEFINE_string('annotations_dir', 'annotations', '(Relative) path to annotations directory.')
```

**Comment by nathanaherne** [comment]
I created this issue because there are many dependencies to getting this script to run that are may not be apparent to the user. For instance:

1. You need to install tensorflow
2. You need to download the models repository
3. You need to copy the script into the /models/research/object_detection/dataset_tools/ folder
etc.

I was simply flagging that it might be worthwhile to flesh out the instructions.

**Comment by ryouchinsa** [comment]
Thanks for pointing out.

We added the installation flow here.
https://rectlabel.com/help#tf_record

> At first, download TensorFlow models repository.
> Then, install Tensorflow Object Detection API.
> Change the current directory to "models/research/".
> Put the python code below to "models/research/object_detection/dataset_tools/" folder.
