### ISSUE TITLE
Changing of object names to update existing object records

### ISSUE THREAD

**Issue by nathanaherne** [ryouchinsa/Rectlabel-support#57]
I started out on a project with a large number of object classes to label in video frames. As I am going through the frames, I am changing the names of the object classes to better fit the dataset. When I do make a change, I need to go back through all previous frames and label the objects as the correct name. It would be great if it was possible to do this automatically.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

If there were a feature of "Replace label names for all images" and you can replace partial text in label names, does it work for you?

**Comment by nathanaherne** [comment]
Yes, I think that would solve the issue. You would only want to change the label names for images in the folder that was currently open.

**Comment by ryouchinsa** [comment]
Added "Replace label text for all images" in the File menu.
This is useful when you changed the object name or attribute name.
https://rectlabel.com/help#replace_text

![2019-01-14 10 28 49](https://user-images.githubusercontent.com/1954306/51093961-ed72fc00-17eb-11e9-818f-15d2fb354299.png)

The new update version 2.31 was released.
