### ISSUE TITLE
File sorting to consider full filename

### ISSUE THREAD

**Issue by nathanaherne** [ryouchinsa/Rectlabel-support#58]
Ive created a couple hundred images from video frames and put the frame number at the end of each filename, for example "frame_200", "frame_1200". In the RectLabel software, "frame_1200" is sorted as being before "frame_200". This makes it difficult to see the progression of the video as I move through the frames (in chronologically named order). It would be good if RectLabel could sort the file names in more of a standard way.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you use "Numeric" in "Sort images" on the settings dialog?
https://rectlabel.com/help#others

**Comment by nathanaherne** [comment]
I have tried both alphabetic and numeric and both have the same issue.

**Comment by ryouchinsa** [comment]
After changing the "Sort images", could you press OK button on the "Open folder" dialog again?

**Comment by nathanaherne** [comment]
Thank you. This worked and the files are now sorted correctly.
