### ISSUE TITLE
Faster mask creation

### ISSUE THREAD

**Issue by nathanaherne** [ryouchinsa/Rectlabel-support#63]
I have had success training faster_rcnn_resnet101_coco on my own image data (40 classes). I now need to move to a mask based model instead of bounding boxes. I saw that RectLabel had this feature but then realised I would need to create polygons around each object. The amount of images that I would need to annotate, makes this very time expensive.

I found an mask annotation tool that used OpenCV to make things quicker, notably https://github.com/abreheret/PixelAnnotationTool. It does work on Mac but I would prefer to stick with your program. You are probably already aware of this program and its features but I thought I would put my vote in for you to add this sort of functionality within RectLabel. The functionality and functions used by the PixelAnnotationTool do not have to be exact but adding some smart functionality that made creating masks easier would be a helpful addition to the tool.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

For the mask labeling, we are going to add super pixel and brush tools.
https://support.labelbox.com/docs/labeling-with-superpixel

Another user requested the feature to label objects which have many twists and  turns.

**Comment by nathanaherne** [comment]
What is the timeframe for adding these features?

**Comment by ryouchinsa** [comment]
We are working on another feature now.
So that super pixel and brush tools would take a few weeks at least.

**Comment by nathanaherne** [comment]
I am currently waiting on the mask feature before I start annotating images again and then I had a thought that may benefit people who wish to convert box annotations into mask annotations. If the Mask feature had the ability to snap to the largest contour inside the box, this would make converting from box to mask very quick. Not sure if it is feasible or if customers want this... just a thought that I thought may be worthwhile sharing.

**Comment by ryouchinsa** [comment]
Again, it take a few weeks at least to implement the algorithm and the UI flow.
The data structure would be totally different from polygons.

Before waiting for the new update, we think you should check the super pixel and brush tools would be useful to label your images.

If you signed up Labelbox, you can check how it works.
https://support.labelbox.com/docs/labeling-with-superpixel

Super pixel is a simple segmentation algorithm so that for many cases, polygons are still useful to label the accurate contour for object detection and segmentation.

Do not expect so much on super pixel and brush tools.
So many developers are working on the segmentation problem with polygons.

**Comment by nathanaherne** [comment]
I checked out LabelBox when you mentioned it previously. I found their UI didn't work but the idea was a good one and it seemed like it would be quick to annotate images.

**Comment by ryouchinsa** [comment]
Hi,

Label pixels with superpixel and brush tools
https://rectlabel.com/help#label_pixels

The new update version 2.22 was released.

If you could give us some feedback to improve this feature, it would be very helpful.

![pixels](https://user-images.githubusercontent.com/1954306/50370246-a7f55180-05e6-11e9-96c9-22d65a18a3e7.jpg)

**Comment by nathanaherne** [comment]
Thank you for notifying me of this. I will get onto this ASAP and get back to you.
