### ISSUE TITLE
Single point annotations

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#66]
Please add the ability to add single point annotations. Rather than drawing a bounding box around an object I would like to be able to click on the object of interest and add a single point, which would then be saved as xy in the annotation.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

For the single point annotations, check "Show all edit points" on the settings dialog and start creating polygon.

![2018-11-21 18 12 13](https://user-images.githubusercontent.com/1954306/48830890-fed5f400-edb8-11e8-8e58-e206aa7c15eb.png)

![1pts](https://user-images.githubusercontent.com/1954306/48830791-c6361a80-edb8-11e8-964d-5dbae78d8137.png)

**Comment by lonnylundsten** [comment]
I'm not able to reproduce that single point behavior. When I follow your instructions the polygon points are connected by lines.
![screen shot 2018-11-21 at 8 29 48 am](https://user-images.githubusercontent.com/32526132/48854806-a591a480-ed67-11e8-891e-38138a0e840a.png)

**Comment by ryouchinsa** [comment]
Please press enter after you clicked the point.
For 1 point polygon, we do not show the line after you labeled.
For 2 point polygon, we do not close the polygon with the extra line after you labeled.

**Comment by lonnylundsten** [comment]
OK. That works. Thanks for your instructions.
Lonny

**Comment by ryouchinsa** [comment]
Now you can use "Create point" mode.
For "Create point", when you add a point, the label dialog would open soon.
To show all single points, use "Show all edit points".
https://rectlabel.com/help#create_polygon
