### ISSUE TITLE
Import/export object and attribute lists

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#67]
I would like to have the ability to import/export object and attribute lists so that I can have various users/workstations setup with the same working lists without having to remake them at each station.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
You can export and import the settings file which includes the object and attribute lists.

![2018-11-29 14 43 36](https://user-images.githubusercontent.com/1954306/49201678-36f6bb80-f3e5-11e8-894e-ebd24529e2d4.png)

Or you can switch different objects and attributes settings for different label task.
https://rectlabel.com/help#projects
