### ISSUE TITLE
Text Annotations with classes

### ISSUE THREAD

**Issue by aakashpatel25** [ryouchinsa/Rectlabel-support#69]
I am looking to get labels for each class for example, 

- window
- man
- whatever
- text

If the label is text than want to have one more field called "value" so it would be more like

```
<class> text </class>
<value> "Some text" </value>

```
Is there a way to do this with existing version? If not is there a plan to get this feature soon?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

When you label the text, how do you input the value?
On the label dialog, you choose the text in the object list and type the text, correct?

![2018-12-20 6 46 07](https://user-images.githubusercontent.com/1954306/50250405-045c4380-0424-11e9-8e55-b0ff5b261b7e.png)

In the PASCAL VOC xml format, the label name is saved in the "name" field.

![2018-12-20 6 47 52](https://user-images.githubusercontent.com/1954306/50250409-07573400-0424-11e9-94d8-a80e600af051.png)

Which part do you want to change?

**Comment by aakashpatel25** [comment]
It would be great if we had something like this

```
<object>
  <name>text</name>
  <value>"This is the text in the bounding box"</value>
  <pose>Unspecified</pose>
  .....
  <bndbox>
  ...
  </bdnbox>
</object>
```

For that if the object is text we would need another input field pop up in the lable box to put the value. That is what I want.

**Comment by ryouchinsa** [comment]
For the save format, we could understand.

For the input UI, do you have some good ideas which would be comfortable for you?

In the example below, we have to distinguish the object name "text" from the value text "100".
For example, when the object name is "text", other text could be thought as the value text.

![2018-12-22 13 28 06](https://user-images.githubusercontent.com/1954306/50370634-7df35d80-05ed-11e9-86ca-bbfa2a97f7aa.png)
