### ISSUE TITLE
Getting Error: Permission Denied when creating the folder

### ISSUE THREAD

**Issue by ankitshekhawat** [ryouchinsa/Rectlabel-support#7]
Getting this error when trying to save:
![image](https://user-images.githubusercontent.com/5464540/28657457-dfcf09ae-72c4-11e7-842e-6c6ef226e72e.png)

 I have tried doing chmod -R 775 (even 777) in vain
also tried manually creating the "annotations" folder

Using MacOS Sierra

**Comment by ankitshekhawat** [comment]
Looks like I found a bug. 

Seems like whenever there is a space in folder path, I get this error.

Removing the space from the folder path fixes the problem.

**Comment by ryouchinsa** [comment]
Thanks for finding the bug!
We appreciate your great help.
Now we started fixing the problem.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update was released.
RectLabel 1.28
Fixed the problem when you open a folder which includes spaces.

**Comment by ankitshekhawat** [comment]
Thanks Ryo,

Its an useful app. You guys should add keyboard shortcuts to make things
faster and expand it to tasks such as superpixel segmentation.

Ankit

Ankit

**Comment by ryouchinsa** [comment]
We have keyboard shortcuts.
https://rectlabel.com/help#keyboard_shortcuts

For segmentation, we would add  "Create a contour" feature like below in the near future.
https://arxiv.org/pdf/1704.05548.pdf

![dfrsemyuiaau_dz](https://user-images.githubusercontent.com/1954306/28796041-018fa57a-7677-11e7-8ca2-c764888d0366.jpg)

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

RectLabel 1.50
- added rotate box mode
- added drawing polygon mode
- added drawing cubic bezier mode
- added convert JSON files to XML files menu
- removed JSON file format support
- removed smart guides

![draw](https://user-images.githubusercontent.com/1954306/33141345-35edc404-cff6-11e7-9836-773f56073fb2.jpg)

**Comment by ryouchinsa** [comment]
RectLabel 1.50 was released.

**Comment by ryouchinsa** [comment]
Now RectLabel has the superpixel and brush tools.
https://rectlabel.com/help#label_pixels

![pixels](https://user-images.githubusercontent.com/1954306/51828105-366b9a00-232e-11e9-9283-ff307f09962b.jpg)
