### ISSUE TITLE
sort object list

### ISSUE THREAD

**Issue by lonnylundsten** [ryouchinsa/Rectlabel-support#72]
Please provide the capability of sorting the object list alphabetically (automatic sort) or manually by dragging and dropping objects in the list to the users desired order.

**Comment by ryouchinsa** [comment]
To change the object order, you can drag and drop on the object table.
Is it not enough for your use-case?

![2018-12-20 7 29 00](https://user-images.githubusercontent.com/1954306/50252776-65d3e080-042b-11e9-8ce3-b6857807ccb3.png)

**Comment by lonnylundsten** [comment]
Yes, drag and drop does work. However, I have 60+ objects and add more continuously. It would be nice to auto sort, alphabetically.

**Comment by ryouchinsa** [comment]
Ok, we would think where to implement the UI to sort objects table.

**Comment by ryouchinsa** [comment]
Added "Sort Alphabetic" on the objects table.
Right clicking on the objects table header, the sort menu would open.

The new update version 2.25 was released.
Let us know your opinion.

![2018-12-28 9 30 30](https://user-images.githubusercontent.com/1954306/50498351-63086980-0a83-11e9-9cbd-aff53b28975a.png)
