### ISSUE TITLE
Multiple Annotators

### ISSUE THREAD

**Issue by mrteera** [ryouchinsa/Rectlabel-support#73]
I would like to know how to annotate with multiple people. Can RectLabel split the dataset to multiple annotators and merge them? I'm considering to purchase RectLabel if the labeling task can scale.

**Comment by mrteera** [comment]
I think again.. maybe it's not difficult to merge the dataset from multiple annotators myself.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

You can set the Annotator name on the settings dialog and this is saved in the xml file. 
This is useful when you manage who labeled the annotations.
https://rectlabel.com/help#others

If you need another feature for team management, let us know.
