### ISSUE TITLE
import csv file to XML files creates error message

### ISSUE THREAD

**Issue by powderscotty** [ryouchinsa/Rectlabel-support#74]
when trying to use the function: "import CSV file to XML files" an error message is created that says: "current folder is different from image folder
current folder: /Users/name/documents/images/
image folder: /" 

In function: "Open folder" I have set image folder and annotation folder to match the path for the images found in the CSV. 

Any idea what I am doing wrong?

**Comment by ryouchinsa** [comment]
Currently, the image path In the CSV file should include the full path.

```
path,annotations
/Users/name/documents/images/sample.jpg,
```

Is your CSV file include the image full path?

You might expect that importing should read from the "Open folder" path + image path in the CSV file.

Let us know your opinion.

**Comment by ryouchinsa** [comment]
Fixed the problem when you import the CSV file from the image file name.
When the current folder is the same as the image folder, the "path" could be the image file name.
```
path,annotations
sample.jpg,
```
The new update version 2.28 was released.

**Comment by powderscotty** [comment]
in the csv file the path is given like this: 
/Users/name/Documents/images/0292.jpeg

the latest version is now installed, but the application now is terminated when importing the csv file. 

it seems the program is very sensitive to any alternations: somehow in the annotations the ' was replaced by " and that creates the error message or lets the program crash. 

maybe on the help page it would be helpful to specify the exact connotations needed to be imported? that could be valuable for those not reimporting, but creating the annotations with some other process. 

many thanks for your support!!!

**Comment by ryouchinsa** [comment]
The new update version 2.31 was released.

Updated the exporting and  importing CSV format to fix the problem when label name includes single-quote or double-quotes.
https://rectlabel.com/help#xml_to_csv

```
path,annotations
/Users/ryo/Desktop/test_annotations/test_data/26073093-275503062977108-7595223473371217920-n_2.jpg,'[{"label":"bag''s","type":"rectangle","coordinates":{"x":179,"y":169,"width":144,"height":138}},{"label":"boots \"A\"","type":"rotated_box","coordinates":{"cx":405,"cy":170,"width":144,"height":138,"rot":0.474627}},{"label":"flats","type":"polygon","coordinates":{"x1":136,"y1":463,"x2":205,"y2":374,"x3":343,"y3":405,"x4":276,"y4":506}},{"label":"glasses","type":"cubic_bezier","coordinates":{"x1":397,"y1":467,"x2":466,"y2":378,"x3":604,"y3":409,"x4":537,"y4":510}},{"label":"line","type":"line","coordinates":{"x1":133,"y1":651,"x2":229,"y2":561}},{"label":"point","type":"point","coordinates":{"x1":456,"y1":596}},{"label":"image","type":"polygon","coordinates":{}},{"label":"person","type":"pixels","id":0}]'
...
```
For the annotations, use single-quote to surround the JSON string.
In the JSON string, use double-quotes to surround each string.
Double-quotes in the label name is escaped with backslash. " => \\"
Single-quote in the label name is escaped with double single-quotes. ' => ''
This works for pandas.read_csv.
```
csv = pd.read_csv(csv_file, quotechar='\'', doublequote=True, converters={'annotations':JSONParser})
```

convert_csv_to_sframe.py is updated, too.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/convert_csv_to_sframe.py
