### ISSUE TITLE
Changing folder causes annotations to be used on wrong images

### ISSUE THREAD

**Issue by turbogeek** [ryouchinsa/Rectlabel-support#75]
When I change folders it seems that the file to annotations are by index and not path. The results is that there are the wrong images related to the wrong bounding box.

To recreate:
1) set folder
2) mark rectangles
3) change folders
4) some images will have rectangles but the wrong image

What should happen is that we should be able to change the path many times for one session. The reason is that I have many folders with my data categorized and should not have a single folder.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

![2019-01-14 15 46 07](https://user-images.githubusercontent.com/1954306/51099365-8c5f1e80-1813-11e9-89b2-6c5c151c4a60.png)

1. Open folder dialog
2. Change Images Folder
3. Change Annotations Folder

This is working in our environment.

> 1. set folder
You changed both Images Folder and Annotations Folder.

> 3. change folders
You changed to another Images Folder and another Annotations Folder.

> 4. some images will have rectangles but the wrong image
What does this mean?
Could you show us some screenshots or example xml files?
