### ISSUE TITLE
rotate does not work

### ISSUE THREAD

**Issue by turbogeek** [ryouchinsa/Rectlabel-support#76]
Rotate does not seem to work

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Rotate box
Change the mode to "Rotate".
Drag up or down on the box to rotate the box.
https://rectlabel.com/help#rotate_box

Rotate image
"Rotate image right" rotates the image by 90 degrees clockwise.
"Rotate image left" rotates the image by 90 degrees counter-clockwise.
https://rectlabel.com/help#rotate_image
