### ISSUE TITLE
Changing directories is broken

### ISSUE THREAD

**Issue by turbogeek** [ryouchinsa/Rectlabel-support#77]
Changing directories and clicking to view the folders requires the user to close the change folder dialog before the file dialog can be used. The changes also do not seem to take place until the change folder dialog is reopened and closed.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

![2019-01-14 15 46 07](https://user-images.githubusercontent.com/1954306/51099365-8c5f1e80-1813-11e9-89b2-6c5c151c4a60.png)

1. Open folder dialog
2. Change Images Folder
3. Change Annotations Folder
4. Press OK button

This is working in our environment.

Could you show us some screenshots?
