### ISSUE TITLE
Export to YOLO not working

### ISSUE THREAD

**Issue by ilmonteux** [ryouchinsa/Rectlabel-support#78]
Just started using this: I have a folder with 5 images.
Annotating them with RecLabel creates one XML file for each, with correct information in them, but clicking `File > Export XML filest to YOLO txt` results in empty txt files (0 bytes). 
`Export XML to CSV` seems to work.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

There is the "class_index" in the YOLO text format.
https://rectlabel.com/help#xml_to_yolo
```
class_index center_x center_y width height
0 0.511161 0.144792 0.103795 0.095833
```

This is the index of the label name in the objects table.
If the label name in your xml file could not be found in the objects table, we skip exporting the label name.

You can export the objects table as .names file for YOLO.
https://rectlabel.com/help#yolo_names
```
car
plate
person
dog
```

At first, could you set up your objects table on the settings dialog?
After that, label each box selecting an object on the label dialog.


Objects table on the settings dialog.
https://rectlabel.com/help#objects
![objects](https://user-images.githubusercontent.com/1954306/51452462-d39e5f80-1d7d-11e9-9361-7b8271be1707.jpg)

**Comment by ryouchinsa** [comment]
Now we show the warning that label names are not found on the objects table when you export YOLO text files.

![2019-01-31 6 52 20](https://user-images.githubusercontent.com/1954306/52015291-00443b00-2525-11e9-9254-f43a13af8e0f.png)

**Comment by ilmonteux** [comment]
Thank you very much, specifying the objects table as you described it works!
