### ISSUE TITLE
export annotations into COCO JSON format error

### ISSUE THREAD

**Issue by moseswmwong** [ryouchinsa/Rectlabel-support#79]
Hi, I am testing your software within the two week trial period. I downloaded your software on MacOS, use 'Create Polygon' to outline a snowman from some images, and use RectLabel's export feature 'Export XML files to COCO JSON files' and take images and this json file to check on Ubuntu 16.04 running COCO API PythonAPI pycocodemo.py to check the image and its instance annotation but get ugly output like the attached image. Failed.

*image deleted*

The COCO API python program pycocodemo.py is a modified version base on this python notebook:
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoDemo.ipynb

The modification I made is simply point to local test dataset which is a coco_val2014 downloaded from cocodataset.org. When I run my modified version pycocoDemo.ipynb over images and corresponding coco_val2014 instances_*.json files, everything display perfectly. Furthermore, since I cannot find person_keypoints_*.json output, nor captions_*.json output from RectLabel, therefore I comment out pycocoDemo.ipynb code related to person keypoints and captions, focus only to see how json generated from RectLabel works, but as you see in the attached image it does not work. 

Observation of problem: straight marks appears sideways which looks like a snowman, repeated a few time along vertical axis. I suspect the RLE decode is not correct here. Please help! Thanks!

Furthermore, I notice that pycocoDemo.ipynb try to display supercats, but there is no keyword for super category. I assme this can be skipped, and training using JSON without any super category defined still works fine, right?

Thanks so much!

----
UPDATE
I used another annotation tool and generated the following and it passed pycocoDemo.ipynb display the snowman with annotation correctly, here is the JSON generated, and it is big difference from RectLabel output

{"images": [{"file_name": "images/davi_0_1.jpg", "id": 0, "height": 1080, "width": 1920}, {"file_name": "images/davi_2_71.jpg", "id": 0, "height": 1080, "width": 1920}], "annotations": [{"segmentation": [[1162.12, 12.85, 1284.22, 14.39, 1367.39, 62.29, 1376.24, 154.99, 1323.15, 215.24, 1459.41, 331.11, 1459.41, 654.01, 1468.26, 986.18, 1186.89, 1054.16, 1059.48, 796.15, 995.78, 776.07, 967.46, 372.83, 1117.88, 306.39, 1163.89, 239.96, 1107.26, 46.84, 1163.89, 9.76, 1162.12, 12.85]], "area": 186839.97, "iscrowd": 0, "image_id": 0, "bbox": [1468.26, 1054.16, 967.46, 9.76], "category_id": 2, "id": 0}, {"segmentation": [[491.44, 12.85, 491.44, 332.66, 1162.12, 332.66, 1162.12, 12.85, 491.44, 12.85]], "area": 107243.94, "iscrowd": 0, "image_id": 1, "bbox": [1162.12, 332.66, 491.44, 12.85], "category_id": 2, "id": 1}], "categories": [{"name": "background", "id": 1},{"name": "person", "id": 2},{"name": "snowman", "id": 3}]}

The key differences are
1. Segmentation is a list of points, but RectLabel created counts="dWi2c0oi04M3L3M5L3N2M4L3N2BdN_WO`1^h0cN_WO`1]h0................................" (*very long and cannot read)
2. This also output bbox with x, y, width, height.

FINALLY, the best example must be this COCO JSON file segmentation session extracted from coco_val2014.json downloaded from cocodatasets.org which is also working well with my Machine Learning platform, so here it is

{"segmentation": {"counts": [3912, 10, 363, 18, 356, 23, 301, 10, 25, 10, 5, 27, 296, 16, 19, 16, 1, 30, 292, 20, 15, 50, 289, 24, 11, 53, 287, 26, 9, 55, 285, 29, 6, 57, 283, 32, 3, 59, 281, 34, 1, 60, 261, 11, 8, 97, 257, 17, 5, 98, 254, 21, 2, 99, 252, 124, 251, 126, 249, 127, 248, 128, 247, 129, 246, 130, 246, 130, 245, 131, 244, 132, 244, 132, 244, 132, 243, 133, 243, 131, 1, 1, 243, 127, 249, 99, 1, 22, 254, 97, 5, 16, 257, 95, 9, 12, 259, 93, 13, 10, 259, 92, 17, 7, 259, 90, 21, 5, 259, 88, 26, 2, 260, 86, 289, 84, 291, 82, 294, 79, 297, 77, 298, 47, 1, 27, 301, 47, 2, 23, 304, 46, 5, 19, 306, 46, 7, 14, 309, 45, 9, 10, 312, 44, 13, 5, 314, 43, 333, 42, 334, 40, 336, 40, 336, 40, 336, 40, 336, 40, 337, 38, 338, 36, 341, 33, 343, 30, 347, 26, 351, 23, 353, 20, 357, 16, 361, 13, 364, 9, 369, 4, 373, 1, 66562, 7, 33, 6, 327, 12, 27, 11, 324, 15, 21, 18, 69, 2, 249, 19, 14, 25, 64, 7, 245, 23, 7, 31, 60, 11, 243, 64, 55, 15, 241, 66, 28, 2, 21, 19, 239, 69, 19, 20, 7, 23, 237, 71, 11, 58, 235, 74, 2, 66, 233, 144, 232, 144, 231, 146, 229, 147, 229, 148, 227, 149, 227, 149, 227, 150, 225, 151, 225, 84, 2, 65, 225, 82, 6, 63, 225, 80, 23, 48, 225, 80, 25, 46, 225, 81, 26, 44, 225, 82, 26, 43, 225, 83, 27, 41, 225, 88, 24, 39, 225, 92, 21, 38, 225, 97, 16, 38, 225, 98, 15, 38, 225, 99, 14, 38, 224, 102, 13, 37, 224, 103, 11, 38, 224, 109, 2, 41, 224, 152, 224, 152, 224, 152, 224, 152, 224, 152, 224, 152, 224, 152, 224, 152, 224, 152, 224, 152, 224, 16, 2, 132, 226, 15, 5, 127, 229, 14, 8, 124, 230, 15, 8, 122, 232, 15, 7, 121, 233, 16, 5, 121, 234, 17, 4, 120, 236, 17, 6, 117, 236, 18, 8, 113, 238, 18, 8, 112, 238, 18, 9, 110, 240, 18, 8, 110, 240, 18, 9, 109, 241, 18, 9, 108, 241, 18, 10, 107, 242, 20, 8, 106, 243, 20, 8, 105, 244, 21, 5, 106, 244, 22, 4, 106, 245, 22, 3, 106, 245, 23, 1, 106, 247, 127, 249, 126, 251, 120, 1, 3, 253, 119, 257, 119, 258, 117, 260, 117, 260, 117, 260, 116, 262, 114, 263, 112, 266, 98, 281, 94, 286, 102, 280, 95, 282, 94, 283, 94, 282, 94, 281, 96, 280, 96, 279, 97, 278, 98, 276, 100, 274, 102, 272, 104, 271, 105, 270, 107, 268, 109, 266, 110, 265, 111, 263, 113, 261, 115, 260, 117, 258, 119, 256, 120, 255, 115, 1, 5, 254, 116, 259, 118, 258, 118, 257, 120, 255, 122, 254, 122, 253, 124, 252, 124, 252, 124, 251, 126, 250, 126, 250, 127, 248, 130, 246, 131, 245, 132, 243, 134, 242, 59, 15, 60, 242, 58, 16, 61, 241, 57, 17, 61, 241, 57, 17, 61, 241, 57, 18, 61, 240, 57, 17, 62, 240, 56, 16, 64, 240, 56, 13, 67, 240, 56, 11, 69, 240, 57, 8, 71, 240, 62, 1, 73, 240, 136, 240, 136, 240, 136, 240, 137, 239, 137, 240, 136, 240, 136, 240, 136, 241, 135, 241, 135, 242, 134, 242, 134, 243, 133, 243, 133, 244, 132, 244, 132, 245, 131, 246, 130, 247, 128, 249, 127, 250, 125, 252, 124, 253, 123, 254, 121, 257, 47, 2, 69, 259, 32, 5, 7, 7, 26, 3, 37, 261, 3, 2, 4, 13, 6, 23, 17, 13, 33, 286, 2, 26, 12, 20, 29, 316, 9, 25, 25, 321, 3, 29, 22, 322, 2, 30, 21, 355, 19, 357, 18, 358, 16, 370, 3, 32544], "size": [376, 500]}, "area": 27277, "iscrowd": 1, "image_id": 50149, "bbox": [10, 41, 403, 152], "category_id": 52, "id": 9.052000501e+11}, 

The key difference from RectLabel output
1. The square bracketed data after "counts" are comma separated integers, but data follows by "counts" outputt from RectLabel was "dWi2c0oi04M3L3M5L3N2M4L3N2BdN_WO`1^h0cN_WO`1]h0................................" (*very long and cannot read)
2. iscrowd equals to 1, I do not know if only this record is like that or whatsoever

Thanks!

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Look at the COCO JSON Object Detection data format.
http://cocodataset.org/#format-data
```
"segmentation" : RLE or [polygon],
```

RLE means the mask image is encoded using run length encoding.
RLE can have the same content as the gray png image.
RLE can represent much more than polygon.
So that RectLabel saves the RLE data.

This is an example how to read the COCO JSON file and check the mask images are correctly decoded.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/checkReadCOCOMask.py

We checked our COCO JSON file worked in the code below.
This code is to convert the COCO JSON file to the tfrecord file for tensorflow.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_coco_tf_record.py

To decode the RLE and use the mask images in your python code, use the code in the code below.
https://rectlabel.com/help#xml_to_coco
```
binary_mask = mask.decode(object_annotations['segmentation'])
mask_shape = binary_mask.shape
binary_mask = np.ravel(binary_mask, order='F')
binary_mask = binary_mask.reshape(mask_shape, order='C')
```

The problem is our RLE data is not working in the simple example.
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoDemo.ipynb

To calculate the RLE data, we are using the c-based coco api.
https://github.com/cocodataset/cocoapi/blob/master/common/maskApi.c

The problem would be in interpreting the RLE data as C-order or Fortran-order.
Currentyly to decode the RLE data from RectLabel, you have to change the array order in your python code as described above.

We would investigate how to change the array order in our c-based RectLabel code.

Let us know your opinion.

This is an example of the RLE data is correctly decoded through our example code.

```
{
  "images" : [
    {
      "id" : 1,
      "file_name" : "tuce-311434.jpg",
      "width" : 1110,
      "height" : 1440
    }
  ],
  "annotations" : [
    {
      "area" : 144238,
      "segmentation" : {
        "size" : [
          1440,
          1110
        ],
        "counts" : "PXZi0m3lm0]1POj0\\Od0^O`0C<E;H7H8J5J6J6I6K6J5K4K6K4K6K4L3L5L3M4K4M2N3L4M3M2N3M2M4M2N2N2N3M2N2N2N3M2N2N2N2N2N2N3M2N2WOfCS[O\\<kd0fCS[O\\<kd0fCS[O\\<ld0eCR[O]<md0cCR[O_<md0aCR[Ob<ld0^CS[Od<ld0d0O1O1O1O1O1O1O1O2N100XO_BY\\Ob=]c0Q1gMiAk_O^>l?RBf_OU>S`0XBb_Om=Y`0[2L5L3M3M4M2N3M3N2N3L4M3M3M3M3M3M3M3M3M3M2N4L4K8I7I6J5K4L4L3M4L3M4L3M4L4L3M4L4L4L4L5K4L4L4L4L4L3M1O00102N2H6L3O2O000O1O2O000000000001O10O0001O001O001O00010O00001O0000101N1O3M2N3M3`XOQETg0Z;N2N3M3M2N100O1O001O001O00010O0000001O0000000001O00000001O00000Z[OXD^b0h;a]O^DZb0b;f]OfDRb0Z;n]OiDoa0W;P^OkDoa0V;P^OkDoa0U;Q^OkDoa0U;P^OmDoa0S;Q^OoDma0R;R^OREja0n:U^OWEga0i:Y^O\\Eba0e:]^O_E_a0a:`^OeE[a0[:e^OiEWa0X:g^OmEUa0S:k^ORFPa0o9o^OUFm`0k9R_O[Fi`0f9V_O^Fe`0c9Z_OcF``0_9__OfFX`0^9g_OgFn?a9P@eFd?c9[@cFW?f9g@`Fl>i9RA^FV>T:iASFn=Q:PBVFh=n9TBZFe=h9XB_Fb=d9ZBdF^=`9^BfFj1oJk8^>UElFk1jJk8`>PEnFQ2fJi8bd0TGb[OT8Ue0iGQ[Og7[e0VHnZOc6SO_Gif0m1_ZOb6_e0]IP[O_6fd0_Io[OR6mc0mIl\\O<gMk1Ye0iM^@U2]?kMg@U2U?jMn@X2n>hMTAY2j>fMWA[2g>dM[A\\2d>dM]A[2c>eM]A\\2b>cM_A]2a>cM`A\\2`>dM`AP1]IQNTe0n0`Ao0cInMmd0S1`An0gIlMjd0T1`Ao0kIiMed0X1`An0oIfMbd0\\1_Am0SJcM`d0^1^An0R`0ROo_Om0R`0QOo_On0R`0QOo_Oo0R`0POn_Oo0S`0POn_OP1S`0nNn_OQ1T`0nNl_OR1U`0lNl_OS1V`0kNk_OT1W`0jNj_OV1W`0gNl_OW1W`0fNj_OY1Y`0cNi_O]1Y`0_Ni_O`1[`0ZNi_Od1]`0RNh_Om1ah0O2L3K5M4M2O2N101N101O0O2O1N101O1N2N2O1N2N2N2N3L4M3K7HTa]="
      },
      "iscrowd" : 0,
      "image_id" : 1,
      "bbox" : [
        234,
        747,
        782,
        292
      ],
      "category_id" : 1,
      "id" : 1
    }
  ],
  "categories" : [
    {
      "name" : "car",
      "id" : 1
    },
    {
      "name" : "plate",
      "id" : 2
    },
    {
      "name" : "person",
      "id" : 3
    }
  ]
}
```
![1_0](https://user-images.githubusercontent.com/1954306/51571796-8ee20800-1ee6-11e9-963a-49f2eec1fd73.png)

**Comment by moseswmwong** [comment]
Thank you for the detail explanation! Now I understand the JSON file is OK, and you had decided to use RLE because it is a better way to represent the segmentation.

As you already explained the pycocoDemo.ipynb is a simple example that would not work directly with the JSON file generated by RectLabel, and I need to make a program to convert the RLE part of the JSON fie in order for me to proceed forward.

However, I do not want to do this extra programming step, since pycocoDemo.ipynb is just a checkpoint I ask myself to validate the JSON file, and as you explained it is too simple and cannot handle RLE, but according to cocodatasets.org the COCO JSON should support RLE, then, I think I should simple skip this pycocoDemo.ipynb and more forward, because the next step for me is to use the JSON file and the corresponding images as a new dataset for Facebook Detectron training. 

As far as I understand Detectron require COCO JSON format defined by cocodataset.org. So now my question is, did you try create a new dataset using json file genereated by RectLabel and directly feed it to Facebook Detectron and what is the result? 

If not, do you think directly provide the JSON file genereated by RectLabel works with Detectron or not?

Thanks so much!

**Comment by ryouchinsa** [comment]
At first, for the pycocodemo, with a simple modification, we checked it works.

In the pycocotools code below, 
https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py

Replace code at Line 268:
m = maskUtils.decode(rle)

With the code below.
m = maskUtils.decode(rle)
m_shape = m.shape
m = np.ravel(m, order='F')
m = m.reshape(m_shape, order='C')

Then with the sample code below, the mask image is decoded correctly.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/checkPycocoDemo.py

![2019-01-23 9 50 29](https://user-images.githubusercontent.com/1954306/51575374-3bc38180-1ef5-11e9-893f-6653a2f56d5f.png)

We tested our mask images on the Mask R-CNN training on Tensorflow.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/instance_segmentation.md

For the facebook Detectron, we have not tested the training with our COCO JSON file.
We would check soon.

**Comment by moseswmwong** [comment]
I changed pycocoDemo and worked well.

However, I use the JSON file and corresponding image files without making any change to Detectron and failed. The reason is segms.py line 60 "mask = mask[:, ::-1, :]". I digged into the code and tried to change to conform to your request like I did with pycocoDemo but no luck!

Here is what I did locally with my forked Detectron

[original segms.py](https://github.com/moseswmwong/Detectron/blob/master/detectron/utils/segms.py)



```
def flip_segms(segms, height, width):
    """Left/right flip each mask in a list of masks."""
    def _flip_poly(poly, width):
        flipped_poly = np.array(poly)
        flipped_poly[0::2] = width - np.array(poly[0::2]) - 1
        return flipped_poly.tolist()

    def _flip_rle(rle, height, width):
        if 'counts' in rle and type(rle['counts']) == list:
            # Magic RLE format handling painfully discovered by looking at the
            # COCO API showAnns function.
            rle = mask_util.frPyObjects([rle], height, width)

##################################################################### MODIFIED ACCORDING TO RECTLABEL ############### 2019.01.23  email from notification_at_github.com Ryo Kawamura to moseswmwong at hotmail.com TEST PASSED . RLE created by Rectlabel worked and resilience test passed

#IMPORTANT WARNING 
#  the above code does not seems compatible should the case frPyObjects is applied, anyways get moving first...

###### NEW

        mask = mask_util.decode(rle)
	mask_shape = mask.shape
	mask = np.ravel(mask, order='F')
	mask = mask.reshape(mask_shape, order='C')

###### ORIGINAL

#       mask = mask_util.decode(rle)

#####################################################################################################################

        mask = mask[:, ::-1, :]
        rle = mask_util.encode(np.array(mask, order='F', dtype=np.uint8))
        return rle

    flipped_segms = []
    for segm in segms:
        if is_poly(segm):
            # Polygon format
            flipped_segms.append([_flip_poly(poly, width) for poly in segm])
        else:
            # RLE format
            flipped_segms.append(_flip_rle(segm, height, width))
    return flipped_segms
```



You asked my suggestion, my suggestion is to add a configuration in Rectlabel when checked, it open in the correct order Detectron expected, as according to segms.py here.

Thanks! 

Look forward!

**Comment by ryouchinsa** [comment]
For the quick update, we added "Export segmentation as polygon" checkbox when you export the COCO JSON file.
To export the segmentation as polygon, check on the box.
Otherwise the segmentation is exported as RLE.

![2019-01-24 20 42 56](https://user-images.githubusercontent.com/1954306/51675991-a6b9a900-2018-11e9-8f03-297f66658db4.png)

The polygon format worked on the pycocoDemo.

Today we submitted the new update 2.37.
When the new update is released, we will let you know.

For the RLE format problem, we would investigate soon.

![2019-01-24 20 42 00](https://user-images.githubusercontent.com/1954306/51675998-a91c0300-2018-11e9-81cd-56da7c87be07.png)

```
{
  "images" : [
    {
      "id" : 1,
      "file_name" : "tuce-311434.jpg",
      "width" : 1110,
      "height" : 1440
    }
  ],
  "annotations" : [
    {
      "area" : 144238,
      "iscrowd" : 0,
      "id" : 1,
      "image_id" : 1,
      "category_id" : 1,
      "segmentation" : [
        [
          304,
          972,
          288,
          950,
          285,
          929,
          280,
          915,
          272,
          911,
          265,
          908,
          260,
          909,
          252,
          907,
          245,
          904,
          241,
          900,
          239,
          893,
          236,
          888,
          236,
          886,
          234,
          884,
          234,
          882,
          234,
          879,
          236,
          878,
          236,
          875,
          239,
          874,
          241,
          873,
          247,
          872,
          245,
          871,
          243,
          868,
          243,
          860,
          243,
          851,
          244,
          839,
          246,
          827,
          259,
          820,
          280,
          817,
          301,
          817,
          325,
          820,
          333,
          819,
          351,
          816,
          371,
          815,
          379,
          816,
          378,
          811,
          378,
          806,
          378,
          800,
          381,
          797,
          385,
          797,
          390,
          797,
          393,
          798,
          395,
          801,
          396,
          804,
          404,
          797,
          415,
          786,
          428,
          774,
          448,
          759,
          456,
          753,
          488,
          749,
          553,
          747,
          610,
          747,
          659,
          748,
          717,
          755,
          760,
          765,
          781,
          774,
          800,
          788,
          829,
          814,
          848,
          828,
          872,
          836,
          890,
          842,
          915,
          846,
          944,
          854,
          988,
          865,
          997,
          868,
          1000,
          871,
          1006,
          875,
          1009,
          895,
          1013,
          922,
          1015,
          953,
          1010,
          961,
          997,
          963,
          981,
          965,
          971,
          966,
          958,
          967,
          948,
          974,
          934,
          975,
          920,
          976,
          904,
          977,
          888,
          977,
          885,
          978,
          885,
          979,
          887,
          979,
          889,
          978,
          894,
          979,
          895,
          980,
          903,
          980,
          918,
          983,
          932,
          987,
          934,
          993,
          930,
          998,
          915,
          994,
          892,
          992,
          881,
          1004,
          871,
          1016,
          859,
          1020,
          849,
          1037,
          821,
          1038,
          803,
          1007,
          793,
          983,
          734,
          982,
          672,
          981,
          599,
          976,
          579,
          975,
          565,
          1007,
          532,
          1012,
          517,
          992,
          509,
          976,
          461,
          966,
          417,
          957,
          386,
          950,
          377,
          947,
          374,
          943,
          367,
          942,
          356,
          940,
          352,
          943,
          346,
          959,
          332,
          972
        ]
      ],
      "bbox" : [
        234,
        747,
        782,
        292
      ]
    }
  ],
  "categories" : [
    {
      "name" : "car",
      "id" : 1
    },
    {
      "name" : "plate",
      "id" : 2
    },
    {
      "name" : "person",
      "id" : 3
    }
  ]
}
```

**Comment by moseswmwong** [comment]
Thanks a lot! The polygon option should be the right way to solve all the above problems.

Look forward to the new release!

**Comment by ryouchinsa** [comment]
The new update version 2.37 was released.

- Added "Export segmentation as polygon" checkbox when you export the COCO JSON file.
To export the segmentation as polygon, check on the box.
Otherwise the segmentation is exported as RLE.
https://rectlabel.com/help#xml_to_coco
