### ISSUE TITLE
only check for receipt on occasion? Offline mode?

### ISSUE THREAD

**Issue by bw4sz** [ryouchinsa/Rectlabel-support#81]
Just an idea, but i'm going on a long flight and would like to label images. I've found that i need to be online for it to check the app store to confirm my receipt every time it opens. This seems gratuitous. Maybe check once a month? I'm sure there are other users in need of offline use.

Thanks for a great tool.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

We understand your use-case that you want to label on flight.

When RectLabel launches, we send the encryped purchase receipt to the Apple's server to decode it.
This is how we could know whether you bought the full app or 2-week free trial.

Without network connections, we have to know your purchase state using another method.
Let us think whtether there is a good way.

**Comment by cipri-tom** [comment]
Well, you can only check once, in the beginning, and then store securely that the app was bought :) . Thank you!

**Comment by ryouchinsa** [comment]
Now You can label offline. When you buy in-app purchase items, you need network connection.
The new update version 2.67 was released.
