### ISSUE TITLE
Generating TFRecord files

### ISSUE THREAD

**Issue by kkalle** [ryouchinsa/Rectlabel-support#83]
Can you please provide step by step instructions for generating TFRecord files? How to save annotations in RectLabel app, how to install the converted python script and what specific command to run on OSX terminal to generate the TFRecord file? Thank you very much.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Output files from RectLabel.

1. Press "Settings" and add object names on the "Objects" table.
2. Press "Open folder" to open Images Folder and Annotations Folder.
2. Draw a box and select an object from the "Objects" pop-up button.
4. Press "Save" button to save the XML file in the annotations folder.
5. Press "Export train, val, and text.txt".
5. Press "Export label map for Tensorflow".
6. If we you train Mask-RCNN, press "Export mask images for all images" and specify the current annotations folder to save.

How to convert to the TFRecord file.
https://rectlabel.com/help#tf_record

7. Download models repository. https://github.com/tensorflow/models
8. Install Object Detection API https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
9. Change the current directory to "models/research/".
10. Put the python code below to "models/research/object_detection/dataset_tools/" folder.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_pascal_tf_record.py
11. On the terminal, execute the python code.
```
python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py \
    --images_dir="${IMAGES_DIR}" \
    --image_list_path="${IMAGE_LIST_PATH}" \
    --label_map_path="${LABEL_MAP_PATH}" \
    --output_path="${OUTPUT_PATH}" \
    --include_masks

IMAGES_DIR: the current images folder.
if your annotations folder is not images_folder/annotations, you have to specify --annotations_dir which is the relative annotations path from the images folder.
IMAGE_LIST_PATH: one of the output files from "Export train, val, and text.txt".
if you train Mask-RCNN, add --include_masks otherwise you can remove it.
```

**Comment by kkalle** [comment]
Thank you very much for the quick reply! Much appreciated. It seems to work except that I get a 'Image format not JPEG' error as all my images are PNGs. Is there an easy way around this or do I have to convert all images to JPEGs and annotate them again? My images are also original size photos from iPhoneX so would it make sense anyway to compress them a bit?

**Comment by kkalle** [comment]
Thank you for the quick reply. Much appreciated! Somehow I don't seem to get the path variables right. Could you provide sample values for those environment variables?

**Comment by kkalle** [comment]
Thank you! Much appreciated.
