### ISSUE TITLE
Annotating files with the same name with different extensions causes unexpected behavior

### ISSUE THREAD

**Issue by alono88** [ryouchinsa/Rectlabel-support#84]
The xml files that are generated during annotation creation are named using the filename without the extension. When two files have the same filename but different extension are labeled, only one xml file is kept, instead of two. There is no indication of that event and users might get confused.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Looking at the Tensorflow sample code, they assume that the image file name without the extension corresponds to the xml file name.
`path = os.path.join(annotations_dir, example + '.xml')`
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py

If you do not agree with this idea, let us know the detailed use-case that two image files have the same filename but different extension.

**Comment by alono88** [comment]
This case was a mistake on my behalf, however I believe there should be some form on notification regarding collision between XML files. It seems that tensorflow deals with this situation better than pytorch (maskrcnn-benchmark repo), which showed an error regarding an image with zero bounding boxes.

**Comment by ryouchinsa** [comment]
On which timing do you want the notification?
When you open the images folder, or when you change the image to the same image file name except the extension, or when you export to some format.

**Comment by alono88** [comment]
I think it would be best to notify the user once he opens the images folder. While some formats currently might be OK with this, its best to let the user know as soon as possible this might cause problems.

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

In the next update, when you open folder, we would show the warning dialog that there are duplicated image names except extension.

![2019-02-23 8 55 27](https://user-images.githubusercontent.com/1954306/53277737-cd1e5180-3748-11e9-9871-5551f57c5b81.png)

![2019-02-23 8 54 41](https://user-images.githubusercontent.com/1954306/53277739-d4ddf600-3748-11e9-8dfc-c1ae8b4449c7.png)

**Comment by alono88** [comment]
Thank you very much!

**Comment by ryouchinsa** [comment]
The new update version 2.52 was released.
Improved that when you open folder, we would show the warning dialog that there are duplicated image names except the extension.
Let us know your opinion.
