### ISSUE TITLE
From IBM: Multi-label select

### ISSUE THREAD

**Issue by waddahAldrobi** [ryouchinsa/Rectlabel-support#85]
Can you add a feature for the multi-select label to move, copy, and paste multiple labels at once. 
That would help a lot for when you have many annotations in one image... 

Thanks

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
Currently you can multi-select and delete boxes.
We would add the "Duplicate" to the menu.
When you drag one of multi-selected boxes, you would be able to move all boxes.
Does this make sense for you?

![2019-02-22 7 40 14](https://user-images.githubusercontent.com/1954306/53206928-9f1c0d00-3675-11e9-8fe9-6e19042cd45b.png)

**Comment by waddahAldrobi** [comment]
Hey, 

I have RectLabel version 2.51, and when I multi select (2 or 3 boxes) I cannot move them all at once. 
When I drag only the one I'm dragging moves and the rest are deselected

Also, instead of copy, I meant a copy/paste feature across images. 

Thanks

**Comment by ryouchinsa** [comment]
> I have RectLabel version 2.51, and when I multi select (2 or 3 boxes) I cannot move them all at once.

We meant in the next update you will be able to move multiple-selected boxes.
We understand what you want for multiple-select move.

![multiple_select_move](https://user-images.githubusercontent.com/1954306/53274490-bc66df00-373a-11e9-96b2-72033eb5e7c3.gif)

> copy, and paste multiple labels at once.
That would help a lot for when you have many annotations in one image...

In one image, duplicate multiple-selected boxes would help.
In the next update, you will have this feature, too.

![multiple_select_duplicate](https://user-images.githubusercontent.com/1954306/53274549-f6d07c00-373a-11e9-8c81-3cf39db81f70.gif)

> I meant a copy/paste feature across images.

Did you try "Load previous image's labels"?
https://rectlabel.com/help#load_labels

You can copy all boxes from another image.
If you want to copy subset of boxes from another image, we have to add the copy/paste feature.
Do you have some good UI/UX idea how to implement on the current Rectlabel?

**Comment by ryouchinsa** [comment]
The new update version 2.52 was released.
Added "Move", "Rotate", and "Duplicate" when you multi-selected boxes.
Let us know your opinion.

**Comment by waddahAldrobi** [comment]
That's great to hear. The update hasn't shown on store yet, but I assume it will need some time. 

As for the UI/UX you asked about, 

I suggest creating a "copy to clipboard" and a "paste to clipboard", which can be copied from image 1 for example, and the pasted to image 2. 
Default in pasting is that all annotations are selected for, moving or rotating.

**Comment by ryouchinsa** [comment]
Thanks for your idea.

We are wondering whether copy/paste boxes feature really necessary or not.
In video annotations, users need the previous frame's annotations, so that we are supporting "Load previous image's labels".
Why do users have to copy/paste subset of annotations across images?
To implement a new feature, we have to understand the detailed use-case.

**Comment by waddahAldrobi** [comment]
I tried the multi-move, works great. 

Think of scene localization. If you have 20 cats in a corner, each labeled, and some other labeled animals in an image. Then in a different scene I have an already pre-labled image with a bunch of different animals from the previous but the same 20 cats in a different corner. 
Instead of loading all the labels from the previous image, and resetting my current labels, I could copy/paste the labels I want and move them to the right location.

(Analogy was due to signing an NDA)

**Comment by ryouchinsa** [comment]
Thanks for the details.
We would try to implement the copy/paste feature.

**Comment by ryouchinsa** [comment]
The new update version 2.55 was released.
- Added "Copy" boxes with command + C and "Paste" boxes with command + V across images.
https://rectlabel.com/help#copy_box

Let us know your opinion.

![copy_paste](https://user-images.githubusercontent.com/1954306/53688038-d2028700-3d80-11e9-9b94-533650db8dce.gif)

**Comment by waddahAldrobi** [comment]
That is awesome, 

My last request, something I realized while preparing data the other day. 
A feature of adding a custom angle rotation (I know there's left and right) for an image, along with its labels in the right place. 
(I did the geometry myself, but haven't written the script)

**Comment by ryouchinsa** [comment]
"Rotate image" is to adjust the 90 degrees rotation of digital cameras.
https://rectlabel.com/help#rotate_image

To fit the box to the object, use "Rotate box" feature.
https://rectlabel.com/help#rotate_box

**Comment by waddahAldrobi** [comment]
Ah, I that wasn't the request. 

I mean to be able to "Rotate Image" with a custom angle ... for example, to be able to rotate an image (assume it's a square) by 10 degrees. And have all the labels rotate along with the image to the right cx and cy position

**Comment by ryouchinsa** [comment]
We understand what you requested.

Again, "Rotate image" is to adjust the 90 degrees rotation of digital cameras.
It is not to adjust each box rotation.

To adjust each box rotation, select a box or multiple boxes and rotate them using "Rotate box" feature.

**Comment by waddahAldrobi** [comment]
Ah I see.
Alright then, you guys have been more than great. 
Thanks again.
