### ISSUE TITLE
turicreate annotations from video(image sequence)

### ISSUE THREAD

**Issue by romanoss** [ryouchinsa/Rectlabel-support#88]
Hi
Are there any plans to support generating annotations from image sequences that are generated automatically? I mean like the thingy that cvat is doing? This would be nice as generating larger datasets with annotations is really annoying.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Do you mean the Auto annotation feature on CVAT?
https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md

You have your own trained custom model and want to process your images with the model to generate the initial annotation files.

Basically our users are processing their images by themselves to generate the initial annotation files.

To support this feature on RectLabel, there are 2 options.
1. Run neural network module on the local app RectLabel. But it is not running on server such as CVAT.
2. Our users provide the api to process the image on their server and RectLabel posts each image to the api to generate annotation files.

For us, 2. would be preferable to implement.

Let us know your opinion.

**Comment by romanoss** [comment]
Hi,
Sorry for not being precise.
What I meant is that if I have a video and I generate a lot of images from it, I have the problem that I don't want to annotate each frame. In cvat one can annotate only some keyframes and the software interpolates the bounding boxes on the other frames and one can generate annotations for all frames this way. This would be a nice feature.

thx

**Comment by ryouchinsa** [comment]
Thanks for the details.

You mean the linear interpolation among image frames.

For video annotations, we are providing the "Load previous image's labels" feature.
But this feature might not be enough to increase the productivity for video annotations.
https://rectlabel.com/help#load_labels

Let us ask you some questions before implementing the feature.
If the number of objects are different in key frames, what kind of interpolation do you prefer?

Example:
Frame 1: box1
Frame 2: not labeled
Frame 3: box1, box2

**Comment by romanoss** [comment]
Thx for the quick reply!
lets say we have 100 frames which belong to a sequence.
In cvat the box lives for the whole sequence on the same place once it is defined.
if you delete it on frame x it is gone from this frame on.
if you move and/or resize it on frame x, the dimensions and coordinates of the box are adapted for the frames in between.
So in the end one has a sequence of coordinates and sizes for each box  along  the frame sequence, which can be used to generate an annotation file for each frame.

Maybe there are better ways but I am not an expert.

kind regards 
Roman

**Comment by romanoss** [comment]
Hi,
in fact when I think about your first proposal, I have a nice idea which should be possible without a lot of effort.
Just think about making it possible to attach a core ml (object detection) model file with a project. So one can easily ask the model for results (=boxes with labels and probability percentage) which can be drawn automatically as proposal and then taken over.
What do u think?

**Comment by ryouchinsa** [comment]
Thanks for your feedback.

For CVAT, we could install and check how it works in our environment.
Let us think how to implement the similar features.
If some frames do not have any annotations, it might be simple to interpolate from annotated frames.
But if we want to interpolate already annotated frames, we have to consider how to store key frame or not status for each image frame.

For coreml, we started investigating how to run object detection model such as mobilenet-ssd and yolo on RectLabel.

**Comment by romanoss** [comment]
Thx for the quick reply!

In fact, mixing existing normal annotation boxes and generated ones can get a bit complicated.
Maybe the core ml idea is easier.
Please let me know  if you make any progress with this.

kind regards
Roman

**Comment by romanoss** [comment]
maybe take a look at this:
https://www.figure-eight.com/platform/machine-learning-assisted-video-object-tracking/

**Comment by ryouchinsa** [comment]
The new update version 2.59 was released.

- Added "Load Core ML model", "Process the image using Core ML", and "Process all images using Core ML".
Automatically label images using Core ML model.
Your macOS version has to be GTE 10.13.
https://rectlabel.com/help#coreml_menu

![coreml](https://user-images.githubusercontent.com/1954306/54859263-896e3600-4d4e-11e9-905a-bed9e1b850a0.jpg)

Let us know your opinion.

**Comment by romanoss** [comment]
Wow, fast implementation.Thx
Unfortunately, I am running GTE 10.14 - hmm
Whats the problem with 10.14? I guess this is the reason I cannot find the CoreML menu items?

btw: the version string in the About RectLabel menu says 2.58 - a bit confusing

**Comment by ryouchinsa** [comment]
Core ML feature works with macOS 10.13 and 10.14.
Could you update RectLabel to the latest one on Mac App Store?
You can press Command + R on Update tab.

**Comment by romanoss** [comment]
Works now. App store tricked me.
The new feature works fine, with one problem.
The annotation adds the probability to the object label - which is nice in the GUI, but not in the XML file because it creates/generates a new class. 
I want to use the XML/CSV files to be an additional dataset for the next training run.
car-1.00 doesn't match the original car label for example.

Great work. Thx

**Comment by romanoss** [comment]
A nice aspect is, that one can easily see which objects are not classified well now and one can add additional BBoxes for these guys.

**Comment by ryouchinsa** [comment]
Thanks for your feedback.
In the next update, we would remove the confidence in the detected label name.

**Comment by ryouchinsa** [comment]
Improved so that detected label names using Core ML model include only label name without its confidence score.

![coreml](https://user-images.githubusercontent.com/1954306/55128856-71d0ec00-5158-11e9-99c0-bfec2a1650c9.jpg)

The new update version 2.60 was released.
