### ISSUE TITLE
Error with create TF record

### ISSUE THREAD

**Issue by kareemw9** [ryouchinsa/Rectlabel-support#89]
I'm getting the following error when running rectlabel_create_pascal_tf_record.py

I've put absolute paths in for my directories. See below:
> --images_dir="/home/folder/folder/folder/images/" \
> --anootations_dir="/home/folder/folder/folder/images/annotations" \
> --label_map_path="/home/home/folder/folder/folder/images//labelmaps/" \
> --output_path="/home/folder/folder/folder/images//outfile/"

Traceback (most recent call last):
  File "../models/research/object_detection/dataset_tools/rectlabel_create_pascal_tf_record.p
y", line 19, in <module>
    np.set_printoptions(threshold=np.nan)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/arrayprint.py", line 246, in set_pr
intoptions
    floatmode, legacy)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/arrayprint.py", line 93, in _make_o
ptions_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representa
tion

I'm running this on a google cloud tensorflow GPU instance.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

"label_map_path" and "output_path" are file paths and not directory paths.

Here is an example which does not have any errors.

```
IMAGES_DIR=/Users/ryo/Desktop/test_annotations/test_data_mask_png
ANNOTATIONS_DIR=/Users/ryo/Desktop/test_annotations/test_data_mask_png/annotations
IMAGE_LIST_PATH=/Users/ryo/Desktop/test_annotations/test_data_mask_png/train.txt
LABEL_MAP_PATH=/Users/ryo/Desktop/test_annotations/test_data_mask_png/label_map.pbtxt
OUTPUT_PATH=/Users/ryo/Desktop/test_annotations/test_data_mask_png/train.record

flags.DEFINE_string('images_dir', '', 'Full path to images directory.')
flags.DEFINE_string('annotations_dir', 'annotations', 'Relative path to annotations directory from images_dir.')
flags.DEFINE_string('image_list_path', 'train.txt', 'Full path to image list file which is one of the output files from "Export train, val, and test.txt".')
flags.DEFINE_string('label_map_path', 'label_map.pbtxt', 'Full path to label map file.')
flags.DEFINE_string('output_path', '', 'Full path to output TFRecord file.')
```

Export TFRecord for Tensorflow
https://rectlabel.com/help#tf_record

**Comment by ryouchinsa** [comment]
We removed the line from our python code.
```
np.set_printoptions(threshold=np.nan)
```
Could you try with the updated python code?
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_pascal_tf_record.py

**Comment by kareemw9** [comment]
Thanks I will check by running later today. In the meantime just to verify, for the label map and the output file do I need to create these prior to running the create file? Or does the create script create both files with the name I give it via the command?

**Comment by ryouchinsa** [comment]
For the label map, you have to export using "Export label map for Tensorflow" before running this python script.

The output file is created by this python script.

Export TFRecord for Tensorflow
https://rectlabel.com/help#tf_record

**Comment by kareemw9** [comment]
I've removed the original script and am now using the updated script. However, now I'm getting the following error: 
--images_dir="/home/folder/folder/folder/images/" 
--anootations_dir="/home/folder/folder/folder/images/annotations" 
--label_map_path="/home/home/folder/folder/folder/images/labelmaps/" 
--output_path="/home/folder/folder/folder/images/outfile/train.record"

  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 7
    <!DOCTYPE html>

**Comment by ryouchinsa** [comment]
1. Could you show us the whole error messages?
2. Could you give us the example data to reproduce the same problem in our environment?
We mean, for example, an image, a xml file, and the label map file.
We would check whether it would have any errors when converting to the TFRecord file.

**Comment by kareemw9** [comment]
Thanks for getting back. I emailed a zip file of the requested information to your support email.

Thanks,

**Comment by ryouchinsa** [comment]
Thanks for the example data.

We executed our python code below.
```
IMAGES_DIR=/Users/ryo/Desktop/test_annotations/support
ANNOTATIONS_DIR=/Users/ryo/Desktop/test_annotations/support/annotations
IMAGE_LIST_PATH=/Users/ryo/Desktop/test_annotations/support/train.txt
LABEL_MAP_PATH=/Users/ryo/Desktop/test_annotations/support/label_map.pbtxt
OUTPUT_PATH=/Users/ryo/Desktop/test_annotations/test_data_mask/train.record

python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py --images_dir="${IMAGES_DIR}" --annotations_dir="${ANNOTATIONS_DIR}" --image_list_path="${IMAGE_LIST_PATH}" --label_map_path="${LABEL_MAP_PATH}" `--output_path="${OUTPUT_PATH}"
```

Then, we had the error.
```
ValueError: Image format not JPEG]
```

If we comment out the code below from rectlabel_create_pascal_tf_record.py(Line 49 - 50), it works without any errors.

```
if image.format != 'JPEG':
        raise ValueError('Image format not JPEG')
```

Or you can use "Convert image size and format to jpg" to convert png files to jpg files.
https://rectlabel.com/help#resize_image

For the screenshot of your error, how about removing the first 9 lines from rectlabel_create_pascal_tf_record.py?
Comments might not be working in your environment.

```
r"""
python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py \
    --images_dir="${IMAGES_DIR}" \
    --annotations_dir="${ANNOTATIONS_DIR}" \
    --image_list_path="${IMAGE_LIST_PATH}" \
    --label_map_path="${LABEL_MAP_PATH}" \
    --output_path="${OUTPUT_PATH}" \
    --include_masks
"""
```

**Comment by kareemw9** [comment]
I downloaded the wrong file. wget instead of git clone. However i'm still receiving the below errors when running updated code:

 python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py
-- images_dir="/home/kareemwilliams7/data/data-kazwil/front/" 
--annotations_dir="/home/kareemwilliams7/data/data-kazwil/annotations/"
--label_map_path="/home/kareemwilliams7/data/labelmaps/" 
--output_path="/home/kareemwilliams7/data/outfile/train.record"

Traceback (most recent call last):
  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 146, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 128, in main
    image_files = dataset_util.read_examples_list(FLAGS.image_list_path)
  File "/home/kareemwilliams7/models/research/object_detection/utils/dataset_util.py", line 59, in read_examples_list
    lines = fid.readlines()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 188, in readlines
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: train.txt; No such file or directory

When i run with sudo i get the below error: 

sudo python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py 
-- images_dir="/home/kareemwilliams7/data/data-kazwil/front/" 
--annotations_dir="/home/kareemwilliams7/data/data-kazwil/annotations/" 
--label_map_path="/home/kareemwilliams7/data/labelmaps/" 
--output_path="/home/kareemwilliams7/data/outfile/train.record"

Traceback (most recent call last):
  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 22,
 in <module>
    from object_detection.utils import dataset_util
ImportError: No module named object_detection.utils

**Comment by ryouchinsa** [comment]
Before starting these steps, be sure that you could set up Tensorflow Object Detection API in your environment.
https://github.com/tensorflow/models/tree/master/research/object_detection

Check these tutorials could work in your environment.

1. Object Detection Demo
https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
2. Training an object detector
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_pets.md

After that, follow these steps.

Export TFRecord for Tensorflow
https://rectlabel.com/help#tf_record

Again, the label map should be a file path.
```
--label_map_path="/home/kareemwilliams7/data/label_map.pbtxt"
```

**Comment by kareemw9** [comment]
Hi I deleted and reinstalled tensor flow object detection API just to be sure and the issue persists. I added a train.txt file and am now getting the following error:

(0, '"/home/kareemwilliams7/data/data-kazwil/front/file_1073.png"')
/home/kareemwilliams7/models/research/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
Traceback (most recent call last):
  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 146, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 140, in main
    tf_example = dict_to_tf_example(data, image_file, annotations_dir, label_map_dict, FLAGS.include_masks, FLAGS.ignore_difficult_instances)
  File "object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py", line 46, in dict_to_tf_example
    encoded_jpg = fid.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: "/home/kareemwilliams7/data/data-kazwil/front/file_1073.png"; No such file or directory

However this file exists as seen below:

ls /home/kareemwilliams7/data/data-kazwil/front/file_1073.png
/home/kareemwilliams7/data/data-kazwil/front/file_1073.png

**Comment by ryouchinsa** [comment]
If you could send us your sample images and xml files, we would check it could be converted to TFRecord file in our environment.

**Comment by ryouchinsa** [comment]
Your image file is PNG format so that we removed the JPEG check code in our python code.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_pascal_tf_record.py

For train.txt, you have to check on "Full path".

![sc](https://user-images.githubusercontent.com/1954306/54875594-5064bd00-4e45-11e9-975a-7dc337a36cd4.png)

Then we could create the tfrecord file.

```
IMAGES_DIR=/Users/ryo/Desktop/test_annotations/support2
ANNOTATIONS_DIR=/Users/ryo/Desktop/test_annotations/support2/annotations
IMAGE_LIST_PATH=/Users/ryo/Desktop/test_annotations/support2/train.txt
LABEL_MAP_PATH=/Users/ryo/Desktop/test_annotations/support2/label_map.pbtxt
OUTPUT_PATH=/Users/ryo/Desktop/test_annotations/support2/train.record

python object_detection/dataset_tools/rectlabel_create_pascal_tf_record.py --images_dir="${IMAGES_DIR}" --annotations_dir="${ANNOTATIONS_DIR}" --image_list_path="${IMAGE_LIST_PATH}" --label_map_path="${LABEL_MAP_PATH}" --output_path="${OUTPUT_PATH}"
```

**Comment by ryouchinsa** [comment]
We recommend your PNG file to be converted to JPG file.
Tensorflow document basically assumes it is a JPG file.

We restord the JPEG format check code.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/rectlabel_create_pascal_tf_record.py

Convert image size and format to jpg
https://rectlabel.com/help#resize_image

![sc](https://user-images.githubusercontent.com/1954306/54875787-79d31800-4e48-11e9-83b4-7044c2b0d57f.png)

After converting, the image size is resized so that you have to press "Save" button on RectLabel again.
Please confirm that image size and the image size in the annotation file is the same.

**Comment by kareemw9** [comment]
Hi, 

Thanks for the help, issue is resolved!
