### ISSUE TITLE
Add a copy boxes / template boxes feature

### ISSUE THREAD

**Issue by xvolks** [ryouchinsa/Rectlabel-support#9]
When labeling a train data, we often label similar images in a row.

For example, I currently have a document type to label, I have many images of this kind of document, each image has nearly the same boxes with the same classes at roughly the same position.

It would be great to just have a hotkey to duplicate the boxes of the previous image and just adjust the positions.

Has a workaround I currently duplicate the JSON file and change the path of the image, but it's not very productive.

**Comment by ryouchinsa** [comment]
Thanks for sharing your use case.
You might be labelling for video object detection.

We can understand the use case where you need to copy the previous label file to the current one.
In the next update, we would add the feature.

We would start coding the feature soon.

**Comment by ryouchinsa** [comment]
We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update was released.
RectLabel 1.30
Copy boxes from the previous image by "command + i"

**Comment by xvolks** [comment]
Works great! Thank you.

**Comment by xvolks** [comment]
I think this feature is incomplete. 
Let's say I have similar images to label.

I do following actions:
- label Image 1
- move to image 2
- command + i to copy boxes from image 1
- modify boxes of image 2
- move to image 3
- realize that boxes should be mostly the same than Image 1 but those from Image 2 are not
- manually box image 3 (tedious)
- done

I'd prefer do:
- label Image 1
- move to image 2
- command + i to copy boxes from image 1
- modify boxes of image 2
- move to image 3
- realize that boxes should be mostly the same than Image 1 but those from Image 2 are not
- move to image 1
- command + c
- move to image 3
- command + v
- done

**Comment by ryouchinsa** [comment]
Thanks for letting us know the detailed labelling flow.

command + i:             load labels from the previous image
shift + command + i: set image index to load labels

As default, "command + i" loads labels from the previous image.
Pressing "shift + command + i" on the 1st image, you can load the 1st image's labels on the 3rd image.

![1](https://user-images.githubusercontent.com/1954306/29000053-7f9b5910-7a9a-11e7-9f86-0945e7519939.png)

**Comment by ryouchinsa** [comment]
Added "Set Image Index to Load Labels" to "File" menu by which you can copy labels to other images.

![1](https://user-images.githubusercontent.com/1954306/29012162-5e442d7a-7b74-11e7-968d-a23123963780.png)

We submitted the new update to Apple.
When the new update is released, we will let you know.
Thank you.

**Comment by ryouchinsa** [comment]
The new update was released.

RectLabel 1.33
Added "Set Image Index to Load Labels" to "File" menu by which you can copy labels to other images
