### ISSUE TITLE
Negative examples

### ISSUE THREAD

**Issue by wuaschtikus** [ryouchinsa/Rectlabel-support#91]
Hi,

is it possible to provide negative examples for turicreate?

**Comment by ryouchinsa** [comment]
You mean the data augmentation is possible by ourselves or not.

About the data augmentation on the object detection toolkit of Turi Create, refer to this issue.
https://github.com/apple/turicreate/issues/1653

> The object detection toolkit performs data augmentation automatically, and one of the augmentations is that with probability 0.5, each image is flipped horizontally. (There’s currently no way to disable this augmentation in the Python API, but we may expose augmentation options in general at a later date.)

**Comment by romanoss** [comment]
I think he means that it could need empty xml files for samples where no object is/should be detected

**Comment by ryouchinsa** [comment]
We had the same request from another user.
In the next update, we would improve the exported CSV file to include the unlabeled images.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
The new update version 2.65 was released.

Now you can export images which are not labeled, too.
https://rectlabel.com/help#xml_to_csv_turicreate

```
path,annotations
/Users/ryo/Desktop/test_annotations/test_data_csv/1.jpg,[{"label":"bare feet","type":"rectangle","coordinates":{"x":393,"y":838,"width":62,"height":118}},{"label":"bare feet","type":"rectangle","coordinates":{"x":392,"y":881,"width":52,"height":102}}]
/Users/ryo/Desktop/test_annotations/test_data_csv/2.jpg,[]
/Users/ryo/Desktop/test_annotations/test_data_csv/3.jpg,[]
/Users/ryo/Desktop/test_annotations/test_data_csv/4.jpg,[]
/Users/ryo/Desktop/test_annotations/test_data_csv/car...jpg,[{"label":"bare feet","type":"rectangle","coordinates":{"x":296,"y":874,"width":59,"height":123}},{"label":"bare feet","type":"rectangle","coordinates":{"x":348,"y":869,"width":62,"height":107}}]
```

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.
