### ISSUE TITLE
Import COCO JSON files then export to YOLO txt files

### ISSUE THREAD

**Issue by mrteera** [ryouchinsa/Rectlabel-support#92]
My dataset is a COCO JSON file, I would like to import into RectLabel and export to YOLO txt files. Do you have any suggestion for doing this task in RectLabel?

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.

Could you show us the sample COCO JSON file?
We want to confirm how many images folders are included and the segmentation format.

**Comment by ryouchinsa** [comment]
The new update version 2.65 was released.

Now you can "Import COCO JSON file to XML files".
https://rectlabel.com/help#coco_to_xml

**Comment by mrteera** [comment]
Thank you :)
