### ISSUE TITLE
Unreliable/buggy COCO json file Export

### ISSUE THREAD

**Issue by aysark** [ryouchinsa/Rectlabel-support#94]
For a paid product, and increasing the pricing, the app needs to be held at prod level standards.  But that is not the case currently- atleast not for the COCO json export feature.

After 1 week of debugging our models... i was randomly sampling the exported COCO annotations from rectlabel.  And i stumble on many incorrect bounding boxes in one image.  This dataset is very large so i can't tell how many more, there are many that are correct.  When i view that image in rectlabel, bboxes are correctly positioned.  But when you look at the COCO json format, coords are incorrect.

This is the type of feature that is all or nothing.  If you can't get all bbox coords correct for all images then it will cause all sorts of issues later in pipeline.  From what i can tell xml format is correct.  I can't share data for obvious reasons.

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

We checked again that "bbox" coordinates in the exported COCO JSON are correct or not.
They are working fine.

We have to reproduce the problems which are happening in your environment.

> When i view that image in rectlabel, bboxes are correctly positioned. 

RectLabel scales annotations to fit to the image size when you view the annotations.
To save the scaled annotations, you have to press save button or use "Resize for all images and annotations" feature.
Could you confirm the actual image size and the image width and height in the COCO JSON file are the same?

Viewer code using pycocotools.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/checkPycocoDemo.py

2 box annotated images for the test.
https://github.com/ryouchinsa/Rectlabel-support/blob/master/test_data_coco.zip

![スクリーンショット 2019-04-13 7 43 37](https://user-images.githubusercontent.com/1954306/56070226-b350d080-5dc1-11e9-8652-e9568d6ec99f.png)

![スクリーンショット 2019-04-13 7 43 59](https://user-images.githubusercontent.com/1954306/56070233-b9df4800-5dc1-11e9-9e2a-02d2c07aea16.png)

**Comment by ryouchinsa** [comment]
Currently If you need our support to fix this problem, please let us know.

**Comment by ryouchinsa** [comment]
RectLabel and macOS Viewer show images with Exif orientation flags in the same way.

According to the Exif orientation flag, each image is rotated and shown in the front orientation.

So that the annotation file on RectLabel assumes that the image is rotated and shown in the front orientation.

https://github.com/facebookresearch/detectron2/issues/863

**Comment by ryouchinsa** [comment]
Currently RectLabel has "Remove EXIF orientation flags" feature on File menu.
After opening images, we recommend to remove EXIF orientation flags.
If necessary, you can rotate the image by 90 degrees using "Rotate the image right/left" feature on Edit menu.
