### ISSUE TITLE
Zooming in breaks my image

### ISSUE THREAD

**Issue by Gl3nninator** [ryouchinsa/Rectlabel-support#96]
Hey, First of all, I love using Rectlabel, it's amazing! I just keep having one issue where if I zoom in on an image sometimes causes my image to split into mismatched sections of the same image, like a jigsaw puzzle, the only way I have been able to replicate is if, while zoomed in, I use the brightness and contrast tool and then zoom out, that is the only way that has consistently caused the image to split apart into mismatched sections. This also caused some tags to go missing, and not save to my annotations folder, I wasted an entire day last week as I kept working through the annoyance of the glitch and didn't check to see if my work was still saving. Other than this glitch I have found Rectlabel an enjoyable tool and wanted to also thank you guys for your hard work on some great software!

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.

For the image zoom problem, we think the latest version 2.69 has solved.
Which version are you using now?

> This also caused some tags to go missing, and not save to my annotations folder, 

Could you show us how to reproduce the save problem?

Best regards,
Ryo

**Comment by ryouchinsa** [comment]
Ok. Thanks for your feedback.
