### ISSUE TITLE
Contrast and brightness reset after I change images

### ISSUE THREAD

**Issue by Gl3nninator** [ryouchinsa/Rectlabel-support#97]
Hey so when working on a darker image the contrast tool is immensely helpful but, every time I change to a new image the contrast and brightness settings return to default, adding another step to the tagging process for every image, if you could add an optional setting for keeping a set contrast and brightness that way you could help people like me without annoying other people who need it the way you have already set it up, just a thought, thanks!

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.
In the next update, when you change to a new image, we do not close the contrast dialog and maintain the values.
After changing to a new image, just pressing "Apply" button makes the same contrast and brightness change.

![スクリーンショット 2019-05-11 15 39 31](https://user-images.githubusercontent.com/1954306/57566110-b44a4180-7403-11e9-8f20-2aca6ee45934.png)

**Comment by ryouchinsa** [comment]
Hi,

- Improved so that we do not close the contrast dialog when you change to a next image.

The new update version 2.72 was released.
To show the new update on Mac App Store, press command + R to reload.

**Comment by Gl3nninator** [comment]
Awesome, thanks for the update!

**Comment by pauldevine** [comment]
I'm not able to click the apply button. The dialog box always stays present.

**Comment by ryouchinsa** [comment]
Could you tell us the details to reproduce the problem in our environment?
