### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by micah5** [ryouchinsa/Rectlabel-support#98]
I just bought Rectlabel and now upon the app is always crashing as soon as I start it.

I've tried reinstalling the app and restarting my machine but no luck. Are there any files for Rectlabel stored elsewhere that I can remove to have a fresh start?

**Comment by ryouchinsa** [comment]
Thanks for reporting the issue.
Could you show us the screenshot of the crash log?
Was RectLabel working before starting the crash?

**Comment by micah5** [comment]
How do I access the crash log?

[This](https://youtu.be/XbBhqYW-EIo) is a video of what's happening (even after reinstalling).

**Comment by ryouchinsa** [comment]
Thanks for the video.

You can find crash logs of RectLabel here.

~/Library/Logs/DiagnosticReports/
https://bjango.com/help/crashlogmac/

Could you send the crash log to support@rectlabel.com?

**Comment by ryouchinsa** [comment]
RectLabel's cache files.
~/Library/Containers/com.waysify.roi/

Copy the file below before removing the cache files.
You can import this settings file from app menu.
~/Library/Containers/com.waysify.roi/Data/settings_labels.json

**Comment by micah5** [comment]
Thank you! I deleted the cache and everything is working again

**Comment by ryouchinsa** [comment]
Thanks for fixing the problem.
If you could know what was the crash reason, let us know.

**Comment by micah5** [comment]
The xml annotation files it was reading weren't valid voc format
