### ISSUE TITLE
Brightness/Contrast Toolbar Interaction

### ISSUE THREAD

**Issue by alkbattery** [ryouchinsa/Rectlabel-support#99]
Using the brightness menu works fine but once you close it, you can no longer use hotkeys or the drop down menu to rotate the image or the file command. It also prevents new inputs from create, rotate, etc.

**Comment by ryouchinsa** [comment]
Thanks for writing the issue.
We could reproduce the problem and fix it.
When the new update is released, we will let you know.

**Comment by ryouchinsa** [comment]
The new update version 2.75 was released.
To show the new update on Mac App Store, press command + R to reload.
